### ISSUE TITLE
Mirror network not initialized by default

### ISSUE THREAD

**Issue by dalvizu** [hashgraph/hedera-sdk-java#1002]
### Description

`Client.forMainnet()` will initialize a client to talk to mainnet consensus nodes, however it looks like mirror network is not correctly set up and a AddressBookQuery (which uses the mirror node for this call) fails

### Steps to reproduce

```
        Client client = Client.forMainnet();
        // must uncomment this
        //client.setMirrorNetwork(Arrays.asList("mainnet-public.mirrornode.hedera.com:443"));

        NodeAddressBook addressBook = new AddressBookQuery()
                .setFileId(FileId.ADDRESS_BOOK)
                .execute(client);
        System.out.println(addressBook);
```

Observe: 
`[main] WARN com.hedera.hashgraph.sdk.AddressBookQuery - Error fetching address book at FileId 0.0.102 during attempt #1. Waiting 1000 ms before next attempt: UNAVAILABLE: io exception`

### Additional context

This can be fixed by explicitly setting the correct mirrornode url:
```
        client.setMirrorNetwork(Arrays.asList("mainnet-public.mirrornode.hedera.com:443"));
```

API documented here:
https://docs.hedera.com/guides/docs/mirror-node-api/rest-api

It looks like the value `hcs.mainnet.mirrornode.hedera.com:5600` is instead hard coded in the SDK:

https://github.com/hashgraph/hedera-sdk-java/blob/772a8d99136c1903c7491d681390fe6827fe5be7/sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java#L47

Discussed internally and it seems like this is an older version of the API? Might be good to confirm with the mirrornode team.

### Hedera network

mainnet

### Version

v2.14.0

### Operating system

macOS

**Comment by SimiHunjan** [comment]
hey @dalvizu ! The mirror node endpoint in the SDKs is the older one this is not public. We have an issue to get this update here https://github.com/hashgraph/hedera-sdk-java/issues/890. The impact on existing customers needs to be evaluated before we can move forward with changing it to the public mirror node endpoint.

**Comment by danielakhterov** [comment]
Closing the issue due to the previous comment.
