### ISSUE TITLE
Expose the underlying proto that was sent or received

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#1015]
### Problem

Expose the underlying protobuf message that sent or received. Response objects do not store raw protobuf response.

### Solution

Add support for this feature.

**Comment by SimiHunjan** [comment]
@steven-sheehy do you have requirements for this feature? I documented this request from one of our discussions.

**Comment by danielakhterov** [comment]
@steven-sheehy Originally when I viewed this issue my understanding was simply that the SDK should log the protobuf being sent and received which is pretty trivial to add to the SDKs. For accessing the protobuf bytes you _can_ serialize the transaction into bytes, and then decode a `proto.TransactionList` from it which will give you the raw protobuf bytes, but it won't provide the response protobuf bytes. For that I'm not really sure what would be a reasonable way to expose it.
