### ISSUE TITLE
Constructor is not transfered

### ISSUE THREAD

**Issue by JaimeSilver** [hashgraph/hedera-sdk-java#106]
https://github.com/hashgraph/hedera-sdk-java/blob/d0b77de518b8ad0cd4d46565e011b366ea4b60e8/examples/src/main/java/com/hedera/examples/contractWrappers/ContractCreate.java#L24

replace: 		return create(contract, fileID, gas, initialBalance, new byte[0], ""); 
with: 		return create(contract, fileID, gas, initialBalance, constParams, "");

**Comment by abonander** [comment]
This code no longer exists.
