### ISSUE TITLE
Filter ABI to exclude null pointer searching for "name" at constructor

### ISSUE THREAD

**Issue by JaimeSilver** [hashgraph/hedera-sdk-java#107]
https://github.com/hashgraph/hedera-sdk-java/blob/d0b77de518b8ad0cd4d46565e011b366ea4b60e8/examples/src/main/java/com/hedera/examples/contractWrappers/ContractFunctionsWrapper.java#L50

Replace: abi.get("name").equals(functionName)
With: ( abi.get("type").equals("function") && 
				 abi.get("name").equals(functionName) )

**Comment by abonander** [comment]
This code also no longer exists.
