### ISSUE TITLE
Self updating address book

### ISSUE THREAD

**Issue by dalvizu** [hashgraph/hedera-sdk-java#1080]
### Problem

Hedera proxies change very slowly, but they do change. Swirlds has a recent request from Hedera to decommission all of our Azure nodes to reduce spend, as well as remove some very old proxies, and want to minimize the impact this has on users to the SDK.

Today we hard code all of these in all previous versions, so when we decommission such a large portion there is going to be some negative impact users and we wish to strongly encourage them to upgrade.

And then going forward we would love to have them on a version that means we won't have this consideration for our slowly moving changes to node addresses, and then eventually just sort of work for permissionless use-cases. So in addition to keeping some hard coded list have the SDK capable of a self-update using the mirrornode REST API, or @lbaird offered some ideas around how we could make this a free transaction on the consensus network under some circumstances

### Solution

- Build some sort of self-updating feature, working with @rbair23 and team to see exactly what that's going to be
- Provide some sort of date on when we could expect this SDK to be released so that we can communicate that back to Hedera and start the process of sunsetting the nodes, which in turn they can relay to the council members on when they can start seeing some of their cloud spend reduced.

### Alternatives

Ask customers to frequently update their SDK to match some hard-coded values that will be relevant for a period of time or risk seeing latencies and errors in their usage of the SDK. And then regularly update the SDK on every release.

Hedera and Swirlds do not see this alternative as acceptable.

**Comment by dalvizu** [comment]
Also a priority "meta" ask - a date to expect a date. So we want to know when we can expect and SDK, but we also want to know when we can expect that date. So like - will we know by Tuesday when that SDK release be? and if not Tuesday, when? Something to manage Hedera's expectation.

**Comment by dalvizu** [comment]
cc @popowycz @lbaird @rbair23 @SimiHunjan @mehcode

**Comment by steven-sheehy** [comment]
The mirror node actually wrote a gRPC API to return node info specifically for the SDK. The SDK implemented support to query it via `AddressBookQuery`. It's just a standalone query at the moment and doesn't update the internal list of nodes the SDK uses, which is the missing piece here.

**Comment by Sean-Tedrow-LB** [comment]
I was thinking of adding two things:
- method to modify `Client` network to match a `NodeAddressBook` (simple wrapper around setNetwork() so that the results of a `AddressBookQuery` can be easily used to configure the network)
- A `NetworkUpdatePeriod`, configurable on the `Client`, perhaps defaults to 24 hours?  Nullable if not desired.  The method `.setNetworkUpdatePeriod()` would accept a `Duration`, and a boolean `updateNow`
