### ISSUE TITLE
Update Mainnet Address book

### ISSUE THREAD

**Issue by beeradb** [hashgraph/hedera-sdk-java#1082]
### Problem

The mainnet address book used by the SDK is quite old. This can result in transactions failing due to them being sent to old or invalid nodes.

### Solution

The address book should be updated. 

Additionally, I'd suggest adding a step to the release process to always pull the latest address book from the network at release time. That way, whenever the SDK ships, it will have the most up-to-date address book possible.

I've attached the current mainnet address book in both json and protobuf formats. Please let me know if I can assist in any other way.

[node-details-mainnet.102.json.zip](https://github.com/hashgraph/hedera-sdk-java/files/9310740/node-details-mainnet.102.json.zip)
[mainnet.pb.zip](https://github.com/hashgraph/hedera-sdk-java/files/9310732/mainnet.pb.zip)

**Comment by dalvizu** [comment]
FYI @SimiHunjan we'd also want to ensure that this also matches up with public docs:

https://docs.hedera.com/guides/mainnet/mainnet-nodes
