### ISSUE TITLE
Thread leak in Client

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-sdk-java#1084]
### Description

The `Client` class contains an `Executor` that it creates and manages but does not shutdown in its `close()` method. This causes a thread leak since threads grow but never decrease as clients come and go. This is more noticeable if you create a lot of temporary clients like the mirror node does to do periodic validation of consensus nodes.

### Steps to reproduce

```java
for (int i = 0; i < 10000; ++i) {
  try (Client client = Client.forMainnet()) {
    // Use it
  }
}
```

### Additional context

Example shutdown code from the `ExecutorService` javadocs:
```java
   try {
       pool.shutdown();
       if (!pool.awaitTermination(30, TimeUnit.SECONDS)) {
           pool.shutdownNow();
           if (!pool.awaitTermination(60, TimeUnit.SECONDS)) {
               log.warn("Pool did not terminate");
           }
       }
   } catch (InterruptedException ex) {
       pool.shutdownNow();
       Thread.currentThread().interrupt();
   }
```

### Hedera network

mainnet

### Version

v2.17.1

**Comment by nickpoorman** [comment]
Either that or all the static `forXYZ()` methods should probably take an executor as their first argument. In Scala, for example, this would get passed implicitly.
