### ISSUE TITLE
Add HIP-514 example

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#1094]
### Problem

HIP-514 introduces new token precompiles that Hedera supports. Add examples using the new precompiles are supported.
HIP: https://hips.hedera.com/hip/hip-514

The following are not yet support from the list:
- getTokenExpiryInfo(address)
- updateTokenExpiryInfo(address, Expiry),
- updateTokenInfo(address, HederaToken), 
- isToken(address token)
- getTokenType(address token)

### Solution

Add example

**Comment by Sean-Tedrow-LB** [comment]
After poking around a bit, I do not believe that this is ready for examples yet.

**Comment by SimiHunjan** [comment]
@Sean-Tedrow-LB can you please expand what you mean?

**Comment by Sean-Tedrow-LB** [comment]
The wrappers around the new precompiles have not been pushed to the `hedera-smart-contracts` repo.  Someone directed me to another repo where there seem to be wrappers around the new precompiles, and there appear to be new helper functions, and they've said that these will eventually be pushed to the `hedera-smart-contracts` repo, but it all looks unfinished to me.

**Comment by SimiHunjan** [comment]
The `hedera-smart-contracts` is expected to be updated with the new precompiles by this Friday. I believe @Nana-EC can point you to what they've been using for reference.

**Comment by Sean-Tedrow-LB** [comment]
Yes, that's what I'm referring to.

Nana directed me to this: https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/packages/server/tests/contracts

Is this interface, including the helper functions, the finalized interface?  Do we know that for certain?  I don't want to write these examples and documentation for them and then have to go back and rewrite them because this isn't the actual interface that is released.

**Comment by SimiHunjan** [comment]
@Sean-Tedrow-LB will remove this issue from this sprint and add it to the next one. By then the `hedera-smart-contracts` repo should be up to date. thanks!

**Comment by SimiHunjan** [comment]
Depends on:

- [ ] https://github.com/hashgraph/hedera-smart-contracts/pull/53
- [ ] https://github.com/hashgraph/hedera-smart-contracts/pull/54
