### ISSUE TITLE
Add examples for HIP-583: Transfer to evm address

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#1189]
### Problem

The SDK does not have examples for this feature. 

### Solution

Add examples when the HIP is live on previewnet.

Link to example definitions: https://github.com/hashgraph/hedera-sdk-reference/pull/65

**Comment by annamariyaivanova** [comment]
https://github.com/hashgraph/hedera-sdk-java/blob/4152aebaf5c62c2302bceff9b433ad29026b2a59/examples/src/main/java/com/hedera/hashgraph/sdk/examples/TransferUsingEvmAddressExample.java#L42 <- @0xivanov that's the resolution to the issue, right? we can close that one?
