### ISSUE TITLE
Hedera Exception: INVALID_NODE_ACCOUNT when calling client.getAccountBalance(AccountId.fromString(newAccountId1))

### ISSUE THREAD

**Issue by KamalZ18** [hashgraph/hedera-sdk-java#124]
about the new upgraded Testnets and support for 4 nodes in Hedera Java SDK v:0.5.0;
I have updated my Java code (class ClientExample) to read 4 nodes from my .env file
(which now contains 4 pairs of Node ID & Node Addresses);
I have also included the Java statement:
hederaClient1 = new Client(Map.of(nodeId1, nodeAddress1, nodeId2, nodeAddress2, nodeId3, nodeAddress3, nodeId4, nodeAddress4)); as specified by Greg Scullard.
The program creates a new account on Hedera Testnet, with new Account ID: 0.0.10480;
but it gets an error (INVALID_NODE_ACCOUNT) when it tries to get the Account Balance:
Java statement:
accountBalance1 = client1.getAccountBalance(AccountId.fromString(newAccountId1));
Here is the Output, displayed by my Program:
Hello Hedera Java SDK World from Kamal !
clientExample --> main entered.
Client Example --> getEnv entered.
clientExample --> hederaClient --> Operator ID 1: 0.0.1613
clientExample --> hederaClient --> Operator Key 1: 302e.....
clientExample --> hederaClient --> Node ID 1: 0.0.3
clientExample --> hederaClient --> Node Address 1: 0.testnet.hedera.com:50211
clientExample --> hederaClient --> Node ID 2: 0.0.4
clientExample --> hederaClient --> Node Address 2: 1.testnet.hedera.com:50211
clientExample --> hederaClient --> Node ID 3: 0.0.5
clientExample --> hederaClient --> Node Address 3: 2.testnet.hedera.com:50211
clientExample --> hederaClient --> Node ID 4: 0.0.6
clientExample --> hederaClient --> Node Address 4: 3.testnet.hedera.com:50211
Client --> constructor entered.
New Account ID: 0.0.10480
Main Program --> Client Example --> Main error --> Hedera Exception.
com.hedera.hashgraph.sdk.HederaException: INVALID_NODE_ACCOUNT
        at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:38)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:168)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:10)
        at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:31)
        at com.hedera.hashgraph.sdk.Client.getAccountBalance(Client.java:133)
        at com.hedera.hashgraph.sdk.examples.simple.ClientExample.main(ClientExample.java:107)
        at pkg.Program.main(Program.java:38)

Please could you solve the problem ?

**Comment by gregscullard** [comment]
There appears to be an issue with the SDK, it's picking a random node too many times. Within a single BalanceQuery, the `client.pickNode` method is called three times with different results

```
Picking node
Picked 3
Picking node
Picked 2
Picking node
Picked 0
```

**Comment by KamalZ18** [comment]
Hi Greg, thank you for that; OK so how do we proceed ? 
what should we do so that when the Java code does a Balance Query, it obtains an accurate Account balance on the first attempt every attempt ?
thank you, regards, Kamal.

**Comment by mehcode** [comment]
I'll take a look at trying to fix this today.

**Comment by KamalZ18** [comment]
Hi to Ryan, does that mean the problem has been resolved ?
