### ISSUE TITLE
FileInfoQuery throws UNRECOGNIZED exception for deleted files

### ISSUE THREAD

**Issue by PaulBon** [hashgraph/hedera-sdk-java#125]
FileInfoQuery works before I delete a file but after I delete a file it throws a HederaException with the text UNRECOGNIZED. Since deleting a file just marks it as deleted until it expires, I would expect FileInfoQuery to work until the file expires.

**Comment by gregscullard** [comment]
This appears to be an issue with Hedera, however the SDK now returns `FILE_DELETED` rather than `UNRECOGNIZED` until the issue is resolved on the Hedera side.
