### ISSUE TITLE
CreateStatefulContract does not work

### ISSUE THREAD

**Issue by PaulBon** [hashgraph/hedera-sdk-java#126]
The CreateStatefulContract does not work. I made the following changes which fixes some of the issues but still leaves the issue that the set_message call fails to update the message.

- changed hello_world.json to stateful.json
- changed var byteCode = ExampleHelper.parseHex(byteCodeHex); to var byteCode = byteCodeHex.getBytes();
- added the following to the new ContractCreateTranscation() call: .setAutoRenewPeriod(Duration.ofHours(1)).setGas(100_000_000)
- added .setGas(100_000_000) to the other transaction and query calls.

After making the above changes, it runs but still returns "hello from hedera!" as shown below:

contract bytecode file: 0.0.10566
new contract ID: 0.0.10567
contract returned message: hello from hedera!
contract returned message: hello from hedera!

**Comment by cylon56** [comment]
I have the same issues although the fixes above helped a lot.

I tested `Stateful.sol` in Remix-IDE just to be sure and it was able to change the message without issue. I removed the owner requirement to see if was calling from the wrong account but that didn't solve it either. It's likely something to do with the SDK's `ContractExecuteTransaction` function.

**Comment by gregscullard** [comment]
Thanks Paul, this is now fixed as a result of PR #128
