### ISSUE TITLE
`fromMnemonic` returns a private key which shouldn't be used

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-sdk-java#1263]
This isn't a bug, but rather a way that an SDK user can easily misuse the `PrivateKey::fromMnemonic` function.

By default, calling `fromMnemonic` returns the key at derivation path `m/44'/3030'/0'/0'` (`A` in the figure below). If a programmer isn't familiar with derivation paths, they will probably just use the resulting private key without a further thought. This behavior seems to be enforced by the [online documentation](https://docs.hedera.com/guides/docs/sdks/keys/recover-keys-from-a-mnemonic-phrase), which shows simple usage of `fromMnemonic`

```
//Use the mnemonic to recover the private key
PrivateKey privateKey = PrivateKey.fromMnemonic(mnemonic);
PublicKey publicKey = privateKey.publicKey();

//v2.0.0
```

However, the private key created from `fromMnemonic` should *not* be used directly - the programmer ought to go one layer deeper in the derivation path, to `m/44'/3030'/0'/0'/0'`, `m/44'/3030'/0'/0'/1'`, etc.. (`B` in the figure below). This requirement *is* documented, but only briefly, in the [function documentation](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/PrivateKey.java)

```
     * @return the recovered key; use {@link #derive(int)} to get a key for an account index (0
     * for default account)
```

![Screenshot 2022-11-29 at 10 49 44 AM](https://user-images.githubusercontent.com/102969658/204581025-1df16f6f-04f0-4b3f-8f9e-6f21ff2d83aa.png)

My understanding is that receiving to `A` is out of line with expected BIP44 behavior, and doing so might result in different wallets not finding existing funds. It seems worth it to me to make it harder for a wallet developer to mistakenly receive here.

**Comment by ochikov** [comment]
Just to add here, that in some of the SDKs, `fromMnemonic` is deprecated and the suggestion is to use `Mnemonic.from`

**Comment by alittley** [comment]
One possible suggestion:

Have 3 different versions of `fromMnemonic` (or equivalent)

1. `fromMnemonic(derivationPath)` allows the user to derive any arbitrary child in the tree
2. `fromMnemonic() returns `m/44'/3030'/0'/0'/0'`
    - This is `B` in the picture above, what I would consider the "default" address. Programmers who don't want to know anything about derivation paths should recover this private key from an end user's mnemonic
3. `fromMnemonic(int index)` returns the key at `m/44'/3030'/0'/0'/index'`, for when a user wants a new address in the same "account"

**Comment by alittley** [comment]
@dikel I agree, `fromMnemonic(mnemonic, derivationPath)` probably wouldn't be used 👍 

I'm also on board with keeping the existing function, and adding `fromMnemonic(mnemonic, passphrase, int index)`

Would it make sense to deprecate the existing `fromMnemonic` function at some point? That would allow existing applications to keep working, but hopefully steer future implementors aways from using it incorrectly.

**Comment by dikel** [comment]
@alittley I did some investigation and it turns out the Java SDK only support creating Ed25519 keys from mnemonic. And it uses the path `m/44/3030/0/0` (All are not-hardened). The JS SDK support creating both Ed25519 and ECDSA keys, but they both use the same path as the Java one (`m/44/3030/0/0`)

The correct path should be `m/44'/3030'/0'/0'/0'` for Ed25519 and `m/44'/3030'/0'/0/0` ECDSA, right?

**Comment by alittley** [comment]
@dikel You're correct, java doesn't support ECDSA from mnemonic.

Concerning the path - `PrivateKeyEd25519::derive` in the Java SDK is hardening the index with the following code:

```
        // write the index in big-endian order, setting the 31st bit to mark it "hardened"
        var indexBytes = new byte[4];
        ByteBuffer.wrap(indexBytes).order(ByteOrder.BIG_ENDIAN).putInt(index);
        indexBytes[0] |= (byte) 0b10000000;
```

The JS SDK is hardening in `slip10::derive`

```
    // set the index to hardened
    input[33] |= 128;
```

The paths you've stated are correct 👍
