### ISSUE TITLE
Request for async calls to include more info (context) in returns and error handlers.

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-sdk-java#131]
Regarding specifically CryptoTransferTransaction, the async calls executeAsync(), executeForRecordAsync() and executeForReceiptAsync().

They currently return void and the error handlers (handling HederaThrowable/HederaException) don't provide any context about the request (transaction ID, etc).

If possible, could/should the exec*Async() calls return a transaction ID and the error handler also provide that context (transaction ID or the request itself)? If the context is available (in either case), it would be useful.

**Comment by abonander** [comment]
I can overload `executeAsync()` and company to take functions that accept two arguments, though I think most users will just capture the relevant context in the lambdas.
