### ISSUE TITLE
Provide an updated release

### ISSUE THREAD

**Issue by cylon56** [hashgraph/hedera-sdk-java#132]
There's been a lot of changes to the SDK since the last release, v0.4.6, in April. 

If there was a more recent release available, developers could import the latest SDK using Maven/Gradle the way this documentation currently describes: https://docs.hedera.com/reference#import-sdk

**Comment by mehcode** [comment]
Thank you for the ping. The new release will be out today or tomorrow.

**Comment by mehcode** [comment]
This is now done - https://github.com/hashgraph/hedera-sdk-java#maven
