### ISSUE TITLE
Add delegating spender functionality to AccountAllowanceApproveTX 

### ISSUE THREAD

**Issue by petreze** [hashgraph/hedera-sdk-java#1322]
### Problem

There is a concept, introduced in [HIP-336](https://hips.hedera.com/hip/hip-336#add-cryptodeleteallowance-api), for a delegating spender account to be able to give allowances to other accounts (concerns only NFT allowances)

Basically, an account, which is given the allowance for all serials of a given NFT collection, can give allowances for single serial number NFT of the same collection to other spender accounts

[Some additional context](https://github.com/hashgraph/hedera-sdk-js/issues/1427)

### Solution

Add the missing functionality to the `AccountAllowanceApproveTX` which sets the delegating_sender field of the NftAllowances proto. In that way, an account, which already has the approveForAll allowance to a NFT collection, can give individual allowances to other spender accounts

**Comment by dikel** [comment]
Fixed by #1349
