### ISSUE TITLE
Add functionality to remove allowance for all serials in AccountAllowanceDeleteTX

### ISSUE THREAD

**Issue by petreze** [hashgraph/hedera-sdk-java#1323]
### Problem

Based on the ERC standard that the SDK follows, users can:

- _approve allowance for all serials of a given NFT collection, then remove allowance for all serials of the NFT collection_
- _approve allowance for individual NFT serial, then remove allowance for individual NFT serial_

The current implementation of the SDK does **not** allow users to remove allowance for all serials of an NFT collection. Thus, this has to be added

[Some additional context](https://github.com/hashgraph/hedera-sdk-js/issues/1427)

### Solution

When the field `approved_for_all` inside the `NftAllowance` proto object is set to `false`  in `CryptoApproveAllowanceTransactionBody` (in SDKs case: `AccountAllowanceApproveTransaction`) we revoke the token for the spender for which we have previously allocated approve_for_all allowance. The SDK has to support this functionality which is explained in [HIP-336](https://hips.hedera.com/hip/hip-336#add-cryptodeleteallowance-api)

**Comment by dikel** [comment]
Fixed by #1349
