### ISSUE TITLE
Smart contract calls with parameters other than string

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#138]
Trying to run a smart contract function with a `uint8` input value to no avail.
This is how the call is put together, but the contract reverts.

```
byte newValue = 10;
        byte[] newValueBytes = ByteBuffer.allocate(1).put(newValue).array();
        new ContractExecuteTransaction(client).setContractId(newContractId)
        .setGas(100_000_000)
        .setFunctionParameters(CallParams.function("set_value")
            .add(newValueBytes))
        .executeForReceipt();
```
Suggest implementing methods for setting a `boolean`, `byte`, `int`, `long`, `bigInteger` and `address`.

Also, the methods for recovering data from a call are limited to `int` and `string`, what about `boolean`, `address`, `BigInteger`, etc... for datatypes larger than int or long (e.g. int256).

Finally, how would an array of values be passed to a contract and returned from it ?

**Comment by gregscullard** [comment]
This is the solidity I used for reference

```
pragma solidity >=0.4.22 <0.6.0;

contract StatefulContract {
    // the contract's owner, set in the constructor
    address owner;

    // the message we're storing
    string message;
    uint8 value;

    constructor(string memory message_) public {
        // set the owner of the contract for `kill()`
        owner = msg.sender;
        message = message_;
        value = 5;
    }

    function set_message(string memory message_) public {
        // only allow the owner to update the message
        if (msg.sender != owner) return;
        message = message_;
    }

    function set_value(uint8 value_) public {
        // only allow the owner to update the value
        if (msg.sender != owner) return;
        value = value_;
    }

    // return a string
    function get_message() public view returns (string memory) {
        return message;
    }

    // return an integer
    function get_value() public view returns (uint8) {
        return value;
    }

    // recover the funds of the contract
    function kill() public { if (msg.sender == owner) selfdestruct(msg.sender); }
}
```

**Comment by abonander** [comment]
@gregscullard those were just the methods I decided to include on an MVP implementation of that class. I'll take some time to enumerate the types Solidity supports and their Java counterparts so I have a nice checklist to work with.

**Comment by abonander** [comment]
Looking at: https://solidity.readthedocs.io/en/v0.5.9/abi-spec.html#types

`Java/Solidity`

- [ ] `boolean/bool`
- [ ] Signed integer types: `byte/int<8>`, `short/int<16>`, `int/int<32>`, `long/int<64>`, `BigInteger,N/int<N>`
- [ ] unsigned variants of the above
- [ ] `<new Java type>/address`, `<new Java type>/address_payable`
- [ ] `<new Java type>/function`
- [ ] Array types of all of the above

Omitted:
* Fixed point types are not currently implemented in the Solidity spec or EthereumJ
