### ISSUE TITLE
Hedera Exception: INVALID_NODE_ACCOUNT when calling client.getAccountBalance(newAccountId1)

### ISSUE THREAD

**Issue by KamalZ18** [hashgraph/hedera-sdk-java#140]
Hedera Exception: INVALID_NODE_ACCOUNT when calling client.getAccountBalance(AccountId.fromString(newAccountId1));
about the new upgraded Testnets and support for 4 nodes in Hedera Java SDK v:0.5.0;
I have updated my Java code (class ClientExample) to read 4 nodes from my .env file (which now contains 4 pairs of Node ID & Node Addresses);
I have also included the Java statement: hederaClient1 = new Client(Map.of(nodeId1, nodeAddress1, nodeId2, nodeAddress2, nodeId3, nodeAddress3, nodeId4, nodeAddress4));
as specified by Greg Scullard; the program creates a new account on Hedera Testnet, with new Account ID: 0.0.10480;
but it gets an error (INVALID_NODE_ACCOUNT) when it tries to get the Account Balance:
Java statement: accountBalance1 = client1.getAccountBalance(AccountId.fromString(newAccountId1));
Here is the Output, displayed by my Program:
Hello Hedera Java SDK World from Kamal !
clientExample --> main entered.
Client Example --> getEnv entered.
clientExample --> hederaClient --> Operator ID 1: 0.0.1613
clientExample --> hederaClient --> Operator Key 1: 302e.....
clientExample --> hederaClient --> Node ID 1: 0.0.3
clientExample --> hederaClient --> Node Address 1: 0.testnet.hedera.com:50211
clientExample --> hederaClient --> Node ID 2: 0.0.4
clientExample --> hederaClient --> Node Address 2: 1.testnet.hedera.com:50211
clientExample --> hederaClient --> Node ID 3: 0.0.5
clientExample --> hederaClient --> Node Address 3: 2.testnet.hedera.com:50211
clientExample --> hederaClient --> Node ID 4: 0.0.6
clientExample --> hederaClient --> Node Address 4: 3.testnet.hedera.com:50211
Client --> constructor entered.
New Account ID: 0.0.10480
Main Program --> Client Example --> Main error --> Hedera Exception.
com.hedera.hashgraph.sdk.HederaException: INVALID_NODE_ACCOUNT
        at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:38)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:168)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:10)
        at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:31)
        at com.hedera.hashgraph.sdk.Client.getAccountBalance(Client.java:133)
        at com.hedera.hashgraph.sdk.examples.simple.ClientExample.main(ClientExample.java:107)
        at pkg.Program.main(Program.java:38)
This issue persists, please could you solve the problem ?

**Comment by gregscullard** [comment]
I've just tried this with the `master` branch of the SDK and it works

in `ExampleHelper.java` I changed the client declaration to setup 4 nodes

```
        var client = new Client(Map.of(
        		AccountId.fromString("0.0.3"), "0.testnet.hedera.com:50211"
        		,AccountId.fromString("0.0.4"), "1.testnet.hedera.com:50211"
        		,AccountId.fromString("0.0.5"), "2.testnet.hedera.com:50211"
				,AccountId.fromString("0.0.6"), "3.testnet.hedera.com:50211"
        		)
		);
```

Then altered the simple `CreateAccount` example as follows

```
        // Generate a Ed25519 private, public key pair
        var newKey = Ed25519PrivateKey.generate();
        var newPublicKey = newKey.getPublicKey();

        System.out.println("private key = " + newKey);
        System.out.println("public key = " + newPublicKey);

        var client = ExampleHelper.createHederaClient();
        for (int i=0; i < 10; i++) {
        	System.out.println("-----------------------");
        	var receipt = new AccountCreateTransaction(client)
	        		.setKey(newPublicKey)
	        		.setInitialBalance(10)
	        		.executeForReceipt();
        	System.out.println("account = " + receipt.getAccountId().getAccountNum());
        }
```

I added some debug statements to the SDK to see which nodes were being picked, and I saw some random selection and no errors, this was run several times without errors

Did you `mvn install` the SDK after getting it from GitHub ? If not, the old version remained in your local maven repository so the bug fix wasn't compiled locally. Also make sure you `mvn install` the examples too to make sure it re-loads the latest SDK version and doesn't use a cached version.

Please confirm this works and close the issue.

**Comment by KamalZ18** [comment]
I Downloaded and Mvn Installed the new version of Hedera Java SDK; I re-compiled my Java program and ran it 4 times using a .env file with 4 nodes.
So therefore this issue has been resolved.
