### ISSUE TITLE
DecoderException for private key string (DecoderException) when reading OPERATOR_KEY from .env file

### ISSUE THREAD

**Issue by edisinovcic** [hashgraph/hedera-sdk-java#141]
Exception in thread "main" org.bouncycastle.util.encoders.DecoderException: exception decoding Hex string: invalid characters encountered in Hex string
	at org.bouncycastle.util.encoders.Hex.decode(Unknown Source)
	at com.hedera.hashgraph.sdk.crypto.ed25519.Ed25519PrivateKey.fromString(Ed25519PrivateKey.java:94)
	at client.hederaClient(client.java:20)
	at client.main(client.java:47)
Caused by: java.io.IOException: invalid characters encountered in Hex string
	at org.bouncycastle.util.encoders.HexEncoder.decode(Unknown Source)
	... 4 more

It's private key so I would rather not place it here. :)

**Comment by gregscullard** [comment]
HI, it's likely your private key was incorrect, this is an example of a private key:
302e020100300506032b65700422042070920011823121f616df91ba60fdb10bcd609395e41e87c49f920f6d053832e8

**Comment by edisinovcic** [comment]
Tnx for the quick response, in this repo I've been playing with SDK, this is the privatekey that was created.

https://github.com/blockchain-it-hr/hedera-java-sdk/blob/master/wallet/privateKey
I've used stable version of java SDK.

Here is generateKeys java class: https://github.com/blockchain-it-hr/hedera-java-sdk/blob/master/src/main/java/generateKeys.java

**Comment by gregscullard** [comment]
Do you have example code that exhibits this behaviour ?

**Comment by edisinovcic** [comment]
Yeah, it's this one: https://github.com/blockchain-it-hr/hedera-java-sdk/blob/master/src/main/java/generateKeys.java

**Comment by edisinovcic** [comment]
@gregscullard Did I use some older code or something of a kind?

**Comment by abonander** [comment]
@edisinovcic your clone/fork is pretty out of date now, you probably want to update it. Additionally, the private key you generated does not appear to be a properly encoded Ed25519 private key; it should have a prefix of `302e0201003...` as that's the common prelude to the encoded key format.

**Comment by edisinovcic** [comment]
Yeah sure, it's quite old so I can close is. Tnx for the info.
