### ISSUE TITLE
Add output to files (can be encrypted)

### ISSUE THREAD

**Issue by edisinovcic** [hashgraph/hedera-sdk-java#142]
https://github.com/hashgraph/hedera-sdk-java/blob/master/examples/src/main/java/com/hedera/hashgraph/sdk/examples/simple/CreateAccount.java

Inside this file, we can add the output to files. It has to be encrypted by the secret in that we can set in .env file, so it's easier to use later on private and public keys.  

Just printing to console is not ideal. 

Then again writing to file private key is also not ideal despite encryption. So let me know your thoughts.

If it's okay for you I can help with this.

**Comment by gregscullard** [comment]
Hi, these are merely examples of the use of the SDK, logging private keys to console should be removed by the security conscious developer. Encrypting the output would make it harder for less experienced developers to later decrypt the output so they can use the generated keys with the account they have created.

Besides, key generation should not be performed server side, only client side to ensure that the server application doesn't know the private key of its users.

**Comment by mehcode** [comment]
As its non-trivial to read/write from/to an encrypted x509-packaged ed25519 private key, we should probably add support for that directly in the SDK. I'd say this is a reasonable request. 

@edisinovcic  For the record, for my applications I've used kubernetes and its secrets management so I haven't needed something like this.

**Comment by edisinovcic** [comment]
@gregscullard definitely agree with it, but then it should probably be implemented by devs like that. They will just copy it and use it like that and by providing more secure solution. It's all a matter does it make sense to put resources on this. 

@mehcode definitely secrets are best for using on kubernets. On the other hand, probably a majority of developers don't know kubernets so creating something like docker-compose and Dockerfiles that they can run locally and test the sdk would be okay. Or add kubernets template that can be used for this and then deploy locally in minikube or similar would also be okay.

**Comment by abonander** [comment]
I have a prototype in #215 that produces encrypted keystore files (currently only holding 1 key). These can also be produced and consumed by the JS/Typescript SDK: https://github.com/hashgraph/hedera-sdk-js/blob/master/src/Keys.ts#L109
