### ISSUE TITLE
Download Data Files like Fee,Address Book from Node

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-sdk-java#144]
The address for the corresponding data files on the main-net are as follows
101 - Address Book
102 - Fee Schedule

The Fee Schedule will have two set of schedules, current & future.
All the clients are required to download a copy of the file for calculating the fees.

**Comment by abonander** [comment]
We decided that this would also be a good time to implement requesting the cost for a given query since we need to know how much it will cost to download these files.

**Comment by gregscullard** [comment]
Correction, getting confirmation on the below, but I believe file numbers are as follows

file 0.0.102 contains the address book (NodeAddressBook proto)
file 0.0.111 contains the fee schedule (FeeSchedule proto)
file 0.0.112 contains the exchange rate (ExchangeRateSet proto)
There is a file 0.0.101, but I'm not sure of its contents right now. Will confirm.

**Comment by mehcode** [comment]
@abonander Let's add 3 associated constants on `FileId`. I'm thinking `FileId.ADDRESS_BOOK`, `FileId.FEE_SCHEDULE`, and `FileId.EXCHANGE_RATE` ?

**Comment by mehcode** [comment]
There is now `FileId.SPECIAL_NAME` constants to allow easy downloading of these special files.
