### ISSUE TITLE
Example StatefulContract.java not working

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#148]
Says method `addString()` not defined (used while passing parameters to functions)
Works by changing to `add()` but add() only accepts string parameters. Not uint, int, address etc.

To pass ints, I tried first converting the int to a byte array like so:
```
byte newValue = (byte) 3;  // x is an integer
byte[] newValueBytes = ByteBuffer.allocate(1).put(newValue).array();
new ContractExecuteTransaction(client).setContractId(newContractId)
            .setGas(100_000_000)
            setConstructorParams(
                CallParams.constructor()
                    .add( newValueBytes ));
```

On calling  `"get_int()"` I get "32" instead of 3 which makes no sense.
And When I later tried calling "set_int()" it does absolutely nothing

(Working on `Stateful.sol` provided in examples. Just changed `get/set_message()` to `get/set_int()` respectively)

**Comment by gregscullard** [comment]
Make sure you have recompiled (mvn clean install) the SDK. The `master` branch definitely has `addString` and others now.

Having said that I'm getting a `CONTRACT_REVERT_EXECUTED` when running the smart contract, investigating that at the moment.

**Comment by rahul-ki** [comment]
I recompiled and am on `master` branch. Problem still persists. Only `add`.

**Comment by rahul-ki** [comment]
`mvn clean install` itself fails:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project sdk-examples: Compilation failure: Compilation failure:
[ERROR] C:\Users\rahco\Desktop\Rahul\Blockchain\Hedera\hedera-sdk-java\examples\src\main\java\com\hedera\hashgraph\sdk\examples\advanced\CreateStatefulContract.java:[63,20] error: cannot find symbol
[ERROR]   symbol:   method addString(String)
[ERROR]   location: class CallParams<Constructor>
[ERROR] C:\Users\rahco\Desktop\Rahul\Blockchain\Hedera\hedera-sdk-java\examples\src\main\java\com\hedera\hashgraph\sdk\examples\advanced\CreateStatefulContract.java:[86,16] error: cannot find symbol
[ERROR]   symbol:   method addString(String)
[ERROR]   location: class CallParams<Function>
```

**Comment by gregscullard** [comment]
After further investigation and reverting to an older version of the SDK I found the following

The constructorParameter for the contract instantiation with the old SDK was:

`\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\022hello from hedera!\000\000\000\000\000\000\000\000\000\000\000\000\000\000`

with the new SDK it's:

`\210\352\353l\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\022hello from hedera!\000\000\000\000\000\000\000\000\000\000\000\000\000\000`

**Comment by gregscullard** [comment]
PR #149 appears to fix the failing contract instantiation

**Comment by gregscullard** [comment]
@rahul-ki if you look here: https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/CallParams.java

You can see addString at line 49. 

Sounds like your environment is picking up another version of the SDK.
Might be worth clearing up your local maven repository, maybe delete the sdk source and fetch again from GitHub ?

**Comment by gregscullard** [comment]
Contract instantiation with constructor resolved in PR #151

**Comment by rahul-ki** [comment]
Great thanks! `mvn clean install` did add `addString` later on.

**Comment by gregscullard** [comment]
Fixed - closing
