### ISSUE TITLE
Add Unit tests for `TopicMessage`

### ISSUE THREAD

**Issue by deyanzz** [hashgraph/hedera-sdk-java#1546]
### Problem

Class `TopicMessage` is missing Unit tests.

### Solution

To add the following Unit tests for `TopicMessage.java`:

- `constructWithArgs`
- `ofSingle`
- `ofMany`

For reference see `TopicMessageUnitTests.cc` from the [C++ SDK](https://github.com/hashgraph/hedera-sdk-cpp).

**Comment by thenswan** [comment]
@deyanzz Is it duplicate of #1540 ?

**Comment by deyanzz** [comment]
You're right, @thenswan. It's duplicating [#1540](https://github.com/hashgraph/hedera-sdk-java/issues/1540). Closing this issue.
