### ISSUE TITLE
Better support for sending transactions to a specific proxies and custom networks

### ISSUE THREAD

**Issue by dalvizu** [hashgraph/hedera-sdk-java#1569]
### Problem

There are certain times where we want to send a transaction to a particular node. For example to understand if a particular node is having problems, sending a test query to that node is something we are required to do.

I imagine this is also a problem for targeting local instances? In my use-case I want to hit specific proxies for previewnet, testnet, and mainnet.

The SDK makes this difficult to do. You can craft a network like so:

```
  Map<String, AccountId> myNetwork = new HashMap<>();
  myNetwork.put("127.0.0.1:50211", new AccountId(3));
  Client client = Client.forNetwork(myNetwork)
```

There are some very big downsides to this approach: for starters, it does not support TLS. That is because no attempt to load the address book is loaded, as that path is not executed. Client provides a `setTransportSecurity()` flag but this appears to have no effect.

If I didn't want to disable the transport security and provide certificate, I have no way of doing that either. I might be able to do it by loading from a json config but there is no documentation or examples on the structure of that configuration, so I don't know how to use that method.

### Solution

Provide methods to initialize a network like mainnet and then restrict it to a single proxy?

Or alternatively change a lot of the accessors? 

Client is a final class, for example. There's very useful methods to load from an address book I could probably use to accomplish my use-case, but that are private or package protected so I can't use them.

Similarly, the Network class which does a lot of the heavily lifting of Client is also package protected, so I can't use it.

### Alternatives

There's not alot honestly. Short of patching the SDK and cutting my own library I don't see a way to accomplish what I'm trying to do.

**Comment by thenswan** [comment]
Hi @dalvizu, thank you for submitting this detailed proposal. We will review it with team members and get back to you.

**Comment by thenswan** [comment]
@dalvizu please check [this PR](https://github.com/hashgraph/hedera-sdk-java/pull/1570) and comments in the file (I quoted some parts of this issue and replied to them in the code). Let me know if that asked your questions and if you still have any :)

**Comment by thenswan** [comment]
Hi @dalvizu, please let me know if we're good to close this issue or if you need some additional support 🙂

**Comment by thenswan** [comment]
Hi @dalvizu, I am closing this issue, and if you need any additional support on this -- feel free to reopen 🙂
