### ISSUE TITLE
Exception --> IllegalAccessError: sdk.Transaction tried to access private field Client.random !

### ISSUE THREAD

**Issue by KamalZ18** [hashgraph/hedera-sdk-java#157]
about the Hedera Java SDK v:0.5.1 and the Create File Java example and
support for multi-node (4 nodes) networks;
I have downloaded the master from GitHub and done an Mvn Install
to create the latest SDK-0.5.1 JAR file;
I imported the CreateFile.java program from Hedera Java SDK\examples\src\main\java\com\hedera\hashgraph\sdk\examples\advanced;
Next I compiled and ran the Create File example program to create a File on the Hedera Network, it crashed with the following output:
Hello Hedera Java SDK World from Kamal !
Create File --> main entered.
ExampleHelper --> getOperatorKey entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> createHederaClient entered.
ExampleHelper --> createHederaClient --> Operator ID 1: 0.0.1613
ExampleHelper --> createHederaClient --> Operator Key 1: 302e.....
ExampleHelper --> createHederaClient --> Node ID 1: 0.0.3
ExampleHelper --> createHederaClient --> Node Address 1: 0.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 2: 0.0.4
ExampleHelper --> createHederaClient --> Node Address 2: 1.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 3: 0.0.5
ExampleHelper --> createHederaClient --> Node Address 3: 2.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 4: 0.0.6
ExampleHelper --> createHederaClient --> Node Address 4: 3.testnet.hedera.com:50211
Client --> constructor entered.
ExampleHelper --> getOperatorId entered.
ExampleHelper --> getOperatorId --> Account ID: 0.0.1613
ExampleHelper --> getOperatorKey entered.
Exception in thread "main" java.lang.IllegalAccessError: class com.hedera.hashgraph.sdk.Transaction tried to access private field com.hedera.hashgraph.sdk.Client.random (com.hedera.hashgraph.sdk.Transaction and com.hedera.hashgraph.sdk.Client are in unnamed module of loader 'app')
at com.hedera.hashgraph.sdk.Transaction.getReceiptDelayMs(Transaction.java:240)
at com.hedera.hashgraph.sdk.Transaction.executeAndWaitFor(Transaction.java:220)
at com.hedera.hashgraph.sdk.Transaction.executeForReceipt(Transaction.java:261)
at com.hedera.hashgraph.sdk.TransactionBuilder.executeForReceipt(TransactionBuilder.java:178)
at com.hedera.hashgraph.sdk.examples.advanced.CreateFile.main(CreateFile.java:46)
at pkg.Program.main(Program.java:70)
Please could Hedera resolve this problem.

**Comment by abonander** [comment]
@KamalZ18 can you perform a clean build and install of the SDK? The code should not compile if it's attempting to access a private field. This leads me to believe there's some bytecode mismatch in the compiled `.class` files for the SDK, like `Client.java` did not get recompiled correctly when you updated your clone of the SDK.

**Comment by KamalZ18** [comment]
Hi to Austin Bonander,
I have just performed a clean build and re-installed of the Java SDK; I ran my Program again and the same error as above occurred.
I did the following:
step 1: delete all of the Mavin Cache: C:\Users\Kamal\.m2\repository\*.*
step 2: remove (delete) the current Hedera Java SDK v:0.5.1 (delete all files);
step 3: download the new version 0.5.1 of the Hedera Java SDK (pull the Master version of Hedera Java SDK) from GitHub;
step 4: Maven Install >MvnInstalOutF1
shall I attach the output from Maven install: MvnInstalOutF1.txt it is a very big file.

**Comment by abonander** [comment]
@KamalZ18 what version of the JDK are you using?

**Comment by KamalZ18** [comment]
Hi to Austin Bonander,

I am using Java Development Kit version: 11.0.3

My Java_Home environment var is set so:
JAVA_HOME=C:\Program Files\Java\jdk-11.0.3

C:\Users\Kamal>Javac --version !displays:
javac 11.0.3

thank you
regards
Kamal Zada

**Comment by abonander** [comment]
Is there a reason you're downloading the source and running `mvn install` locally? You should just be able to use the published version from the Maven central repository.

**Comment by KamalZ18** [comment]
My IDE is Ms-Visual Studio, not very good; It does not have Maven nor Gradle; so I have to manually download Hedera Java SDK from GitHub and
do DOS commands to run Mvn Install locally on my Windows PC.
The Mvn Install generates the SDK-0.5.1 JAR file which should be the same as the published SDK-0.5.1 JAR file. So the problem persists.
I am sure that the problem is with the Hedera Java SDK source code;
Have you tried running the Create File Java example and using a .env file with 4 nodes (multi-node) ?

**Comment by gregscullard** [comment]
Just tried it, it works.

**Comment by gregscullard** [comment]
Visual studio or Visual Studio Code ? The latter supports maven.
https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven

**Comment by KamalZ18** [comment]
My IDE is Visual studio which does not support Maven nor Gradle;
Shall I do an Mvn Install using Java JDK v:10; then compile my App & Java SDK and execute the JAR file using Java JDK v:10 ?

**Comment by gregscullard** [comment]
I also run maven from command line. I've tried java 10 and 11 as per below, and run the fileCreate example from my IDE (Eclipse) without any issues. This is with 4 nodes setup as follows:

```
    public static Client createHederaClient() {
        // To connect to a network with more nodes, add additional entries to the network map
        var nodeAddress = Objects.requireNonNull(getEnv().get("NODE_ADDRESS"));
        var client = new Client(Map.of(
                AccountId.fromString("0.0.3"), "0.testnet.hedera.com:50211"
                ,AccountId.fromString("0.0.4"), "1.testnet.hedera.com:50211"
                ,AccountId.fromString("0.0.5"), "2.testnet.hedera.com:50211"
                ,AccountId.fromString("0.0.6"), "3.testnet.hedera.com:50211"
                )
        );
```

May be worth switching to Eclipse,IntelliJ or Visual Studio Code for Java Development, you're likely going to find it much easier, although there will be a learning curve associated with a new IDE.

```
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /Users/gregscullard/Downloads/apache-maven-3.6.0
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Users/gregscullard/Downloads/openjdk-11.0.2_osx-x64_bin/jdk-11.0.2.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"

IDE (eclipse): OpenJDK11
```

```
java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /Users/gregscullard/Downloads/apache-maven-3.6.0
Java version: 10.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"

IDE (eclipse): OpenJDK10
```

**Comment by KamalZ18** [comment]
Hi to Greg,
thank you for the info above;
please could you also copy & paste the output displayed of the execution of the Create File Java example from the Java SDK; so that I can check the source code and output with my copy of Create File ?

**Comment by gregscullard** [comment]
All I get is the new file ID output to the console. The code I ran is the example in the /examples of the sdk, save for the modification to `createHederaClient` I posted above to use four nodes.

**Comment by gregscullard** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/9549788/60607108-e9985d80-9dbc-11e9-8d29-1fa679c5cb80.png">
 is what eclipse shows after the example has run.

**Comment by gregscullard** [comment]
You appear to have debug statements in your code
```
ExampleHelper --> getOperatorKey entered.
Exception in thread "main" java.lang.IllegalAccessError: class com.hedera.hashgraph.sdk.Transaction tried to access private field com.hedera.hashgraph.sdk.Client.random (com.hedera.hashgraph.sdk.Transaction and com.hedera.hashgraph.sdk.Client are in unnamed module of loader 'app')
```
Any chance one of those is throwing the error ?

**Comment by gregscullard** [comment]
Can you run the example without any modifications at all ?

**Comment by KamalZ18** [comment]
Hi Greg,
thank you very much for your help; we have now resolved the problem.
It is mostly my fault; the Example Helper and Client classes Java bytecode that were being used were compiled classes from the old SDK v:0.5.0; even though I had the latest version of the Java SDK v:0.5.1; whenever I compile & built my App, it picked up the old Example Helper and Client classes Java bytecode; so I have now deleted them and everything is OK.

**Comment by gregscullard** [comment]
Thanks @KamalZ18, glad you got it sorted. Closing issue.
