### ISSUE TITLE
Intermittent Timeout Issues on TestNet

### ISSUE THREAD

**Issue by Scratchmine-Scratchyours** [hashgraph/hedera-sdk-java#1588]
### Description

 I have my code running in Jupyter and have isolated the token creation, NFT minting, wallet balance calls, and it works about 85% of the time but sometimes it'll just fail with a time-out error:

"jvm exception occurred: exceeded maximum attempts for request with last exception being com.hedera.hashgraph.sdk.maxattemptsexceededexception"

I won't make any changes and then rerun it and it will work. Sometimes I'll run the get balances and it will work but then token creation will fail and vice versa. 

### Steps to reproduce

Run any of the functions listed above in a loop on the test net until it fails.

### Hedera network

testnet

### Version

2.21.0

### Operating system

Windows

**Comment by SimiHunjan** [comment]
@Scratchmine-Scratchyours are you able to share the exact code sample you are running? How long are you typically running the functions in a loop until you see the timeout error? Minutes/hours/days? Or is it just totally random? Thanks!

**Comment by Scratchmine-Scratchyours** [comment]
Sure, they are really straightforward and I haven't found any way to
consistently recreate the error. It'll just fail with a time out randomly.

It'll fail on token creation, balance queries, or 20 iterations into a
token minting loop. The loop has a max iteration count of 120 or so. I
think it takes about 5 - 10 minutes if there are no issues.

def create_token(**kwargs):

    max_supply = kwargs.get("max_supply")
    token_name = kwargs.get("token_name")
    token_symbol = kwargs.get("token_symbol")

    token_tran = TokenCreateTransaction(
    ).setTokenName(token_name
    ).setTokenSymbol(token_symbol
    ).setTokenType(TokenType.NON_FUNGIBLE_UNIQUE
    ).setDecimals(0
    ).setInitialSupply(0
    ).setSupplyType(TokenSupplyType.FINITE
    ).setMaxSupply(max_supply
    ).setTreasuryAccountId(OPERATOR_ID
    ).setAdminKey(OPERATOR_KEY.getPublicKey()
    ).setSupplyKey(OPERATOR_KEY.getPublicKey()
    ).setPauseKey(OPERATOR_KEY.getPublicKey()
    ).setFreezeKey(OPERATOR_KEY.getPublicKey()
    ).setWipeKey(OPERATOR_KEY.getPublicKey()
    ).freezeWith(client
    ).sign(OPERATOR_KEY
    ).execute(client)

    receipt = token_tran.getReceipt(client)
    token_id = receipt.tokenId

    print(f'Success! token id: {token_id.toString()}')
    print('test'+str(receipt))
    print(token_id)
    print( token_id.toString())
    return (token_id.toString())
# print(f"New t



create_token(
    max_supply = 10,  # Set your desired max supply
    token_name = "thetimes081023",  # Name your token
    token_symbol = "tt"  # Provide a symbol for your token
)




def mint_new_nft(**kwargs):

    tk_id = kwargs.get("token_id")
    cid = kwargs.get("cid")

    token_id = TokenId.fromString(tk_id)

    token_mint = TokenMintTransaction(
    ).setTokenId(token_id
    ).addMetadata([ord(s) for s in cid]
    ).freezeWith(client
    ).sign(OPERATOR_KEY
    ).execute(client)

    receipt = token_mint.getReceipt(client)
    serial_number = receipt.serials[0]
    print(f'Success! NFT serial number {serial_number}')
    hedera_serials = serial_number


    return(serial_number)

**Comment by SimiHunjan** [comment]
awesome thank you for sharing this information!

**Comment by SimiHunjan** [comment]
Hey @Scratchmine-Scratchyours ! Sorry it looks like there was a misunderstanding. We thought the issue was observed in one of the official Hedera supported SDKs. It looks like the example code provided is using the community maintained python SDK. We don't offer support to triage issues for community SDKs. You would need to open the issue in the Hedera python repo. We did try to reproduce the issue and were not successful using the Java SDK. If you are able to reproduce the issue using the Hedera Java SDK please reopen the issue.
