### ISSUE TITLE
Improve the documentation on how to get started with the Java SDK

### ISSUE THREAD

**Issue by thenswan** [hashgraph/hedera-sdk-java#1595]
### Problem

Multiple community members have submitted issues where their projects are failing due to incorrect setup. For reference, see:
- **Java**: #1614 and #1615
- **Android**: https://github.com/hashgraph/hedera-sdk-java/issues/1566 and [this commit](https://github.com/aadityapaliwal/WalletConnectDemo/compare/main...1566).

### Solution

To improve the documentation on how to get started with the Java SDK

**Comment by iron4548** [comment]
Would be good to know how to properly set up gradle build dependencies for a Spring Boot Application too.

**Comment by thenswan** [comment]
Thanks for your feedback 👍 @iron4548
