### ISSUE TITLE
getExpirationTime returns default unix timestamp

### ISSUE THREAD

**Issue by isiko-de** [hashgraph/hedera-sdk-java#161]
`client.getAccount(accountId).getExpirationTime();` returns `1970-01-01T00:00:00Z` instead of the actual expiration time of the account

**Comment by abonander** [comment]
This would be the case if the `CryptoGetInfoResponse` did not actually contain an `expirationTime` as the protobuf is returning the default instance with 0 for the seconds/nanoseconds fields. We can change that to return `null` instead, however this may be a bug with Hedera, not sure yet.

Either way I have been able to reproduce this using both the node and operator accounts on the testnet.

**Comment by gregscullard** [comment]
This appears to be an issue with Hedera, raising issues on the Hedera platform.

**Comment by gregscullard** [comment]
Confirmed issue with Hedera, engineering team added fix to their backlog.

**Comment by abonander** [comment]
@gregscullard this issue has changed on the latest testnet; now the problem appears to be that it's returning some unit wildly out of range. (It might be nanoseconds? That puts the expiration time in 2262.)

```
cryptoGetInfo {
  header {
    cost: 8
  }
  accountInfo {
    accountID {
      accountNum: 2
    }
    contractAccountID: "0000000000000000000000000000000000000002"
    proxyAccountID {
    }
    key {
      keyList {
        keys {
          ed25519: "\n\250\342\020d\306\036\253\206\342\251\301dV[Nz\232AF\020n\nl\320:\2149Z\021\016\222"
        }
      }
    }
    balance: 4799282615223668859
    generateSendRecordThreshold: 5000000000000000000
    generateReceiveRecordThreshold: 5000000000000000000
    expirationTime {
      seconds: 9223372036854775807
    }
    autoRenewPeriod {
      seconds: 17775
    }
  }
}
```

**Comment by abonander** [comment]
The genesis account is probably just using the max value of an int however as a test account I created gets an `expirationTime` of August 31.
