### ISSUE TITLE
Failed pre-check with the status `PAYER_ACCOUNT_NOT_FOUND`

### ISSUE THREAD

**Issue by bibash28** [hashgraph/hedera-sdk-java#1644]
### Description

I followed these steps in Android(Java)
https://docs.hedera.com/hedera/getting-started/create-an-account

but I am getting error.
Error: com.hedera.hashgraph.sdk.PrecheckStatusException: Hedera transaction 0.0.15594008@1699959357.602000000 failed pre-check with the status PAYER_ACCOUNT_NOT_FOUND

### Steps to reproduce

Run https://docs.hedera.com/hedera/getting-started/create-an-account

### Additional context

![image](https://github.com/hashgraph/hedera-sdk-java/assets/18188709/28fa379c-55a3-4653-9e09-70754e8525ab)

### Hedera network

testnet

### Version

None

### Operating system

Other

**Comment by gregscullard** [comment]
Hi, it looks like you initialised the SDK with account id `0.0.15594008` which doesn't exist on testnet or mainnet and that's what the error you're getting telling you. The payer for the transaction (0.0.15594008) isn't a valid account Id on the network you're sending the transaction to.

**Comment by bibash28** [comment]
Yes, it looks like my id is wrong. Thank you for your response. The issue is resolved.
