### ISSUE TITLE
v2.29's transaction valid start no longer caters for time drift between client and node

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#1652]
### Description

Previous versions of the SDK used to remove a random number of seconds (between 5 and 8s) to the client's time to include in the transactionID's valid start time. Removing a few seconds allowed for some time drift between the client and the receiving node and prevented spurious INVALID_TRANSACTION_START.

A recent change to the SDK to better handle potential duplicate transaction ids removed this time drift mitigation leading to errors that don't happen with the prior versions of the SDK.

The code that was removed is:

`Instant instant = Clock.systemUTC().instant().minusNanos((long) (Math.random() * 5000000000L + 8000000000L));`

### Steps to reproduce

A client's clock needs to be ahead of a node's clock by 1s in order to reproduce the issue.

### Hedera network

mainnet, testnet, previewnet

### Version

v2.29

### Operating system

None

**Comment by SimiHunjan** [comment]
@gregscullard is the CM still blocked because of this issue?
