### ISSUE TITLE
Convert groovy Gradle scripts to Kotlin

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-sdk-java#1662]
## Description

In preparation for the automated release integration, we need to bring the Gradle configuration inline with the rest of the Hedera projects. To do so, we need to convert the groovy scripts to Kotlin and introduce the standard `build-logic` mechanism used by the other Gradle projects.

**Comment by Petyo-Lukanov** [comment]
Hey @nathanklick, this issue seems to be completed in this PR - https://github.com/hashgraph/hedera-sdk-java/pull/1732
I will go ahead and close the issue now. Let me know if you believe there are any pending items related to this conversion to Kotlin.
