### ISSUE TITLE
Add support for spotless formatting of the CI pipelines and Gradle scripts

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/hedera-sdk-java#1669]
## Description

As part of the release automation changes, we need to add spotless support for formatting and enforcing proper formatting of the CI pipeline configuration files and the Gradle build scripts.

**Comment by jjohannes** [comment]
This will be solved by #2033

**Comment by rbarkerSL** [comment]
Blocked by #2033

**Comment by jjohannes** [comment]
Done by #2033 and active now. If anything is not working as expected, please report here: 
https://github.com/hiero-ledger/hiero-gradle-conventions/issues

...as it should work the same in all Hiero/Hedera Gradle setups.
