### ISSUE TITLE
The Java class Node should be declared public !

### ISSUE THREAD

**Issue by KamalZ18** [hashgraph/hedera-sdk-java#167]
Hi to Hedera,
please could you make the Node class public?
on GitHub --> Hedera Java SDK there exists a Java class --> Node.java;
location: https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/Node.java
please could you make the Node class public?
Because in Android studio whenever I compile & build my DAppt complains that the Node class is not public so I cannot use Node in my Java code.
All of the other classes are declared public.

**Comment by mehcode** [comment]
That's not part of the public API. Can I ask what your use case is here?

**Comment by KamalZ18** [comment]
Hi to Ryan Leckey,
I am developing a Native Android DApp to interface with the Hedera Testnet using the Hedera Java SDK and Android studio IDE and Android SDK;
the Android IDE Java compiler & Gradle are very strict when it comes to compiling Java code;
in Gradle I insert the dependency: implementation 'com.hedera.hashgraph:sdk:0.5.1'; this JAR file contains the Node class;
but because it is not declared Public, the Java compiler gives me an error;
I have had to copy & paste the Client.java class code into my Android IDE and make changes so that it compiles;
the Client java code uses the Node class, but because it is not declared Public, the Java compiler gives me an error;
So I have had to copy & paste the Node.java class code as well;
but if you declare Node class to be public, it saves me having to copy & paste the Node.java code.

**Comment by mehcode** [comment]
This SDK doesn't officially support Android except through the instructions in #103. We can release an Android-compatible artifact in the next couple days. It's been on the todo list.

**Comment by KamalZ18** [comment]
Hi to Ryan Leckey,
How is the Android compatible artifact going ?

**Comment by KamalZ18** [comment]
I am developing the Hedera Java SDK that is Android compatible, which will resolve the problem.
