### ISSUE TITLE
Incorrect validation of require(string) in HederaCall

### ISSUE THREAD

**Issue by ahdrew** [hashgraph/hedera-sdk-java#169]
For The method require(@Nullable String setValue, String errMsg) in HederaCall, the condition of the validation is setValue != null && **setValue.isEmpty()** which is incorrect. It should be setValue != null && **!setValue.isEmpty()** instead

**Comment by abonander** [comment]
Good catch. We're only using this in `GetBySolidityIdQuery` so the impact should fortunately be minor.
