### ISSUE TITLE
ContractExecuteTransaction.executeForRecord() - more return values

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#172]
From Smart Contract calls and transactions, need array return types like
* `bool[]`
* `address[]`
etc.

for a solidity method like:
```
function bulkTransfer(address[] memory _tos, uint256[] memory _values)
        public whenNotPaused
        returns (bool[] memory successes) {

            require(_tos.length == _values.length, "length of tos and values aren't same");

            bool[] memory successes = new bool[](_tos.length);
            for(uint i=0; i<_tos.length; i++) {
                successes[i] = _transfer(msg.sender, _tos[i], _values[i]);
            }

        return successes;
    }
```

**Comment by abonander** [comment]
@rahul-ki we originally thought not to implement `bool[]` as it's incredibly wasteful in the Solidity ABI. Each boolean in the array takes up a whole 32 bytes. If you have control over the contract bytecode, you probably want a custom bitvector based off `bytes` instead.

`address[]` is reasonable to add though.

**Comment by mehcode** [comment]
Please open a specific method for a specific ask here if you need something. We don't mind adding what is needed. It's not complicated, just tedious.
