### ISSUE TITLE
INVALID_CONTRACT_ID exception when trying to Create a Stateful Contract !

### ISSUE THREAD

**Issue by KamalZ18** [hashgraph/hedera-sdk-java#173]
about the Hedera Java SDK v:0.5.1 and the Create Stateful Contract example and support for multi-node (4 nodes) networks;
I imported the CreateStatefulContract.java program from Hedera Java SDK\examples\src\main\java\com\hedera\hashgraph\sdk\examples\advanced;
Next I compiled and ran the Create Stateful Contract example program to create a Smart Contract on the Hedera Network, but it crashed with the following output:
Hello Hedera Java SDK World from Kamal !
CreateStatefulContract --> main entered.
ExampleHelper --> getOperatorKey entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> createHederaClient entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> createHederaClient --> Operator ID 1: 0.0.1613
ExampleHelper --> createHederaClient --> Operator Key 1: [redacted]
ExampleHelper --> createHederaClient --> Node ID 1: 0.0.3
ExampleHelper --> createHederaClient --> Node Address 1: 0.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 2: 0.0.4
ExampleHelper --> createHederaClient --> Node Address 2: 1.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 3: 0.0.5
ExampleHelper --> createHederaClient --> Node Address 3: 2.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 4: 0.0.6
ExampleHelper --> createHederaClient --> Node Address 4: 3.testnet.hedera.com:50211
Client --> constructor entered.
Client constructor --> nodesMapP1 elements: {0.0.3=0.testnet.hedera.com:50211, 0.0.4=1.testnet.hedera.com:50211, 0.0.5=2.testnet.hedera.com:50211, 0.0.6=3.testnet.hedera.com:50211}
nodesMap Entry --> Key: 0.0.3; Value: 0.testnet.hedera.com:50211
nodesMap Entry --> Key: 0.0.4; Value: 1.testnet.hedera.com:50211
nodesMap Entry --> Key: 0.0.5; Value: 2.testnet.hedera.com:50211
nodesMap Entry --> Key: 0.0.6; Value: 3.testnet.hedera.com:50211
Client constructor --> channels: {0.0.3=com.hedera.hashgraph.sdk.Node@694abbdc, 0.0.4=com.hedera.hashgraph.sdk.Node@2e005c4b, 0.0.5=com.hedera.hashgraph.sdk.Node@4567f35d, 0.0.6=com.hedera.hashgraph.sdk.Node@5ffead27}
ExampleHelper --> getOperatorId entered.
ExampleHelper --> getOperatorId --> Account ID: 0.0.1613
Client --> pickNode entered.
Client --> getNodeForId entered.
Client --> pickNode entered.
CreateStatefulContract --> contract bytecode file: 0.0.36730
Client --> pickNode entered.
Client --> getNodeForId entered.
CreateStatefulContract --> new contract ID: 0.0.36731
Client --> pickNode entered.
Main Program --> CreateStatefulContract --> Main error --> Exception.
com.hedera.hashgraph.sdk.HederaException: INVALID_CONTRACT_ID
        at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:38)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:199)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:15)
        at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:43)
        at com.hedera.hashgraph.sdk.examples.advanced.CreateStatefulContract.main(CreateStatefulContract.java:78)
        at pkg.Program.main(Program.java:81)
Please could you resolve this problem ?

**Comment by abonander** [comment]
@KamalZ18 your log included your account's private key on the testnet; I went ahead and removed that for you but you should probably not use that on mainnet in the future because while you can delete Github edit history, who knows where else this was archived in the meantime.

Can you try again but skip the code that creates the contract and just use `ContractId.fromString("0.0.36731")` as `newContractId`?

**Comment by KamalZ18** [comment]
OK, thank you; I now get the INSUFFICIENT_TX_FEE exception.

**Comment by abonander** [comment]
Closing in favor of #182 then.
