### ISSUE TITLE
`TCK-Java`: Implement JSON-RPC methods for `AccountDeleteTransaction`

### ISSUE THREAD

**Issue by agadzhalov** [hashgraph/hedera-sdk-java#1735]
We should implement JSON-RPC methods (endpoints) for `AccountDeleteTransaction` for the Go TCK server

**Add the following methods:**

Account:
- deleteAccount

**Comment by 0xivanov** [comment]
fixed in https://github.com/hashgraph/hedera-sdk-java/pull/1988
