### ISSUE TITLE
AccountId has a fromString method but FileId has not.

### ISSUE THREAD

**Issue by isiko-de** [hashgraph/hedera-sdk-java#180]
I think we should keep things consistent and easy to use around Ids and add a `fromString()` method to all kinds of Id's (in this case `AccountId` haven't checked the others) – Right now if I want to read an `AccountID`, I have to instantiate a new `FileId` and pass it three longs (`shardNum`, `realmNum` and `fileNum`) which I find inconvenient.

**Comment by abonander** [comment]
@isiko-de what SDK version are you using? This is already fixed on `master` so we might just need to publish an update.

**Comment by abonander** [comment]
This should be in the next version of the SDK which we just published today as `0.5.2`; it's not showing on Maven Central yet as the update takes some time to propagate.
