### ISSUE TITLE
Release sdk with protobuf-java instead of protobuf-javalite

### ISSUE THREAD

**Issue by KamilBemowskiGFT** [hashgraph/hedera-sdk-java#1804]
### Problem

My project uses grpc and I can build only with support for the protobuf-java instead of protobuf-javalite. Could you build and release a new version supporting the full protbuf-java? I saw the config files for the build with protobuf-java, but I couldn't find any release.

### Solution

Build and release new sdk with support for protobuf-java not protobuf-javalite.

**Comment by thenswan** [comment]
Hi @KamilBemowskiGFT,

Can you please advise how urgent it is for you (is it blocking you right now)?

Thanks 🙏🏻

**Comment by PIOTR-OSTROWSKI-GFT** [comment]
Hi @thenswan ,

Unfortunately this is currently a blocker for us as many of our services already use "full" `protobuf-java` library and trying to use the `protobuf-javalite` would cascade to a whole lot of other places, so it's not really feasible.

Thanks for your support

**Comment by thenswan** [comment]
Hey @KamilBemowskiGFT @PIOTR-OSTROWSKI-GFT,

The new version of Java SDK was just released (including `sdk-full`) -- please let me know if you have any other questions or we can close this issue.

**Comment by thenswan** [comment]
Closing as completed. 
Feel free to reopen if you will encounter any issues with the `sdk-full`.
