### ISSUE TITLE
INSUFFICIENT_TX_FEE exception when I try to Create a Stateful Contract (CreateStatefulContract.java)

### ISSUE THREAD

**Issue by KamalZ18** [hashgraph/hedera-sdk-java#182]
I am still getting a INSUFFICIENT_TX_FEE exception when I try to Create a Stateful Contract (CreateStatefulContract.java);
I have set the Client class --> DEFAULT_MAX_TXN_FEE = 500000000L; but to no avail.
Here is the full output from the program:
Hello Hedera Java SDK World from Kamal !
CreateStatefulContract --> main entered.
ExampleHelper --> getOperatorKey entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> createHederaClient entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> createHederaClient --> Operator ID 1: 0.0.1613
ExampleHelper --> createHederaClient --> Operator Key 1: 
ExampleHelper --> createHederaClient --> Node ID 1: 0.0.3
ExampleHelper --> createHederaClient --> Node Address 1: 0.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 2: 0.0.4
ExampleHelper --> createHederaClient --> Node Address 2: 1.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 3: 0.0.5
ExampleHelper --> createHederaClient --> Node Address 3: 2.testnet.hedera.com:50211
ExampleHelper --> createHederaClient --> Node ID 4: 0.0.6
ExampleHelper --> createHederaClient --> Node Address 4: 3.testnet.hedera.com:50211
Client --> constructor entered.
Client constructor --> nodesMapP1 elements: {0.0.6=3.testnet.hedera.com:50211, 0.0.5=2.testnet.hedera.com:50211, 0.0.4=1.testnet.hedera.com:50211, 0.0.3=0.testnet.hedera.com:50211}
nodesMap Entry --> Key: 0.0.6; Value: 3.testnet.hedera.com:50211
nodesMap Entry --> Key: 0.0.5; Value: 2.testnet.hedera.com:50211
nodesMap Entry --> Key: 0.0.4; Value: 1.testnet.hedera.com:50211
nodesMap Entry --> Key: 0.0.3; Value: 0.testnet.hedera.com:50211
Client constructor --> channels: {0.0.6=com.hedera.hashgraph.sdk.Node@6356695f, 0.0.5=com.hedera.hashgraph.sdk.Node@4f18837a, 0.0.4=com.hedera.hashgraph.sdk.Node@359f7cdf, 0.0.3=com.hedera.hashgraph.sdk.Node@1fa268de}
ExampleHelper --> getOperatorId entered.
ExampleHelper --> getEnv entered.
ExampleHelper --> getOperatorId --> Account ID: 0.0.1613
ExampleHelper --> getEnv entered.
ExampleHelper --> getOperatorKey entered.
ExampleHelper --> getEnv entered.
TransactionBuilder --> constructor entered.
Client --> getMaxTransactionFee entered.
TransactionBuilder --> executeForReceipt entered.
Client --> pickNode entered.
Client --> getNodeForId entered.
Client --> pickNode entered.
contract bytecode file: 0.0.37172
TransactionBuilder --> constructor entered.
Client --> getMaxTransactionFee entered.
TransactionBuilder --> executeForReceipt entered.
Client --> pickNode entered.
Client --> getNodeForId entered.
Client --> pickNode entered.
new contract ID: 0.0.37173
Client --> pickNode entered.
TransactionBuilder --> constructor entered.
Client --> getMaxTransactionFee entered.
Main Program --> CreateStatefulContract --> Main error --> Exception.
com.hedera.hashgraph.sdk.HederaException: INSUFFICIENT_TX_FEE
        at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:38)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:199)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:15)
        at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:43)
        at com.hedera.hashgraph.sdk.examples.advanced.CreateStatefulContract.main(CreateStatefulContract.java:82)
        at pkg.Program.main(Program.java:81)

**Comment by abonander** [comment]
@KamalZ18 the transaction fees on the testnet were recently raised so you need to call `Client.setMaxTransactionFee()` with a higher number than `100_000` as that is the default which is no longer sufficient.

**Comment by KamalZ18** [comment]
Hi to Austin,
I have set in the Client class --> DEFAULT_MAX_TXN_FEE = 500000000L;
is that not enough, do I also need to call:
Client.setMaxTransactionFee(500000000L) ?

**Comment by abonander** [comment]
My mistake, I didn't look at the stack trace. Whatever query being executed at line 82 needs to have a payment attached. You can do that with `.setDefaultPayment(long amount)` which creates and attaches a payment transaction with that amount; do note though that query payments are not a maximum amount like with transactions, but an exact amount which will be deducted from your account.

**Comment by mehcode** [comment]
Query payments should now be defaulting ( in master, not yet released )
