### ISSUE TITLE
Update examples to reflect fee calculation changes for query and transaction fees

### ISSUE THREAD

**Issue by abonander** [hashgraph/hedera-sdk-java#183]
Query fees should be addressed by #175 when COST_ANSWER is fixed to not require payment.

Transaction fees should be fixed by adding `.setTransactionFee` to all builder usages, or raising `Client.DEFAULT_MAX_TXN_FEE`.

**Comment by rahul-ki** [comment]
Yes definitely! Setting `Client.DEFAULT_MAX_TXN_FE` will definitely be useful!

**Comment by mehcode** [comment]
This shouldn't be needed if the default fee is now 1hbar. No fees should need to be explicitly defined.

**Comment by gregscullard** [comment]
Depending on transaction type and the hbar price, 1hbar may not be sufficient !

**Comment by rahul-ki** [comment]
@mehcode upon using the latest maven repo (0.6.2), I actually need to also do `client.setMaxTransactionFee(...)` and then in individual transactions I need to set this too.

In testnet, I don't need to do this client.setMaxTxFee(), but in mainnet I definitely have to. JSilver advised me to do this too

**Comment by abonander** [comment]
@rahul-ki fees may be different between mainnet and testnet. If you set `client.setMaxTransactionFee()` to the highest value you have to set on an individual transaction builder then you shouldn't need to set fees on individual transactions.
