### ISSUE TITLE
Mirror node acceptance tests fail after upgrading Java SDK to 2.33.0

### ISSUE THREAD

**Issue by jascks** [hashgraph/hedera-sdk-java#1839]
### Description

With Java SDK 2.33.0, running the mirror node acceptance tests results in:
```
2024-06-09T19:31:50.268Z  WARN main c.h.m.t.e.a.c.SDKClient Unable to validate node 0.0.8 after 30.13 s: Error, while processing getAccountTokens mirror node query 
2024-06-09T19:32:20.462Z  WARN main c.h.m.t.e.a.c.SDKClient Unable to validate node 0.0.9 after 30.19 s: Error, while processing getAccountTokens mirror node query 
2024-06-09T19:32:50.568Z  WARN main c.h.m.t.e.a.c.SDKClient Unable to validate node 0.0.5 after 30.11 s: Error, while processing getAccountTokens mirror node query 
...
2024-06-09T19:38:23.456Z  INFO main c.h.m.t.e.a.c.SDKClient Validated 0 of 14 endpoints in 7.056 min 
```
This particular example is running on `previewnet`, but this occurs on `integration` and `testnet` as well.

The acceptance test framework queries the mirror node for the network nodes (`/api/v1/network/nodes`). That is collected into a `Map` and then `Client.forNetwork()` is called to create the SDK client. In addition, `setMirrorNetwork()` is invoked on the client based on an acceptance test property value, in this case `previewnet.mirrornode.hedera.com:443`.

Debugging this a bit, each node is validated by issuing an `AccountBalanceQuery`. The gRPC call itself is successful, but then `Executable.execute()` invokes `grpcRequest.mapResponse()`  which ultimately gets to `MirrorNodeRouter.getMirrorNodeUrl()` which, because the `ledgerId` is null, returns a URL for the  mirror node at `http://previewnet.mirrornode.hedera.com:5551` rather than `https://previewnet.mirrornode.hedera.com`. This results in the above errors.

```java
    static String getMirrorNodeUrl(List<String> mirrorNetwork, LedgerId ledgerId) {
        Optional<String> mirrorNodeAddress = mirrorNetwork.stream()
            .map(address -> address.substring(0, address.indexOf(":")))
            .findFirst();

        if (mirrorNodeAddress.isEmpty()) {
            throw new IllegalArgumentException("Mirror address not found");
        }

        String fullMirrorNodeUrl;

        if (ledgerId != null) {
            fullMirrorNodeUrl = "https://" + mirrorNodeAddress.get();
        } else {
            // local node case
            fullMirrorNodeUrl = "http://" + mirrorNodeAddress.get() + ":" + LOCAL_NODE_PORT;
        }

        return fullMirrorNodeUrl;
    }
```
I understand 2.33.0 introduces queries to the mirror node for the SDK's own purposes. I did not see anything in the release notes or the documentation for the SDK for that release regarding any changes that would be required for existing client applications.

If I drop back to 2.32.0, everything works as expected. If I modify the acceptance test client setup code to set the `ledgerId`, that too works. What should be the experience of Java SDK users in this regard.

### Steps to reproduce

Checkout the [mirror node repo](https://github.com/hashgraph/hedera-mirror-node) and update the`com.hedera.hashgraph:sdk` dependency on line 68 of `build.gradle.kts` from 2.32.0 to 2.33.0 and run a single acceptance test scenario.

The described failures above will occur as the tests are starting up and the network is being probed.

### Hedera network

previewnet

### Version

2.33.0

### Operating system

macOS

**Comment by thenswan** [comment]
Hey @jascks, thanks for raising it. Should be closed by #1840. Will take into account in case there would be need to bring back solution with querying the Mirror Node 😄
