### ISSUE TITLE
Too many threads when multiple Clients are used in a single process

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-sdk-java#1844]
### Problem

A single Client can only provide limited throughput mostly due to this setting in network nodes:
```
netty.prod.maxConcurrentCalls = 10
```
Load tests require creating many Clients (10-150) in order to achieve maximum network throughput.
Unfortunately, each client creates its own thread pool with the number of threads equals to the number of CPUs on the machine. Running such test with 150 Clients on a 48-CPU machine creates 150*48 = 7200 threads, for which there is little justification.
I think sharing a single thread pool between multiple Clients should be acceptable.

### Solution

- share a static thread pool between multiple `Clients`
- provide a way to configure the size of the pool (`Runtime.getRuntime().availableProcessors()` by default)

**Comment by 0xivanov** [comment]
Hi @OlegMazurov, thanks for submitting this issue.
Do you think exposing an API for `Client` , where you can set the `ExecutorService` as a parameter would be effective for you?
This way you would have the ability to configure singleton thread pool for multiple clients and also configure the size of the pol

**Comment by 0xivanov** [comment]
> A single Client can only provide limited throughput mostly due to this setting in network nodes

Does this mean that having more than 10 threads in the pool is meaningless?

**Comment by OlegMazurov** [comment]
> Do you think exposing an API for Client , where you can set the ExecutorService as a parameter would be effective for you?

Yes, it would work. However, I think the default behavior should also change: a singleton thread pool for multiple clients. If somebody wants a separate thread pool per client, they can use the API.

> > A single Client can only provide limited throughput mostly due to this setting in network nodes
> 
> Does this mean that having more than 10 threads in the pool is meaningless?

No, I use asynchronous calls so responses may come in bulk and require more parallelism to process. Moreover, the `maxConcurrentCalls` parameter is hidden (not exposed by the network) and can be set arbitrarily. The client should not make any assumptions about it.

**Comment by 0xivanov** [comment]
I would not change the default behaviour because no one has complained about this at this point. There are more complexities that would come with this change, like closing the client/network/executor, since now they are closing simultaneously. Maybe some time in the future.

You can see the newly provided apis [here](https://github.com/hashgraph/hedera-sdk-java/pull/1987)

**Comment by 0xivanov** [comment]
fixed in https://github.com/hashgraph/hedera-sdk-java/pull/1987
