### ISSUE TITLE
INSUFFICIENT_TX_FEE not getting solved

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#186]
As advised on Discord, I changed `getCost()` in `QueryBuilder.java` to `return client.getMaxTransactionFee();`
It threw error: `Possible lossy conversion from long to int` or `NullAway dereferenced expression client is @Nullable`
This error is also confirmed by others on the discord chat.

I resolved this temporarily by returning `42_000_000` in`getCost()`. 
In my app - I set `client.setMaxTransactionFee(1_000_000_000);` and it still throws `INSUFFICIENT_TX_FEE`
**This ONLY happens with ContractCall methods for me.**
Since the launch date is coming closer, we are in intense pressure, especially because we can't test with the dynamic fees.

I hope you can advise me!

**Comment by abonander** [comment]
Go ahead and change the return type of `getCost()` to `long`. That method should be going away soon.

**Comment by abonander** [comment]
Alternatively, you can use `.setPaymentDefault(1_000_000_000)` on your `ContractCallQuery` (though I would try something like `100_000_000`).

**Comment by rahul-ki** [comment]
@abonander - changing the return to long was the first thing I did. That threw this error:
```
[NullAway] dereferenced expression client is @Nullable
[ERROR]     (see http://t.uber.com/nullaway )
```

So if getCost() is getting removed should I leave it as 100_000 for now?
Will try with setPaymentDefault

**Comment by rahul-ki** [comment]
@abonander interestingly, `.setPaymentDefault()` takes in no parameter. Passing in that int throws error.

**Comment by abonander** [comment]
@rahul-ki update your SDK version to `0.5.2`, that's the one that has that method.

**Comment by rahul-ki** [comment]
Facepalm I changed to 05.2 days ago and forgot that my IDE doesn't auto-update. Anyway everything works!
