### ISSUE TITLE
Update the repository settings for the required checks on PRs/pushes to main.

### ISSUE THREAD

**Issue by thenswan** [hashgraph/hedera-sdk-java#1903]
After PR #1895 merges the existing checks will not be valid (code compiles / example code tests / unit tests). We will need to add in checks the new named CI/CD items.

**Comment by rbarkerSL** [comment]
Created feshdesk ticket for this: https://swirldslabs.freshdesk.com/a/tickets/3384

**Comment by thenswan** [comment]
cc @SimiHunjan @agadzhalov
