### ISSUE TITLE
HederaException doesn't extend RuntimeException

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#192]
Raising on behalf of a developer at an internal hackathon, he expected the HederaException to extend RuntimeException, thus removing the necessity to always wrap calls with a try/catch.

**Comment by abonander** [comment]
@gregscullard `HederaException` wraps precheck codes which are not always fatal; for example, `BUSY` which just necessitates re-running the call at a later time or `UNKNOWN` where the transaction failed to reach consensus before `executeAndWaitForReceipt()` timed out.

I'm not a big fan of checked exceptions myself but it seems like we need _some_ way to signal to the programmer that some of these codes need to be handled. We could possibly be more granular here and only throw checked exceptions for recoverable codes.

**Comment by gregscullard** [comment]
This makes sense. Closing.
