### ISSUE TITLE
TRANSACTION_OVERSIZE

### ISSUE THREAD

**Issue by patel512** [hashgraph/hedera-sdk-java#194]
While Deploying My Contract I am getting this Error . 
JAVA SDK Version 0.5.0

**Comment by abonander** [comment]
@patel512 could please try updating to the latest SDK, version `0.5.2`, and let us know if this is still happening?

**Comment by mehcode** [comment]
@patel512 That error code (if correctly returned and not a bug in the SDK) means that you need to break your contract byte code into chunks and submit in multiple FileAppend transactions.

**Comment by patel512** [comment]
@mehcode  I  breaked my code into parts and appended in multiple Transaction but now I am getting Error   INSUFFICIENT_GAS  even though  I have set my gas to  70000000000 and total no of line in my sc is  137

**Comment by rahulasati** [comment]
@mehcode any update on this facing the same issue INSUFFICIENT_GAS

**Comment by publu** [comment]
Same here.

**Comment by mehcode** [comment]
Can either @rahulasati or @publu run the example for this and see if you get the same error? 

---

@abonander and I can't reproduce this so it's hard for us to help here. Our examples work and they seem to have a similar scenario to what you describe.

It would help and we could likely help you quikcly if you could PR an example that breaks with this issue.

**Comment by abonander** [comment]
@patel512 calling `execute()` alone does not get the final result of the transaction; if it returns successfully it just means the node has accepted it for processing. `executeForReceipt()` or `execute()`+`queryReceipt()` will get the final result of the transaction.

**Comment by mehcode** [comment]
Please re-open if there is a specific issue with the SDK you're still experiencing.

**Comment by hynese** [comment]
Below is the code I use to handle chunking my 8.32 kB smart contract:

`int MAX_FILE_SIZE = 4000`

`Hbar MAX_TX_FEE_CONTRACT = new Hbar(30)`

```java
// upload file (chunk if necessary):
        TransactionReceipt txReceipt_file = null;
        int nIters = (int) Math.ceil(evmBinary.getBytes().length/Helper.MAX_FILE_SIZE);
        System.out.println("File is " + String.format("%.2f", ((float)evmBinary.length()/1000)) + " kB long");
        System.out.println(nIters + " chunks will be uploaded");
        for(int i = 0; i <= nIters; i++) {
            int from = Helper.MAX_FILE_SIZE * i;
            int to = (i == nIters) ? from + evmBinary.getBytes().length % Helper.MAX_FILE_SIZE : Helper.MAX_FILE_SIZE * (i + 1);

            byte[] segment = Arrays.copyOfRange(evmBinary.getBytes(), from, to);

            if (i == 0) {
                // create a new file
                // save the file:
                var tx_file = new FileCreateTransaction();
                tx_file.setContents(segment);
                tx_file.addKey(operatorKey.publicKey);
                tx_file.setExpirationTime(Instant.now().plus(Duration.ofSeconds(7890000)));
                tx_file.setMaxTransactionFee(Helper.MAX_TX_FEE);

                TransactionId txId_file = tx_file.execute(client);
                txReceipt_file = txId_file.getReceipt(client);
                // print out the result:
                System.out.println("Result of file save:");
                System.out.println(txReceipt_file.status);
                System.out.println("File lives at: " + txReceipt_file.getFileId());
            } else {
                // append chunk to existing file
                System.out.println("Appending chunk: " + i + " (" + segment.length + " bytes)");
                new FileAppendTransaction().setFileId(txReceipt_file.getFileId())
                        .setMaxTransactionFee(Helper.MAX_TX_FEE)
                        .setContents(segment).execute(client);
            }
        }
```
