### ISSUE TITLE
TransactionRecord.transferList protobuf definition out of sync with testnet

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-sdk-java#195]
testnet returns transferList via field number 10 in the TransactionRecord protobuf message definition, whereas the current SDK is expecting it in field number 9. At some point these definitions diverged.

The protobuf definition between client and server are incompatible in this regard and the SDK will not return any transferLists to callers.

**Comment by abonander** [comment]
We're going to fix this by removing the copies of the protobufs here and using the published Maven version of https://github.com/hashgraph/hedera-protobuf as the main source of truth so it doesn't have to be manually kept in-sync.
