### ISSUE TITLE
FEE_SCHEDULE_FILE_PART_UPLOADED marked as error

### ISSUE THREAD

**Issue by jbair06** [hashgraph/hedera-sdk-java#1950]
### Description

When submitting a FileUpdate along with the required FileAppends in order to update the `0.0.111` fees file, getting the receipt returns or throws a ReceiptStatusException. The FEE_SCHEDULE_FILE_PART_UPLOADED response is not an error, but is a response to indicate that the file is not complete and requires more FileAppends until a Fees file is fully uploaded.

### Steps to reproduce

Ran this on local node (the issue showed up when updating the file on TESTNET):
1. Create a FileUpdateTransaction for file `0.0.111` with the proper fee payer and signatures. 
2. Execute the transaction: 
`final var transactionResponse = transaction.execute(client);`
3. Get the receipt:
 `receipt = transactionResponse.getReceipt(client);`

It throw a ReceiptStatusException.

### Hedera network

other

### Version

v2.24.1

### Operating system

macOS

**Comment by SimiHunjan** [comment]
[feeSchedules.bin.zip](https://github.com/user-attachments/files/16667305/feeSchedules.bin.zip)

you can use this test file to reproduce the issue
