### ISSUE TITLE
Calling a Contract view type function through call Local gives LOCAL_CALL_MODIFICATION exception  while the same function can be called by ContractExecuteTransaction

### ISSUE THREAD

**Issue by patel512** [hashgraph/hedera-sdk-java#199]
Does ContractExecuteTransaction execute with less gas when a view type function is called

**Comment by abonander** [comment]
If your contract code is not confidential would you mind sharing the snippet of the function you're trying to call?

Otherwise, can you check to make sure the function you're calling is marked `view` or `pure`? `ContractCallQuery` is not allowed to modify contract state.

**Comment by patel512** [comment]
@abonander  here is the function I was trying to call

function getpinCode() public view returns(int) {
        return pincode;
    }

**Comment by abonander** [comment]
@patel512 is this still occurring?

**Comment by mehcode** [comment]
Re-open if this is still occurring.
