### ISSUE TITLE
Update actions per step-security to used pinned commit shas

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-sdk-java#1994]
## Background

Step-security is maintaining a list of actions that are not pinned to a full length commit sha. We need to update
our actions to pin full-length commit shas as checkout versionbs. This story intends to cover an audit of all
actions used within the repository.

## Acceptance Criteria

- [ ] All required actions have been updated with full-length commit shas.

**Comment by san-est** [comment]
There were no actions with missing full-length commit shas in the main workflow directory.
Do we update the ones that are in the "disabled" folder?
