### ISSUE TITLE
`Client.setNetworkFromAddressBook(NodeAddressBook)` does not set certificate information

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-sdk-java#1995]
### Description

`Client.setNetworkFromAddressBook(NodeAddressBook)` is both a public method that can be called directly by the user and also used internally when the address book is refreshed automatically from the mirror node. The certificate info inside the `NodeAddressBook` parameter is not passed through to `Node.setAddressBookEntry()` so TLS does not work unless we also specify `Client.setVerifyCertificates(false)`, which is less secure.

Not tested, but believe it also results in the refreshed address book clearing the cert hash info from the built-in address book.

### Steps to reproduce

Invoke `Client.setNetworkFromAddressBook(NodeAddressBook)` with a NodeAddressBook that has a list of consensus nodes each with 50212 TLS port and cert hash info. 

### Hedera network

testnet

### Version

2.38.0

### Operating system

None

**Comment by 0xivanov** [comment]
Hey @steven-sheehy . Can you check out https://github.com/hashgraph/hedera-sdk-java/pull/1901 . The newly added override of `setNetworkFromAddressBook()` might be fixing the issue.

**Comment by 0xivanov** [comment]
We decided to make it optional just to make sure we are not breaking something. 
Is it possible for the mirror node team to test using the new function just to be sure everything works?
We could remove the overloaded method in one of the next releases if it's Ok.

**Comment by 0xivanov** [comment]
Closing and adding a follow-up issue to enable this by default. https://github.com/hashgraph/hedera-sdk-java/issues/2015
