### ISSUE TITLE
IllegalStateException: Some node account IDs did not map to valid nodes in the client's network

### ISSUE THREAD

**Issue by Loganistic** [hashgraph/hedera-sdk-java#2044]
Hi,

Our wallet uses the Hedera Java SDK (com.hedera.hashgraph:sdk:2.29.1).
I'm reaching out because we encountered the following error on Hedera Java SDK when executing a transaction that is from the external dApp.

> IllegalStateException: Some node account IDs did not map to valid nodes in the client's network.

The code in the SDK where the exception occurs is as follows: https://github.com/hashgraph/hedera-sdk-java/blob/dce06be5477948f788d76a2a307f9225b89a82c4/sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java#L620

Upon investigating the cause, we found that the list of nodes in the dApp's transaction differs from the list of nodes in the Hedera Java SDK Client that our wallet is using, which leads to the error.

> List of nodes in the dApp's transaction: 
> [0.0.22, 0.0.16, 0.0.17, 0.0.28, 0.0.4, 0.0.5, 0.0.27, 0.0.14, 0.0.23, 0.0.11, 0.0.6, 0.0.19, 0.0.7, 0.0.10, 0.0.12, 0.0.31, 0.0.13, 0.0.30, 0.0.26, 0.0.8, 0.0.20, 0.0.18, 0.0.3, 0.0.25, 0.0.24, 0.0.21, 0.0.15, 0.0.29, 0.0.9]
> 
> List of nodes in the Hedera Java SDK Client:
> [0.0.5, 0.0.28, 0.0.3, 0.0.27, 0.0.19, 0.0.24, 0.0.15, 0.0.17, 0.0.32, 0.0.34, 0.0.18, 0.0.16, 0.0.22, 0.0.21, 0.0.4, 0.0.8, 0.0.14, 0.0.12, 0.0.23, 0.0.30, 0.0.29, 0.0.10, 0.0.20, 0.0.11, 0.0.9, 0.0.13, 0.0.25, 0.0.7, 0.0.33, 0.0.6, 0.0.31]

The node 0.0.26 is not present in the Client. 
I have heard that this node has been officially excluded from the node list. So the Client seems fine but some dApp may not recognize it.

I suggest enhancing the SDK code so that the transaction execution logic can continue. 
Is there a reason to throw an error and halt the transaction execution just because some nodes are missing on the Client? Even though the transaction can be executed with other nodes.. 
Rather than causing an exception, it would be better to at least log the error and allow the transaction execution logic to continue.
This would provide flexibility in case specific nodes are excluded from the list in the future.

**Comment by starlove7** [comment]
By default, I think the dApp should support the latest node list.
However, the java SDK and js SDK have different implementations of the execute() function.
In this case, the js SDK does not throw an error.
It would be nice if the java SDK could be modified so that the same logic can be configured.
(The latest version of java SDK has the same issue.)

**Comment by 0xivanov** [comment]
Hello, thanks for the detailed explanatation.

This issue is most likely happening because the address book (list of nodes) of the Java SDK is not up to date. The issue **might** get fixed if you use the latest version of the SDK. I will check if the latest version of the Java SDK has node 26 and if it does - it's not really a bug on our side.

Anyways, if you want to do a hotfix, you could try to set your custom network of nodes for your client. Example: 
```java
            Map<String, AccountId> network = new HashMap<>();
            network.put("1.testnet.hedera.com:50211", new AccountId(4));
            network.put("2.testnet.hedera.com:50211", new AccountId(5));
            var client = Client.forNetwork(network);

```

**Comment by starlove7** [comment]
> Hello, thanks for the detailed explanatation.
> 
> I guess you are calling `setNodeAccountIDs(<the dapp's nodes>)` on the transaction you are executing, but when you are creating the SDK Client, you are having different `network` set up. These 2 should be matching. I recommend using this snippet to create the Client:
> 
> ```java
>         Map<String, AccountId> network = new HashMap<>();
>         // fill the nodes from the dapp
>          var client = Client.forNetwork(network);
> ```
> 
> Regarding this :
> 
> > However, the java SDK and js SDK have different implementations of the execute() function.
> > In this case, the js SDK does not throw an error.
> 
> Depends on what version of the JS SDK you are referring to. Different SDK versions have different address books and some nodes might be missing or new ones could be added.

I agree that the NodeAccountIds should match.
As I understand it, HederaSDK is getting an up-to-date list of NodeAccountIds from the mirror node.
If the dApp uses an older version of the SDK, or uses randomized NodeAccountIDs (like in the case of SaucerSwap in this issue), it will most likely cause issues.
Nevertheless, the behavior should be consistent on the client regardless of platform (AOS, iOS, JS, etc.).

**Comment by Loganistic** [comment]
@0xivanov Thank you for the checking!

Even if there is a way to set up the SDK Client's network, this is unlikely to be resolved.
We can include 0.0.26 node that exist only in transactions to the client's network, but I don't think we should include 0.0.26 node in the client's network because it is invalid nodes.
