### ISSUE TITLE
Rename hedera to hiero in gradle files

### ISSUE THREAD

**Issue by 0xivanov** [hashgraph/hedera-sdk-java#2054]
### Problem

-

### Solution

-

**Comment by 0xivanov** [comment]
@jjohannes Would you be able to take a look at this? I've done the renaming for the `.java` files [here](https://github.com/hashgraph/hedera-sdk-java/pull/2045). but I am not very familiar with the gradle structure in the sdk.

**Comment by jjohannes** [comment]
@0xivanov with the change of the Java packages and Module Name, we should also change the `group` the SDK is published under (IMO). This would be here: https://github.com/hashgraph/hedera-sdk-java/blob/main/gradle/plugins/src/main/kotlin/com.hedera.gradle.base.gradle.kts#L21
I suggest to change that in your PR as well.


The Gradle configuration files (convention plugins) also use the _hedera_ in their IDs, but that is only internal to our build and has no influence on the published artifacts. I will change these to `org.hiero.*` as part of #2033.

**Comment by 0xivanov** [comment]
Sounds good!

**Comment by 0xivanov** [comment]
Hi @jjohannes , has there been any progress on this issue?

**Comment by jjohannes** [comment]
Everything is prepared, but we are still waiting to get all credentials/singing keys for the new Hiero org to be able to publish the first version of https://github.com/hiero-ledger/hiero-gradle-conventions

I expect this to happen any day now.

As soon as it is done, I will update https://github.com/hashgraph/hedera-sdk-java/pull/2033 in a way that it also resolves this issue.

**Comment by jjohannes** [comment]
Done by #2033 

The group for publishing (Maven Coordinates) is also defined in a Gradle file – `settings.gradle.kts` – but should be changed together with the packages as it is part of the "user facing API". See https://github.com/hashgraph/hedera-sdk-java/pull/2141#issuecomment-2544045813
