### ISSUE TITLE
(Low priority) - Solidity address calculations

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#206]
When calculating a solidity address, the first four bytes are not the shard, and should default to `0000`.

Not an issue until we have shards in place, but the encoder from shard.realm.number to solidity should not use shard, likewise, the decoder from solidity should not assume that the first four bytes are the shard.

Need to think about the implications of the SDK having to be aware of the shard it's interacting with in order to set the shard number when decoding, but that's not an immediate priority.

**Comment by mehcode** [comment]
For the immediate this should probably just be deprecated from the SDK or should the "toSolidityAddress" conversion take the shard number?

**Comment by mehcode** [comment]
* `toSolidityAddress` should not encode shard
 * `fromSolidityAddress` should take shard as a parameter

**Comment by donaldthibeau** [comment]
Ready for development

**Comment by lbaird** [comment]
Hi. I’m not clear on where this is now. When we have shards, we will definitely want those first 32 bits in the Solidity address to represent the shard number.

But shard zero will be the only shard for at least the next year. So it’s fine if the SDK hard codes those bits to zeros. We can fix that later.

We just need to remember that someday, we will need to put the shard in those bits.


________________________________

**Comment by mehcode** [comment]
It seems like what we have now is correct. When shards exist in the future we can revisit during that time.
