### ISSUE TITLE
Review TCK test specifications

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-java#2080]
Review TCK test specifications for:

- `TokenAssociateTransaction`
- `TokenDissociateTransaction`
- `TokenPauseTransaction`
- `TokenUnpauseTransaction`
- `TokenGrantKycTransaction`
- `TokenRevokeKycTransaction`
- `TokenMintTransaction`
- `TokenBurnTransaction`
- `TokenFreezeTransaction`
- `TokenUnfreezeTransaction`

**Comment by SimiHunjan** [comment]
open discussions on token mint and token burn otherwise all have been reviewed
