### ISSUE TITLE
Send transaction has crashed in Android

### ISSUE THREAD

**Issue by starlove7** [hashgraph/hedera-sdk-java#2095]
### Description

The app crashes when performing a transaction after v2.35.1 on Android.
The problematic part is the BaseNode.getUserAgent function as shown in the screenshot.
The problem seems to be caused by the getModule() Method modified in commit 9012a3d17646e4fae5e5a835ef5ed639cfb58a31, which is not supported by the Android API.
It looks like that part needs to be rolled back to run on Android.

### Steps to reproduce

1. Run Android Example
2. Crypto Transfer Tab -> Send

### Additional context

![image](https://github.com/user-attachments/assets/f1fab81e-f62a-4550-bee0-c4c1a04e8e1d)

### Hedera network

testnet

### Version

v2.44

### Operating system

None

**Comment by 0xivanov** [comment]
Hello, what version of the android API are you using?

**Comment by starlove7** [comment]
I'm using Android API 33 and 34.
