### ISSUE TITLE
Just a Dev related documentation - busted link 

### ISSUE THREAD

**Issue by johnda98** [hashgraph/hedera-sdk-java#216]
https://docs.hedera.com/reference/cryptocurrency-transactions

404.

**Comment by SimiHunjan** [comment]
@johnda98 thanks! I think we resolved this with issue #217 ?

**Comment by johnda98** [comment]
similar.. cant dig through now.. both links were in the docs for some Dev
getting started, one of my Dev guys noticed it.

wished to ensure the HH site was all smooth and QAQCd :-)


*John D Allen.*


*Leveridge Systems INC.   *



*T +1 417 414 4963 CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


This email is sent on behalf of Leveridge Systems INC. Reg.Ein 86-0905636.

The information contained in this email and any attached files is
confidential and intended solely for the addressee(s). The email may be
legally privileged or prohibited from disclosure and unauthorized use. If
you are not the named addressee you may not use, copy, or disclose this
information to any other person. If you received this message in error
please notify the sender immediately and delete it from your system.

**Comment by abonander** [comment]
@johnda98 this is not the proper issue tracker for problems with the documentation site. If you're on the [Hedera Discord channel](https://discordapp.com/invite/FFb9YFX) please report problems there.
