### ISSUE TITLE
Prob updating.. another busted link   https://docs.hedera.com/reference/smart-contracts

### ISSUE THREAD

**Issue by johnda98** [hashgraph/hedera-sdk-java#217]
API docs ..  https://docs.hedera.com/reference/smart-contracts

404..

**Comment by gakz** [comment]
@johnda98 thanks for flagging; where are you coming across these links? Want to make sure we fix the root.

**Comment by johnda98** [comment]
scroll to bottom of page
https://docs.hedera.com/docs/getting-started-cryptocurrency

see last link.. it goes to the 404.. looks circular.

cheers,
John.

I am Greg Scullard's best buddy fellow Brit  ;)   johnda98 on discord java
sdk and dapponboarding channels



*John D Allen.*


*Leveridge Systems INC.   *



*T +1 417 414 4963 CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


This email is sent on behalf of Leveridge Systems INC. Reg.Ein 86-0905636.

The information contained in this email and any attached files is
confidential and intended solely for the addressee(s). The email may be
legally privileged or prohibited from disclosure and unauthorized use. If
you are not the named addressee you may not use, copy, or disclose this
information to any other person. If you received this message in error
please notify the sender immediately and delete it from your system.
