### ISSUE TITLE
Minimum duration / auto renew default needs to be set to 7890000 seconds

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#223]
Mainnet and testnet implement this minimum duration (which is also maximum duration) for now.

All accounts, files and contracts have to have that duration set exactly.

**Comment by abonander** [comment]
This likely affects the JS SDK as well.

**Comment by abonander** [comment]
@mehcode already updated it in the JS SDK so it's just here that needs to be updated: https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/account/AccountCreateTransaction.java#L25

**Comment by jjones151** [comment]
Thanks

**Comment by jjones151** [comment]
Call

**Comment by jjones151** [comment]
FaceFactory nothing

**Comment by jjones151** [comment]
Nothing is bad so long as it is good to try in position of country and power

**Comment by abonander** [comment]
@jjones151 it looks like you're replying to the wrong thread from your email.

**Comment by jjones151** [comment]
To me a friend should answer
