### ISSUE TITLE
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. 

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#248]
Hi,

Since upgrading to v0.8.0 (from v 0.6.1), I have been getting the following error for any call to hedera (contract or otherwise)

```
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
```

I have seen that several commits back in the java sdk, the grpc-netty thing was removed. It seems like this error is related to this. 

The current example code also fail with the same error.

What dependency should I now add to my maven file? (can you update the example code too). Alternatively, can you add the grpc-netty dependency back?

Cheers!

**Comment by abonander** [comment]
@rahul-ki `grpc-netty` was removed to allow consumers of the SDK to choose their own gRPC transport; this was necessary to support Android properly (which wants to use `grpc-okhttp` instead). Instead, add the dependency to your project as shown here: https://github.com/hashgraph/hedera-sdk-java#maven

**Comment by mehcode** [comment]
@rahul-ki In the future, check the release notes. We'll try and identify that kind of stuff here: https://github.com/hashgraph/hedera-sdk-java/releases

**Comment by rahul-ki** [comment]
Nevermind haha! I don't know how I managed to skip the readme! Sorry about this
