### ISSUE TITLE
Java SDK for HCS

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-sdk-java#254]
Ken to talk to Mike and ensure that we have convergence on Java SDK for HCS

**Comment by mehcode** [comment]
Prototype is being worked on here https://github.com/hashgraph/hedera-sdk-java/pull/273

**Comment by mehcode** [comment]
To update, the prototype is working and most things are implemented. It just needs a bit of clean-up and @abonander is working on that today.

**Comment by mehcode** [comment]
This exists on maven under `0.9.0-hcs-1` and under the https://github.com/hashgraph/hedera-sdk-java/tree/hcs branch
