### ISSUE TITLE
Client should accept a signer callback like with the Javascript SDK

### ISSUE THREAD

**Issue by abonander** [hashgraph/hedera-sdk-java#260]
Taking a signer callback in lieu of a private key is implemented in the JS SDK to support hardware wallets: https://github.com/hashgraph/hedera-sdk-js/blob/master/src/BaseClient.ts#L21-L30

If we want full parity between the SDKs then this should be implemented here. I'm thinking something along the lines of this:

```java
// to be implemented by `Ed25519Signature`
public interface Signature {
    SignaturePair toProto();
}

// to be implemented by `Ed25519PrivateKey` or passed as a lambda
@FunctionalInterface
public interface Signer {
    /**
    * Sign (after optionally validating) the given message (which is an encoded {@link Transaction}).
    * 
    * This method is allowed to block, e.g. while waiting for user confirmation.
    */
    Signature sign(byte[] message);
}
```

**Comment by mehcode** [comment]
This would be used in `Transaction#signWith`

**Comment by donaldthibeau** [comment]
Ready for development
