### ISSUE TITLE
Should QueryBuilder#setMaxQueryPayment be QueryBuilder#setMaxPayment instead ?

### ISSUE THREAD

**Issue by mehcode** [hashgraph/hedera-sdk-java#283]

**Comment by abonander** [comment]
I picked `setMaxQueryPayment` as a parallel to `setMaxTransactionFee`; really, `TransactionBuilder.setMaxTransactionFee` could also just be `setMaxFee` but then they wouldn't match the equivalent methods on `Client` which seemed more important.

**Comment by mehcode** [comment]
https://github.com/hashgraph/hedera-sdk-java/blob/3ab0e25c89a2657fb039079148a7c1073420d176/src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java#L143-L155

I think my issue here is that we have both `setPaymentAmount` _and_ `setMaxQueryPayment`

**Comment by mehcode** [comment]
Decided to rename `setPaymentAmount` to `setQueryPayment`
