### ISSUE TITLE
HCS: subscribeTopic() fails; wrong package name for mirror's ConsensusService

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-sdk-java#289]
The package name for the mirror's ConsensusService needs to be `com.hedera.mirror.api.proto` not `mirror`.

The mirror node (and hedera-mirror-protobuf package) use this package name and if they don't match the requested service won't be found when the subscribeTopic call is made.

**Comment by abonander** [comment]
fixed in #291
