### ISSUE TITLE
MirrorConsensusTopicResponse doesn't have a public constructor

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#292]
I need to be able to reconstruct a `ConsensusMessage`, suggest enabling public constructor for this class.

**Comment by calvinchengx** [comment]
Same here. I need to be able to reconstruct a `ConsensusMessage`.

**Comment by abonander** [comment]
`ConsensusMessage` is deprecated but `MirrorConsensusTopicResponse` could use the same treatment.

**Comment by donaldthibeau** [comment]
Fixed in v2
