### ISSUE TITLE
Implement toBytes/fromBytes for various POJOs

### ISSUE THREAD

**Issue by abonander** [hashgraph/hedera-sdk-java#296]
Serialize the following types to/from binary using their Protobuf equivalents.

### ID types
- [x] `AccountId`
- [x] `ConsensusTopicId`
- [x] `ContractId`
- [x] `FileId`
- [x] `TransactionId`

### "Info" Types
- [x] `AccountInfo`
- [x] `ConsensusTopicInfo`
- [x] `ContractInfo`
- [x] `FileInfo`

### Misc
- [ ] `ConsensusMessage` (on `experiment/hcs`)
- [x] `TransactionReceipt`
- [x] `TransactionRecord`

**Comment by Sheng-Long** [comment]
added to develop branch
