### ISSUE TITLE
[Discussion] Removed methods from ContractFunctionParams/ContractFunctionResult

### ISSUE THREAD

**Issue by abonander** [hashgraph/hedera-sdk-java#298]
Less-used methods on `CallParams` and `FunctionResult` have been removed in the process of their being moved to the `contract` package and renamed to `ContractFunctionParams` and `ContractFunctionResult`, respectively. If there is a method missing that you require, this is the place to let us know.

**Comment by JaimeSilver** [comment]
Missing Uint8 and Bytes32 in the new ContractFunctionParams. Why not leave the option to provide the length of the variable as it was before (bytes, Uint)?
Proposal: Keep the common ones, but don't restrict the type.

**Comment by mehcode** [comment]
Support for `uint8`, `int8`, and `bytes32` have been added and are released as `v1.0.0`

---

If there is sufficient demand, I'm okay with adding say, `.addInt` with a width parameter. 

The reasoning behind the new APIs is they mirror solidity exactly so if you see a `bytes32` type in your contract you know to use `.addBytes32` in the Java code.

**Comment by JaimeSilver** [comment]
Hello,

Below is a reference to map your design: 

There are values required uint8, uint16, uint24 ... uint256. (Intervals of 8)

Same for bytes bytes1, bytes2, ... bytes32.

See below: 

https://solidity.readthedocs.io/en/v0.4.21/types.html

**Comment by mehcode** [comment]
After discussion, we've decided to provide a core set of types and then wait for users to request additional types that they need. Note that the encoding and decoding provided by the SDK is a *helper* and not intended to provide support for the entire language. For Java, I believe https://github.com/ethereum/ethereumj provides support for **all** types in the language.

This is actually a great place for the community to contribute. We will accept PRs that **make** well-tested additions to the API. 

For what you suggest there I would say it should look like `.addIntN`, `addUintN`, and `addBytesN`.
