### ISSUE TITLE
Be able to send tinyBars on a smart contract constructor

### ISSUE THREAD

**Issue by bchevallereau** [hashgraph/hedera-sdk-java#311]
There is a method `setAmount` on `ContractExecuteTransaction` to be used on "payable" solidity functions.
But I didn't found such method on `ContractCreateTransaction`.
Here is an example of smart contract that contains a constructor marked as "payable":
https://solidity.readthedocs.io/en/v0.5.3/solidity-by-example.html#safe-remote-purchase

**Comment by mehcode** [comment]
You're looking for https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/contract/ContractCreateTransaction.java#L80

**Comment by bchevallereau** [comment]
Awesome, thanks a lot @mehcode !
