### ISSUE TITLE
Incorrect cost returned for a FileInfoQuery

### ISSUE THREAD

**Issue by mehcode** [hashgraph/hedera-sdk-java#320]
See discussion in #317 

---

Try adding a factor of 1.1 ? Seems to be the magic number for files.

**Comment by abonander** [comment]
@mehcode the specific bug in the network is that `COST_ANSWER` for a **deleted** file returns a cost of 0; if you set a payment of 25 tinybar then it throws with `FILE_DELETED`. It is otherwise correct for live files.
