### ISSUE TITLE
AccountDeleteTransaction: the account ID in the transaction ID must be the account being deleted

### ISSUE THREAD

**Issue by abonander** [hashgraph/hedera-sdk-java#322]
Otherwise you get back `RECEIPT_NOT_FOUND` for `getReceipt()`.

**Comment by mehcode** [comment]
This sounds like this could be a network issue @gregscullard ?

**Comment by abonander** [comment]
We can fix this on our end by generating a transaction ID if one has not been set in `setDeleteAccountId`.

**Comment by mike-burrage-hedera** [comment]
Definitely some kind of timing issue. In the DeleteAccount example if you pause between execute and getReceipt on AccountDeleteTransaction it works.

**Comment by abonander** [comment]
Which is very strange because we're using `getReceipt()` on the delete transaction to wait for consensus.

**Comment by mehcode** [comment]
@abonander Mike has a point. We _should_ be retrying on `RECEIPT_NOT_FOUND`. Looking back, I would have sworn we were at some point.

**Comment by abonander** [comment]
Hmm, if `RECEIPT_NOT_FOUND` is returned between the transaction reaching consensus and the receipt being generated, then we should definitely be retrying on it.
