### ISSUE TITLE
Update HCS code for final version of HCS protobuf

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-sdk-java#323]
ConsensusClient.getMessages/getMessagesUntil and ConsensusMessageSubmitTransaction.setTopicID() use *topic* as param name, where other functions call it *topicId*. Please use the same param name for all references to this topicId.

@SimiHunjan can update documentation when these changes are in.

**Comment by mehcode** [comment]
@mike-burrage-hedera This was all done a couple weeks ago actually. We picked up the HCS protobuf changes from hedera-protobuf then. Just reviewed and looks good to me.

> ConsensusClient.getMessages/getMessagesUntil and ConsensusMessageSubmitTransaction.setTopicID() use topic as param name, where other functions call it topicId. 

That does need fixing. Good catch. @abonander please, when you get a moment today.

**Comment by mike-burrage-hedera** [comment]
This was fixed in an hcs related checkin.
