### ISSUE TITLE
IllegalStateException "Unchecked Key Case" in getInfo() calls on entities having threshold/keylist

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-sdk-java#333]
Specifically I was testing ConsensusTopicInfoQuery() on the experiment/hcs branch for a topic with a threshold key and this exception was thrown upon execute()ing the query.

Likely affects info queries on file/contract/crypto where the entity has non-trivial keys (threshold or keylist).

I have a fix as part of updates I'm doing for #332 , just need to add some unit test cases and I'll update that PR.

**Comment by mehcode** [comment]
Thanks for the fix
