### ISSUE TITLE
HCS message fragmentation/reassembly

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-sdk-java#344]
Provide an interface that allows for message fragmentation and reassembly to submit and receive messages larger than ~6kB over HCS

**Comment by mehcode** [comment]
This is pretty trivial for at an application level to handle in a domain specific fashion. In the context of a specific domain there may even be something available for splitting packets.

---

Note that we would be (silently) executing N transactions on behest of the user. How does that look? Does the client `maxTransactionFee` get split into N pieces so we don't go over? 

---

What does generic "message fragmentation/reassembly" look like? Are we prefixing with a UUID and a "x of N" header type thing?

---

I think something like this would be better served in a simple example showcasing fragmentation/reassembly at a domain level. Additionally, and probably far more useful, is showcasing compression. It would be pretty trivial from the application side to pipe input and output through something like Zstd.

**Comment by mike-burrage-hedera** [comment]
The SDK doesn't expose the size of the overhead for a transaction (which depends on the signature map which depends on the operator and submit keys, among other things).

To make best use of the 6144 byte transaction size limit in terms of fragmentation, this can be handled by the SDK (which does have access to that info).

A simple header is one option (magic number, message ID, fragment number). message ID can be the transaction ID of the first fragment.
The scaffolding currently uses another option where each fragment is a protobuf with several optional fields.

maxTransactionFee would still apply to each transaction sent, but large messages would require multiple transactions.

Compression doesn't change the need for fragmentation/reassembly.

The goal would be to provide a commonly supported standard option/interface for sending and receiving messages larger than ~6k.

**Comment by mehcode** [comment]
@mike-burrage-hedera Do we still want this in the SDK given https://github.com/hashgraph/hedera-hcs-sxc-java ?

**Comment by gregscullard** [comment]
Having chunking/reassembly in the SDK would be useful, it would potentially make sending/receiving messages simpler, however, this needs to be an optional feature.

Reason is that for proof (transactions, records and state proofs), individual chunks that are sent as transactions potentially need to be known by the sender/receiver(s). hcs-sxc chunks and reassembles while logging all the transactions and chunks for that very purpose.

This may not be desired by all, so optionally allowing the SDK to do it out of the box could still be beneficial to some.

**Comment by mehcode** [comment]
Tracked in #401 now
