### ISSUE TITLE
ConsensusTopicId.java missing methods

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#349]
I see in the JS SDK you can call `fromSolidityAddress` and `toSolidityAddress` for consensus topic id: https://github.com/hashgraph/hedera-sdk-js/blob/master/src/consensus/ConsensusTopicId.ts

I don't see those options available for Java SDK: https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/consensus/ConsensusTopicId.java

**Comment by abonander** [comment]
It doesn't make much sense to convert topic IDs to Solidity addresses since that's purely for interacting with smart contracts, and those can't access HCS functionality.

Files have the same methods but those also don't make much sense as the Solidity VM has no concept of files.
