### ISSUE TITLE
Can't delete contracts with balance.

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#353]
Hedera Exception `OBTAINER_REQUIRED` says that when deleting smart contract that has crypto balance either transfer account or transfer smart contract is required.
However, there is no obvious builder method to add a transfer account or smart contract:

![image](https://user-images.githubusercontent.com/35169918/74050518-24571980-49ce-11ea-9e3e-f0dd814da69a.png)

**Comment by mehcode** [comment]
Added `setTransferAccountId` and `setTransferContractId` to `ContractDeleteTransaction`. This should be out some time today as v1.1.3
