### ISSUE TITLE
Include instructions for running the examples in a README.md in the examples folder

### ISSUE THREAD

**Issue by craigdrabiktxmq** [hashgraph/hedera-sdk-java#354]
It would be easier for people to get up and running with the SDK and the examples if the documentation at https://docs.hedera.com/javasdk/getting-started was included right in the github repository.  This is standard practice for most NodeJS libraries that I'm familiar with.

**Comment by mehcode** [comment]
Done in v2 - https://github.com/hashgraph/hedera-sdk-java/tree/develop#example
