### ISSUE TITLE
Exception in thread "main" com.hedera.hashgraph.sdk.HederaStatusException: TRANSACTION_OVERSIZE

### ISSUE THREAD

**Issue by Velmuruganms12** [hashgraph/hedera-sdk-java#362]
while creating SmartContract getting following error.

Exception in thread "main" com.hedera.hashgraph.sdk.HederaStatusException: TRANSACTION_OVERSIZE

Code : Using existing CreateStatefulContract code, changed only the solidity and json file.

Will provide solidity code based on request.

    try (InputStream jsonStream = cl.getResourceAsStream("xennies.json")) {
            if (jsonStream == null) {
                throw new RuntimeException("failed to get xennies.json");
            }
            jsonObject = gson.fromJson(new InputStreamReader(jsonStream), JsonObject.class);
        }

        String byteCodeHex = jsonObject.getAsJsonPrimitive("object")
            .getAsString();
        byte[] byteCode = byteCodeHex.getBytes();

        // `Client.forMainnet()` is provided for connecting to Hedera mainnet
        Client client = Client.forTestnet();

        // Defaults the operator account ID and key such that all generated transactions will be paid for
        // by this account and be signed by this key
        client.setOperator(OPERATOR_ID, OPERATOR_KEY);

        // default max fee for all transactions executed by this client
        client.setMaxTransactionFee(new Hbar(10000));
        client.setMaxQueryPayment(new Hbar(1000));

        // create the contract's bytecode file
        TransactionId fileTxId = new FileCreateTransaction()
            // Use the same key as the operator to "own" this file
            .addKey(OPERATOR_KEY.publicKey)
            .setContents(byteCode)
            .execute(client);

        TransactionReceipt fileReceipt = fileTxId.getReceipt(client);
        FileId newFileId = fileReceipt.getFileId();

        System.out.println("contract bytecode file: " + newFileId);

        TransactionId contractTxId = new ContractCreateTransaction()
            .setBytecodeFileId(newFileId)
            .setGas(100_000_000)
            .setConstructorParams(
                new ContractFunctionParams()
                    .addString("hello from hedera!"))
            .execute(client);

**Comment by mehcode** [comment]
Files have a max size that may be transmitted over a single transaction (~5 KiB I believe). If you need to upload a larger file/contract you must create the file first then do N FileAppend transactions to upload the file in chunks.

**Comment by Velmuruganms12** [comment]
Can i get example for this one or some reference code how to use N FileAppend transaction to upload the file in chunks.

**Comment by mehcode** [comment]
I don't have a great example in Java handy. That's definitely something we should add as an example. Upload a file that's say ~1 MiB. 

However we do have a fairly decent JavaScript example here:

https://github.com/hashgraph/MyHbarWallet/blob/master/src/views/InterfaceUploadFile.vue#L180

**Comment by rahul-ki** [comment]
@Velmuruganms12  here is a java example for N file append:

```
       int final FILE_PART_SIZE = 4000
        String byteCodeHex = jsonObject.getAsJsonPrimitive(contractName).getAsString();
        byte[] byteCode = byteCodeHex.getBytes();

        int numParts = byteCode.length / FILE_PART_SIZE;
        int remainder = byteCode.length % FILE_PART_SIZE;
        
        //add in 4k chunks
        byte[] firstPartBytes;
        if (byteCode.length <= FILE_PART_SIZE) {
            firstPartBytes = byteCode;
            remainder = 0;
        } else {
            firstPartBytes = TokenUtils.copyBytes(0, FILE_PART_SIZE, byteCode);
        }

        // create the contract's bytecode file
        TransactionId fileTxId = new FileCreateTransaction().setExpirationTime(
                Instant.now().plus(Duration.ofMillis(7890000000L)))
                // Use the same key as the operator to "own" this file
                .addKey(operatorKey.publicKey)
                .setContents(firstPartBytes)
                .setMaxTransactionFee(new Hbar(10))
                .execute(client);

        TransactionReceipt fileReceipt = fileTxId.getReceipt(client);
        FileId newFileId = fileReceipt.getFileId();

        logger.info("contract bytecode file: " + newFileId);

        //add remaining chunks
        // append the rest of the parts
        for (int i = 1; i < numParts; i++) {
            byte[] partBytes = TokenUtils.copyBytes(i * FILE_PART_SIZE, FILE_PART_SIZE, byteCode);
            new FileAppendTransaction().setFileId(newFileId)
                    .setMaxTransactionFee(new Hbar(5))
                    .setContents(partBytes).execute(client);
        }
        //appending remaining data
        if (remainder > 0) {
            byte[] partBytes = TokenUtils.copyBytes(numParts * FILE_PART_SIZE, remainder, byteCode);
            new FileAppendTransaction().setFileId(newFileId)
                    .setMaxTransactionFee(new Hbar(5))
                    .setContents(partBytes).execute(client);
        }

        return newFileId;
```

**Comment by Velmuruganms12** [comment]
> @Velmuruganms12 here is a java example for N file append:
> 
> ```
>        int final FILE_PART_SIZE = 4000
>         String byteCodeHex = jsonObject.getAsJsonPrimitive(contractName).getAsString();
>         byte[] byteCode = byteCodeHex.getBytes();
> 
>         int numParts = byteCode.length / FILE_PART_SIZE;
>         int remainder = byteCode.length % FILE_PART_SIZE;
>         
>         //add in 4k chunks
>         byte[] firstPartBytes;
>         if (byteCode.length <= FILE_PART_SIZE) {
>             firstPartBytes = byteCode;
>             remainder = 0;
>         } else {
>             firstPartBytes = TokenUtils.copyBytes(0, FILE_PART_SIZE, byteCode);
>         }
> 
>         // create the contract's bytecode file
>         TransactionId fileTxId = new FileCreateTransaction().setExpirationTime(
>                 Instant.now().plus(Duration.ofMillis(7890000000L)))
>                 // Use the same key as the operator to "own" this file
>                 .addKey(operatorKey.publicKey)
>                 .setContents(firstPartBytes)
>                 .setMaxTransactionFee(new Hbar(10))
>                 .execute(client);
> 
>         TransactionReceipt fileReceipt = fileTxId.getReceipt(client);
>         FileId newFileId = fileReceipt.getFileId();
> 
>         logger.info("contract bytecode file: " + newFileId);
> 
>         //add remaining chunks
>         // append the rest of the parts
>         for (int i = 1; i < numParts; i++) {
>             byte[] partBytes = TokenUtils.copyBytes(i * FILE_PART_SIZE, FILE_PART_SIZE, byteCode);
>             new FileAppendTransaction().setFileId(newFileId)
>                     .setMaxTransactionFee(new Hbar(5))
>                     .setContents(partBytes).execute(client);
>         }
>         //appending remaining data
>         if (remainder > 0) {
>             byte[] partBytes = TokenUtils.copyBytes(numParts * FILE_PART_SIZE, remainder, byteCode);
>             new FileAppendTransaction().setFileId(newFileId)
>                     .setMaxTransactionFee(new Hbar(5))
>                     .setContents(partBytes).execute(client);
>         }
> 
>         return newFileId;
> ```

where i can get this method TokenUtils.copyBytes. do i need import any other library or its custom Util class.

**Comment by rahul-ki** [comment]
```public static byte[] copyBytes(int start, int length, byte[] bytes) {
        byte[] rv = new byte[length];
        for (int i = 0; i < length; i++) {
            rv[i] = bytes[start + i];
        }
        return rv;
    }```
It is literally a method that copies a given number of bytes from one array into another

**Comment by Velmuruganms12** [comment]
I am able to proceed with that error.

But got another error now in below line. I have balance in my account

        TransactionId contractTxId = new ContractCreateTransaction()
            .setBytecodeFileId(newFileId)
            .setGas(100_000_000)
            .setConstructorParams(
                new ContractFunctionParams()
                    .addString("hello from hedera!"))
            .execute(client);

Exception in thread "main" com.hedera.hashgraph.sdk.HederaStatusException:
INSUFFICIENT_PAYER_BALANCE
at
com.hedera.hashgraph.sdk.HederaStatusException.throwIfExceptional(HederaStatusException.java:30)
at com.hedera.hashgraph.sdk.Transaction.mapResponse(Transaction.java:248)
at com.hedera.hashgraph.sdk.Transaction.mapResponse(Transaction.java:23)
at com.hedera.hashgraph.sdk.HederaCall.lambda$execute$0(HederaCall.java:55)
at com.hedera.hashgraph.sdk.Backoff.tryWhile(Backoff.java:37)

**Comment by rahul-ki** [comment]
Check that the client.setMaxTransactionFee is < your balance. Also that the typical fee is < your balance. You can always find out more about these exceptions [here](https://github.com/hashgraph/hedera-protobuf). Seach for your error in this repo.

Given this is not an issue with the sdk, can we please switch over to discord java-sdk channel? You will find that this has been asked multiple times.

**Comment by mehcode** [comment]
I'm going to say I'd prefer SDK discussion to happen in issues vs. in Discord as it's far more likely to be answered and show up in google results if we discuss it here.

---

With that said, your issue there is you're setting a huge amount of gas and you likely don't have a high enough balance to afford that gas limit. Just reduce the gas to something more reasonable like ~2000.

**Comment by donaldthibeau** [comment]
Closing out discussion.

**Comment by Intigate** [comment]
> I don't have a great example in Java handy. That's definitely something we should add as an example. Upload a file that's say ~1 MiB.
> 
> However we do have a fairly decent JavaScript example here:
> 
> https://github.com/hashgraph/MyHbarWallet/blob/master/src/views/InterfaceUploadFile.vue#L180

this link is not working. Is there any other reference ?

**Comment by Intigate** [comment]
https://github.com/hashgraph/MyHbarWallet/blob/master/src/views/InterfaceUploadFile.vue#L180
@mehcode this link is not working. Is there any other reference in JavaScript.
@rahul-kothari
