### ISSUE TITLE
Exception in thread "main" com.hedera.hashgraph.sdk.HederaStatusException: AUTORENEW_DURATION_NOT_IN_RANGE

### ISSUE THREAD

**Issue by Velmuruganms12** [hashgraph/hedera-sdk-java#363]
I was able to run the CreateStatefulContract with default solidity code smart contract created but when i ran CreateSimpleContract code i got below shown error.

Exception in thread "main" com.hedera.hashgraph.sdk.HederaStatusException: AUTORENEW_DURATION_NOT_IN_RANGE

I running it on my windows machine took the last code from git, added OPERATOR_ID & OPERATOR_KEY created for my testnet account. let me know if i am missing any configuration.

**Comment by rahul-ki** [comment]
@Velmuruganms12 
Try this auto duration range:
```.setAutoRenewPeriod(Duration.ofSeconds(8000000))```

in the sdk, the autorenewal duration is between:  6999999 to 8000001 seconds
Otherwise, the above-mentioned error is thrown

Also, not sure but the community usually asks questions in discord rather than here :)

**Comment by Velmuruganms12** [comment]
I am getting error while creating FileCreateTransaction itself as
highlighted below.


[image: image.png]

**Comment by rahul-ki** [comment]
Please try the exact amounts I have mentioned in my sample code in this issue for Contracts and for files refer to my comments on issue#362

**Comment by mehcode** [comment]
Please re-open if you're still having problems.
