### ISSUE TITLE
Testnet EVM requires lesser gas than remix?

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#364]
I have a smart contract that uses roughly 5,000,000 units of gas to deploy (on remix). And it throws an `out of gas` error when trying to only supply 300,000 units of gas (which is hedera's gas limit).

Yet, when I deploy this exact smart contract on hedera's testnet, it successfully deploys even when supplying only 300,000 tiny bars as gas.

Similarly, for `ContractExecuteTransaction`, the testnet works with gas that is a whole order of magnitude lesser than what remix uses. 

I am not sure why this is the case. But I can confirm multiple instances of this.

**Comment by johnda98** [comment]
Remix hits, obviously, the EVM and ropsten/ or the other test/mainnet for Ethereum and ITS gas price/terms as dictated by that protocol.. still PoW .. PoS though.

EVM is open specification right.. so Hedera's tweaks to it are unknown.. thus the ScVM as the Hedera solidity VM is called.. has its own pricing/terms in synergy for gossip-gossip/virt vote.

**Comment by johnda98** [comment]
Try it on mainnet HH with a suicide method.. wont cost you much to deploy! .. 4cents/ 100M x 300,000
(could be dyslexic math) .. maybe HH gas pricing is different.

**Comment by rahul-ki** [comment]
Thanks to Constantin, here is the actual reason why:

> the gas calculation in HH is different in some aspects from the canonical EVM .  MOST of the opcodes would consume the same amount of gas in HH but there are some differences :

- Basic transaction cost is not part of the gas , transaction fee is used instead.
- Storage related operations when you storing anything new on HH the gas would be calculated based on Bytes Per Hour coefficient  so number of gas units  needed to store 1 byte could be significantly less than  on Ethereum network ( depending on your contract expiration)
- Event emitting would also use a BPH coefficient  . Events are stored as part of transaction record  that have a known lifespan of 25 Hours.

> So if you estimating gas of  contractCall  that store data Remix estimate could be very different from the actual gas cost you would incur on HH network If you estimating a gas for contractCall that would do just computation  or would  change the value of existing storage it would be very close to Remix estimate.

**Comment by lbaird** [comment]
Does the gas per BPH price come from the transaction fee schedule? Or is it hard coded?

________________________________

**Comment by czemelman** [comment]
@lbaird  transaction service BPH coefficient is used to calculate new storage cost in tinycents
then service Gas coefficient is used to calculate the number of gas units

**Comment by lbaird** [comment]
Great. So we can control that price with the fee schedule. Perfect. Thanks!

________________________________

**Comment by johnda98** [comment]
> Thanks to Constantin, here is the actual reason why:
> 
> > the gas calculation in HH is different in some aspects from the canonical EVM .  MOST of the opcodes would consume the same amount of gas in HH but there are some differences :
> 
> * Basic transaction cost is not part of the gas , transaction fee is used instead.
> * Storage related operations when you storing anything new on HH the gas would be calculated based on Bytes Per Hour coefficient  so number of gas units  needed to store 1 byte could be significantly less than  on Ethereum network ( depending on your contract expiration)
> * Event emitting would also use a BPH coefficient  . Events are stored as part of transaction record  that have a known lifespan of 25 Hours.
> 
> > So if you estimating gas of  contractCall  that store data Remix estimate could be very different from the actual gas cost you would incur on HH network If you estimating a gas for contractCall that would do just computation  or would  change the value of existing storage it would be very close to Remix estimate.

Exactly as I commented.. we do not yet know the differences to the VM spec in the HH scVM spec..  Greg S said that code will be open review soon.

**Comment by rahul-ki** [comment]
@czemelman looks like dragonglass understandably doesn't show ContractCallLocal, and given remix' gas values are way off the mark, how should one go about estimating the gas requirements for queries?

**Comment by czemelman** [comment]
@rahul-ki Since state modification is not allowed in contractCallLocal  Remix gas estimate would be very close to HH , you will need a little less gas than Remix would estimate. Let me also answer the question about gas and  hbar exchange rate.  Number of gas units needed would not be affected by exchange rate fluctuations what would be affected is the number of tinybars service would charge you for each gas unit spent. For new storage and events you might see a very little changes in number of gas units needed due to rounding errors.
