### ISSUE TITLE
TransactionId.getReceipt() not waiting for timeout

### ISSUE THREAD

**Issue by carlcherry** [hashgraph/hedera-sdk-java#374]
In version 1.1.3 of the SDK I am having trouble getting the receipt for new accounts: i.e.

Transactionid txId = AccountCreateTransaction()...

txId.execute(client);

txId.getReceipt(client, Duration.ofSeconds(5L));

Many times the getReceipt returns immediately and does not wait until the transaction succeeds.

**Comment by abonander** [comment]
I believe the real problem is that `getReceipt()` is returning on `OK` and not waiting until `SUCCESS`. I've been seeing this spuriously in my own testing.
