### ISSUE TITLE
getting a typemismatch .. used to be fine with FunctionResult... doesnt like contractCallQuery

### ISSUE THREAD

**Issue by johnda98** [hashgraph/hedera-sdk-java#375]
.. "String scontractid = "0.0.12345";

             ContractId existingcontractid = ContractId.fromString(scontractid);

                    ContractFunctionResult contractCallResult = new ContractCallQuery()
                     .setGas(30000)
                      .setContractId(existingcontractid)
                     .setFunction("getter_xyz")
                     .execute(client);
was fine with the old FunctionResult type .. new contractFunctionResult puking on me type mismatch
used to be simple to ContractId type from string..
callquery doesnt seem to like my ContractId type.. yet sdk prompt offers me.. and it was always there in the past..  0.1.8 ran fine as above but with FunctionResult

**Comment by johnda98** [comment]
ype mismatch: cannot convert from com.hedera.hashgraph.sdk.contract.ContractFunctionResult to 
 com.hedera.hashgraph.proto.ContractFunctionResult

**Comment by abonander** [comment]
Look at your imports and replace `com.hedera.hashgraph.proto.ContractFunctionResult` with `com.hedera.hashgraph.sdk.contract.ContractFunctionResult`. Your IDE probably auto-imported the wrong one.

**Comment by johnda98** [comment]
that bloody razor.. yes it did.
