### ISSUE TITLE
ClassNotFoundException: java.time.Duration on Android API level 24

### ISSUE THREAD

**Issue by mohit26chauhan** [hashgraph/hedera-sdk-java#377]
When I tried to use hedera-sdk in my app on Android device which have API level 24, it gave me below exception:
`Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Ljava/time/Duration;`

`Caused by java.lang.ClassNotFoundException
Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.zimbali.networks-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zimbali.networks-1/lib/arm, /system/lib, /vendor/lib]]`

Below is the SDK stack trace:
`dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass (ClassLoader.java:380)
java.lang.ClassLoader.loadClass (ClassLoader.java:312)
com.hedera.hashgraph.sdk.HederaCall.<clinit> (HederaCall.java:24)
com.hedera.hashgraph.sdk.HederaCall.<clinit> (HederaCall.java:24)`

While searching over the [Android documentation](https://developer.android.com/reference/java/time/Duration), I found that `java.time.Duration` was added in API level 26.
You guys mention the minSdkVersion to 21 in your android-example. 
Why am I experiencing this issue?
Have you ever faced this issue? If yes, how did you resolved it?

Dependencies included in Android project:
`com.hedera.hashgraph:sdk:1.1.3`
`io.grpc:grpc-okhttp:1.24.0`

**Comment by abonander** [comment]
Our Android example doesn't check much of the SDK right now; we probably should have caught this.

Does the error go away if you add the [ThreeTen-Backport](https://www.threeten.org/threetenbp/) as a dependency?

**Comment by mehcode** [comment]
Did this resolve your issue @mohit26chauhan

**Comment by mehcode** [comment]
This is being formally addressed in our incoming v2 ( very minimal breaking changes, mostly superficial ).

See: https://github.com/hashgraph/hedera-sdk-java/tree/develop#hedera-hashgraph-java-sdk

Including full tested support for Android API 19+
