### ISSUE TITLE
AccountBalanceQuery() cant differentiate between accounts and contracts. 

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#384]
I am checking for Hbar balance through a method that can check balance for both accounts and contracts. So I use this:
```
Hbar balance = new AccountBalanceQuery()
                .setAccountId(AccountId.fromString(id))
                .setContractId(ContractId.fromString(id)) //check balance of contracts!
                .execute(client);

        return balance.asTinybar();
```
However, even when I pass an account id (e.g. 0.0.143267), this throws an error saying `INVALID_CONTRACT_ID` but I can confirm that it is actually an account.

Interestingly, if I swap the two builder method calls, so call .setContractId first and then .setAccountId:
```
Hbar balance = new AccountBalanceQuery()                
                .setContractId(ContractId.fromString(id))
               .setAccountId(AccountId.fromString(id))
                .execute(client);

        return balance.asTinybar();
```

now, this works for account ids but not contract ids.

**Comment by cacampbell** [comment]
really makes you think

**Comment by cacampbell** [comment]
Hi @rahul-ki, what you have documented above is unsupported behavior. As you may be able to tell from the above behavior, whichever entity you set last will determine the type. 

Please use one entity type or the other when executing queries!

**Comment by rahul-ki** [comment]
@cacampbell this is for an API exposed to the public so they can input in anything (account or contract), so I have no real control over

**Comment by mehcode** [comment]
It's not possible for the SDK to tell the difference between an account or a contract ID. You could try doing one followed by the other?

**Comment by donaldthibeau** [comment]
Will not implement. 

HAPI cannot differentiate between entity types.
