### ISSUE TITLE
HederaStatusException thrown with Status.Ok

### ISSUE THREAD

**Issue by carlcherry** [hashgraph/hedera-sdk-java#387]
There are times when attempting to get a transaction receipt an HederStatusException is thrown but the status is Ok.  At other times you get back a receipt with a status of Ok.  Seems like Ok should not be an exceptional case.

**Comment by mehcode** [comment]
What version of the SDK are you using?

**Comment by carlcherry** [comment]
hedera-protobuf-java-api 0.3.4
sdk 1.1.4

**Comment by donaldthibeau** [comment]
@carlcherry is this still occuring?

**Comment by mehcode** [comment]
`Ok` does not mean that it's okay. That is an error code that means "receipt not yet available". What's likely happening is the timeout is elapsing and we're returning the "last" error instead. This is fixed in v2.
