### ISSUE TITLE
[com.hedera.hashgraph.proto.Duration] Issue after importing SDK project in eclipse

### ISSUE THREAD

**Issue by subodh07** [hashgraph/hedera-sdk-java#390]
![image](https://user-images.githubusercontent.com/51649863/80331686-602fab80-8866-11ea-80a4-adf83f33512f.png)

Proto is missing package

**Comment by subodh07** [comment]
![image](https://user-images.githubusercontent.com/51649863/80331949-1c897180-8867-11ea-897e-d3543eaf21ea.png)

**Comment by donaldthibeau** [comment]
Please use from maven central or build with maven locally.

https://github.com/hashgraph/hedera-sdk-java#maven
