### ISSUE TITLE
Client doesn't retry if a node is down

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#394]
Hi,
On mainnet 2 nodes were down (last time I checked). The client randomly happened to send a transaction one of those 2 nodes and the transaction failed with `io.grpc.StatusUnavailable`

It seems like the client doesn't retry sending it to other nodes. 

This should ideally be a feature within the SDK.

**Comment by mehcode** [comment]
Check out https://github.com/hashgraph/hedera-sdk-java/tree/develop

---

Multi-node retry is a very hard problem that required a rewrite of a large % of the SDK. That work will be available as `v2.x` and is currently in `develop`.

**Comment by rahul-ki** [comment]
Cool. That makes sense.
Probably #395 would make things work for now.
