### ISSUE TITLE
Do we need a api.status.hedera.com?

### ISSUE THREAD

**Issue by rahul-kothari** [hashgraph/hedera-sdk-java#395]
In accordance with #394 , for production environment, it would be helpful if there was an API that would tell you which nodes are working.
Otherwise `Client.forMainnet()` may send a transaction to a node that is down.
Similarly updating the `.env` with nodes that are working is manual and there is no "subscription" system to find out when a node is down. 

In Tune.fm we will have several hundred transactions happening and it is quite frustrating that some of them fail because some node is down and we have no way of knowing that programatically

**Comment by lbaird** [comment]
To be more up to date, and to deal with potential misbehavior by nodes, the client should maintain a list of which nodes it has recently used that either it couldn’t connect to, or that it could connect to but the node didn’t submit the transaction within a few seconds. The client should usually send a transaction to a random node that isn’t on that list. And only occasionally try one on that list, to see if it has improved.

________________________________

**Comment by rahul-ki** [comment]
@lbaird that would be ideal. Declutters the `.env` and harnesses the true power of `Client.forMainnet()`

**Comment by mehcode** [comment]
The client currently can't reasonably retry submission if that submissions is to a different node than it started with.

In `develop`, we are nearing completion of a `2.0` of the SDK that does have that ability. It's 2.0 for several reasons (including multi-node retry) though the breaking changes should be very light externally.

**Comment by rahul-ki** [comment]
Yes but having an api.status.hedera means we don't need a retry. We also send the transaction to the right node (the one that is not down)

**Comment by mehcode** [comment]
I don't think something like that is possible while still maintaining the decentralized property.

**Comment by rahul-ki** [comment]
How so? The fact that we have a status.hedera.com page (or that we have 12 nodes) itself doesn't maintain the decentralized property. Adding an API version would not decrease the decentralization.
Although I would be curious to hear your thoughts!

**Comment by lbaird** [comment]
The status.hedera.com page is just for information. But there’s a single point of failure of a single party that could theoretically lie. So we wouldn’t want clients to base their behavior on what a single person is claiming.

It also wouldn’t help if a client were a victim of a firewall that blocked a certain node. The centralized list would show that node as active, even though that particular client can’t reach it.

Instead, a client should remember which nodes it has found to be slow or offline, and avoid them in the future. And only try them again occasionally, to see if they improved.

________________________________

**Comment by donaldthibeau** [comment]
Will be fixed in upcoming version per above.

**Comment by johnda98** [comment]
I should have checked - good thread - ran into intermittent mainnet 503 exceptions - some nodes that status.hedera may not have been fully healthy.   Greg and I discussed and we found maybe related issue to node selection ..  issue#399 replacenodes maybe passing a null and thus  tripping up the tran builder
