### ISSUE TITLE
No support in sdk to handle dynamic array from solidity.

### ISSUE THREAD

**Issue by arijitban6** [hashgraph/hedera-sdk-java#396]
sdk is not able to handle/parse string array or struct array. Currently, no method available in ContractFunctionResult class to get string array or struct array from the raw result.

Solidity code:
`function getUserByRole(string memory role) public returns (string[] memory)`
Java code:
```
transactionId = new ContractExecuteTransaction()
                    .setContractId(newContractId)
                    .setGas(100_000_000)
                    .setFunction("getUserByRole", contractFunctionParams)
                    .execute(client);
            TransactionReceipt transactionReceipt = transactionId.getReceipt(client);
            contractFunctionResult = transactionId.getRecord(client).getContractExecuteResult();
            System.out.println("contract returned message:" + contractFunctionResult.getString(0));
            System.out.println("contract returned message:" + contractFunctionResult.getString(1));
            System.out.println("contract returned message:" + contractFunctionResult.getString(2));
            System.out.println("contract returned message:" + contractFunctionResult.getString(3));
            System.out.println("contract returned message:" + contractFunctionResult.getString(4));
```
To be sure I have printed other index also.
Output:
![image](https://user-images.githubusercontent.com/32069979/82412021-7d841e00-9a90-11ea-9093-d61c3868949d.png)

**Comment by mehcode** [comment]
@arijitban6 Thank you for opening an issue. I'm sure it's not too much to add that. Note that there is an ethereumj java library that has a complete set of solidity type decoding options which might help in the short term.

**Comment by danielakhterov** [comment]
`ContractFunctionResult.getStringArray(int index)` is now supported on master.
