### ISSUE TITLE
AccountInfo.key looks to be returning an object when fed with old mainnet accounts

### ISSUE THREAD

**Issue by johnda98** [hashgraph/hedera-sdk-java#397]
attached. 

0.0.910 is the a/c
![Screenshot from 2020-06-11 11-31-23](https://user-images.githubusercontent.com/13384285/84415461-6c828480-abd8-11ea-8ec5-59504997d7fa.png)

 AccountInfo info = new AccountInfoQuery()
       		             .setAccountId(anyaccoperatorid)
       		             .execute(client);
       	         
       	   	    		 out.println("<p> </p> ");
       	   	    		 out.println("<p>Public Key                       = " + info.key +"</p>");

**Comment by mehcode** [comment]
@johnda98 Can you explain what you expect to happen? These "lower number" mainnet accounts do have an object for the key. Keys are complex structures in Hedera. As shown in your image, that account has a _list_ of keys instead of a single key.

**Comment by johnda98** [comment]
thanks Ryan .. yes interesting.. yep higher accounts as usual the public key .. all good then,  IDK the older accounts returned an object ref.  I'll inform our client.
