### ISSUE TITLE
intermittent - and costs me hours in delays..main Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 503

### ISSUE THREAD

**Issue by johnda98** [hashgraph/hedera-sdk-java#398]
. now writing chunks of contract bytecode file: 0.0.44937
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 503
invalid content-type: text/html
headers: Metadata(:status=503,cache-control=no-cache,content-type=text/html)
DATA-----------------------------
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

DATA-----------------------------

    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:110)
    at com.hedera.hashgraph.sdk.HederaCall.lambda$execute$0(HederaCall.java:55)
    at com.hedera.hashgraph.sdk.Backoff.tryWhile(Backoff.java:37)
    at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:58)
    at com.hedera.hashgraph.sdk.Transaction.execute(Transaction.java:122)
    at com.hedera.hashgraph.sdk.TransactionBuilder.execute(TransactionBuilder.java:193)
    at com.hedera.hashgraph.sdk.TransactionBuilder.execute(TransactionBuilder.java:15)
    at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:44)
    at artifactid.LScontractDeployer.main(LScontractDeployer.java:113)
[1:11 PM]
getting tired of these intermittent 503 unavailables on mainnet ...  going to have to give my client the news..   I dont careif the 503 is tripped on the call or the call for the receipt ..   its getting VERY expensive.
[1:11 PM]
not in Hbar but in human TIME

**Comment by donaldthibeau** [comment]
@johnda98 are you submitting to a specific node when this error occurs? https://status.hedera.com/ provides the status of the mainnet nodes. If a node goes offline this could cause the error.

**Comment by johnda98** [comment]
nope.. I think the simple call to client.mainnet.. covers all nodes https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/Client.java
**
     * Get a Client configured for Hedera mainnet access.
     * <p>
     * Most users will also want to set an operator account with
     * {@link #setOperator(AccountId, PrivateKey)} so transactions can be automatically
     * given {@link TransactionId}s and signed.
     *
     * @return a Client configured for Hedera mainnet access
     */
    public static Client forMainnet() {
        // connect to all known nodes
        final HashMap<AccountId, String> nodes = new HashMap<>();
        nodes.put(new AccountId(3), "35.237.200.180:50211");
        nodes.put(new AccountId(4), "35.186.191.247:50211");
        nodes.put(new AccountId(5), "35.192.2.25:50211");
        nodes.put(new AccountId(6), "35.199.161.108:50211");
        nodes.put(new AccountId(7), "35.203.82.240:50211");
        nodes.put(new AccountId(8), "35.236.5.219:50211");
        nodes.put(new AccountId(9), "35.197.192.225:50211");
        nodes.put(new AccountId(10), "35.242.233.154:50211");
        nodes.put(new AccountId(11), "35.240.118.96:50211");
        nodes.put(new AccountId(12), "35.204.86.32:50211");

        return new Client(nodes);
    }

    /**
     * Get a Client configured



so in .env  NODe and NODe_ADDRESS are not used

**Comment by johnda98** [comment]
It seems to be intermittent..one call works... 1 Sc deploys falls over.. then re-run..deploys fine ..

   // grab paying deployer account..
        
       // Client client = Client.forTestnet();
        Client client = Client.forMainnet();
        
        client.setOperator(OPERATOR_ID, OPERATOR_KEY);
        client.setMaxTransactionFee(50_000_000_000L);
        
        TransactionId fileTxId = new FileCreateTransaction()

**Comment by johnda98** [comment]
Don, Ryan

yes .. this is somewhat related to the issue raised by Greg after him and I discussed.. I found that replacenodes in Client was setting a url to null ( a related find)..   However,  the abstracted issue as touched on by a few is that no at runtime way of avoiding a 503 if any of the hitherto healthy nodes picked (hedera.status) .. have a problem..   so we can close this out as its not a issue, its a feature. (until self healing nodes are on council or some sort of push to DApps of each node status )

**Comment by johnda98** [comment]
feature.

**Comment by mehcode** [comment]
There is a way actually and this is fixed on the develop branch. It was a massively invasive refactor which is why it's a new branch with some minor breaking changes.
