### ISSUE TITLE
Question: Why SpongyCastle (instead of Bouncy)?

### ISSUE THREAD

**Issue by Sajjon** [hashgraph/hedera-sdk-java#4]
I saw ([in ECKeypair.java](https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/sdk/cryptography/ECKeyPair.java#L7-L23) for example) that [SpongyCastle](https://github.com/rtyley/spongycastle) is used instead of [BouncyCastle](https://github.com/bcgit/bc-java)

I found this [Github issue by the author about Spongy being obsolete or not](https://github.com/rtyley/spongycastle/issues/34) but most people voted for SC being wanted.

So I just thought it would be interesting to know which advantages of SpongyCastle was attractive to prefer chose it over BouncyCastle 😄

**Comment by gregscullard** [comment]
Hi, some time ago when we started work on the cryptography side of the SDK, we looked at many libraries and were a also conscious to ensure that keys generated from the Android+iOS wallets were fully compatible with those generated by the SDK and vice-versa. The Android wallet uses SpongyCastle so to avoid any inconsistencies it felt right to use the same in the Java SDK. Having tried other libraries such as LibSodium, compatibility wasn't consistent.

Hope this clarifies.
Greg

**Comment by jbuhacoff** [comment]
Hi, in case you need a more recent version of BouncyCastle in the SpongyCastle style, I made a tool called `mybc` for building your own customized BC library, so you don't need to wait for the next SpongyCastle release. There's a section in the README specifically about making a drop-in replacement for SpongyCastle. I'm using it in my Android app. Currently it's building BC version 1.62 for JDK 1.5 successfully. Links:  [mybc on GitHub](https://github.com/jbuhacoff/nodejs-mybc-util) and [mybc on NPM](https://www.npmjs.com/package/@jbuhacoff/mybc).  If it helps please star the repo!
