### ISSUE TITLE
Float last selected node to the developer

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#400]
In the event that communication with a node fails, the developer sees an error but is unable to tell which node was chosen. This makes it difficult to dynamically manage a list of healthy nodes.

Would it be possible to make that last node selection available as a public property of the client ?

**Comment by mehcode** [comment]
> This makes it difficult to dynamically manage a list of healthy nodes.

This should probably be implemented by the SDK as a deprioritizing a node.

---

> the developer sees an error but is unable to tell which node was chosen.

We never return these errors in v2 because we try a different node on node network failure. I'm not sure a good place to communicate this where it would work.
