### ISSUE TITLE
Name of setMaxQueryPayment may be misleading

### ISSUE THREAD

**Issue by paulmadsenhed** [hashgraph/hedera-sdk-java#405]
This is the default value that clients will use in the payment transactions for queries unless overridden by an explicit setQueryPayment. 

use of 'max' may give the impression that , as for maxTransactionFee, clients are protected against overpayment by the node's calculating an actual & lower fee.

But, if not overridden, the nodes will charge the client this fee.

Perhaps 'setDefaultQueryPayment' ?

**Comment by mehcode** [comment]
That is not what it does actually. We look up the cost from the network and then use the actual cost if it's under the configured maximum.

**Comment by paulmadsenhed** [comment]
hmm, I'm talking to a customer that has setMaxQueryPayment = 10 hbars, and thats what they're paying . Will confirm

**Comment by mehcode** [comment]
I'm pretty confident this is what we're doing: 

https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/QueryBuilder.java#L176-L187

We do have a `.setQueryPayment` method that operates as you're describing.

**Comment by danielakhterov** [comment]
Closing as this is a stale issue. If you're having further trouble please reopen.
