### ISSUE TITLE
Handle GRPC error and resubmit if not accepted by the network

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#407]
We occasionally get a gRPC error `server closed the stream without sending trailers` when sending a transaction to Hedera. 
Note: This applies to all SDKs, not just this Java SDK.

It is however possible that despite this error, the transaction has been successfully submitted, so we should not just retry.

So mitigation should be:
-Send to network, get gRPC error
-Query same node for receipt on transaction id without waiting for consensus time. The node will know immediately if the transaction id is valid or not.
-If transaction is unknown, resubmit
-If transaction is known, don't resubmit

Either the SDK handles this error per the above, or it provides sufficient information for the client to make an informed decision. 

If the former is chosen, there may be other errors that will require the same handling, provision for a list of possible errors might be desirable to implement.

If the latter option is chosen:
* The SDK must let the client know which node was chosen
* The SDK must enable a client to target a specific node when asking for a receipt
* The receipt query must have an override to skip the initial wait period and not loop if UNKNOWN.

**Comment by danielakhterov** [comment]
I know this is an error you were getting with the v1 SDK, however I'm wondering if you could still reproduce this in v2.

**Comment by danielakhterov** [comment]
Closing as this is a stale issue. If you're still having trouble feel free to reopen the issue.
