### ISSUE TITLE
How to get message for CONTRACT_REVERT_EXECUTED 

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-java#408]
Hi,

I am getting HederaStatusException but I can't find a message(returned from solidity) for CONTRACT_REVERT_EXECUTED?

**Comment by rahulasati** [comment]
any updates on this?

**Comment by mehcode** [comment]
Get the transaction record and the function result will contain the error message.

**Comment by rahulasati** [comment]
Ok you mean from the catch block we should call for transaction record? @mehcode

**Comment by mehcode** [comment]
If you ask for the record and not the receipt – `getRecord` – the exception will contain the record:

https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/HederaRecordStatusException.java#L23

**Comment by rahulasati** [comment]
Ok got it, so now I tried to print exception as JSON String but an error message is still empty, am I missing anything?

{"record":{"consensusTimestamp":{},"inner":{"bodyCase_":7,"body_":{"bloom_":{"bytes":[],"hash":0},"contractCallResult_":{"bytes":[],"hash":0},"errorMessage_":"","gasUsed_":2501,"logInfo_":[],"memoizedIsInitialized":-1,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"consensusTimestamp_":{"memoizedIsInitialized":-1,"nanos_":964039000,"seconds_":1596050270,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"memo_":"","memoizedIsInitialized":-1,"receipt_":{"exchangeRate_":{"currentRate_":{"centEquiv_":131654,"expirationTime_":{"memoizedIsInitialized":-1,"seconds_":1596052800,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"hbarEquiv_":30000,"memoizedIsInitialized":-1,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"memoizedIsInitialized":-1,"nextRate_":{"centEquiv_":131577,"expirationTime_":{"memoizedIsInitialized":-1,"seconds_":1596056400,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"hbarEquiv_":30000,"memoizedIsInitialized":-1,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"memoizedIsInitialized":-1,"status_":33,"topicRunningHash_":{"bytes":[],"hash":0},"topicSequenceNumber_":0,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"transactionFee_":93001552,"transactionHash_":{"bytes":[21,-60,59,-93,74,-73,113,18,-75,58,-16,118,112,56,38,-113,-45,30,-15,-77,-24,17,-116,115,-13,96,29,-86,-78,-1,-46,-95,-66,-59,-102,-2,-43,16,-79,-16,122,5,91,-75,67,-91,-112,21],"hash":0},"transactionID_":{"accountID_":{"accountNum_":113328,"memoizedIsInitialized":-1,"realmNum_":0,"shardNum_":0,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"memoizedIsInitialized":-1,"transactionValidStart_":{"memoizedIsInitialized":-1,"nanos_":765000000,"seconds_":1596050259,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"transferList_":{"accountAmounts_":[{"accountID_":{"accountNum_":3,"memoizedIsInitialized":-1,"realmNum_":0,"shardNum_":0,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"amount_":5763801,"memoizedIsInitialized":-1,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},{"accountID_":{"accountNum_":98,"memoizedIsInitialized":-1,"realmNum_":0,"shardNum_":0,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"amount_":87237751,"memoizedIsInitialized":-1,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},{"accountID_":{"accountNum_":113328,"memoizedIsInitialized":-1,"realmNum_":0,"shardNum_":0,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"amount_":-93001552,"memoizedIsInitialized":-1,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0}],"memoizedIsInitialized":-1,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"receipt":{"inner":{"exchangeRate_":{"currentRate_":{"centEquiv_":131654,"expirationTime_":{"memoizedIsInitialized":-1,"seconds_":1596052800,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"hbarEquiv_":30000,"memoizedIsInitialized":-1,"unknownFields":{"fields":{},"fieldsDescending":{}},"memoizedSize":-1,"memoizedHashCode":0},"memoizedIsInitialized":-1,"nextRate_":{"centEquiv_":131577,"expirationTime_":{"memoizedIsInitialized":-1,"seconds_":1596056400,"unknownFields":{"fields":
expirationTime_2020-07-30 00:48:49.685 22436-22436/com.myearthid E/SensorManager: unregisterListenerImpl callingApp: com.myearthid,callingPid:22436,callingUid:10294
2020-07-30 00:48:50.090 22436-23935/com.myearthid D/ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=false inTouchMode=true

**Comment by rahulasati** [comment]
@mehcode

**Comment by rahul-kothari** [comment]
Hey @rahulasati sorry just saw this
The way the SDK is structured, it seems not possible to find the reason.

As you may know `CONTRACT_REVERT_EXECUTED` is thrown when solidity executes a revert() method. Unlike ethereum however, hedera can't show you the revert message. You will have to debug this on your own though. Your best tip is to isolate the exact method call to your smart contract and identify which revert() is called.

**Comment by mehcode** [comment]
@danielakhterov I think we just need an example for this.

**Comment by mehcode** [comment]
To be clear, the error messages is rendered in the contract function result, here: https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java#L65

You need to request the transaction record of the failing contract call to get that information.
