### ISSUE TITLE
getRecord - transport error occurred while accessing the Hedera network

### ISSUE THREAD

**Issue by rahulasati** [hashgraph/hedera-sdk-java#409]
Hi,

I am getting below exception when trying to get the record

contractCall TransactionRecord error :: com.hedera.hashgraph.sdk.HederaNetworkException: transport error occurred while accessing the Hedera network

```
new ContractExecuteTransaction()
                .setContractId(new ContractId(shardNum, realmNum, contractNum))
                .setGas(1000000)
                .setFunction(functionName, callParams)
                .executeAsync(client, new Consumer<TransactionId>() {
                    @Override
                    public void accept(TransactionId transactionId) {
                        // if this doesn't throw then we know the contract executed successfully
                        try {
                            transactionId.getReceipt(client);
                        } catch (HederaStatusException e) {
                            onError.accept(e);
                        }
                        new TransactionRecordQuery()
                                .setTransactionId(transactionId)
                                .executeAsync(client, onSuccess, onError);
                    }
                }, onError);
```

1. ContractExecuteTransaction - **Call successful**
2.  transactionId.getReceipt(client); -  **Call successful**
3.  new TransactionRecordQuery().setTransactionId(transactionId).executeAsync(client, onSuccess, onError); - **Getting Exception**

Note - tried with adding sleep before and after receipt but no luck but if I change get record to call `TransactionRecord transactionRecord = transactionId.getRecord(client);` It works well

Environment - Android

**Comment by danielakhterov** [comment]
This might be because you are using `getReceiptAsync(client)` `getRecordAsync(client)` inside a callback. Not entirely sure if this is the root cause, but worth a shot. I believe `getRecord()` and `getReceipt()` block the current/main thread which sounds like it would be an issue if run from inside a callback.

**Comment by danielakhterov** [comment]
Closing as this is a stale issue. If you're still having trouble feel free to reopen the issue.
