### ISSUE TITLE
Duplicate signatures result in thrown exception

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#412]
When a transaction is created, if it is signed manually and executed with a client where the operator and key are set, an exception is thrown indicating the transaction is already signed with the same key. This is not happening with the GO SDK and feels like an overly intrusive error, why not just skip the signing operation and continue without throwing an error ?

Note: This occurred while attempting to calculate the Hash of a transaction, this requires all signatures to be present, but means the transaction cannot then be executed unless `client = new Client().forTestnet` is called prior to the `.execute`, followed by `client = new client().forTestnet(); client.setOperator(OPERATOR_ID, OPERATOR_KEY);` before getting a receipt or record for the transaction.

**Comment by mehcode** [comment]
I agree. We've already made this change in the `develop` branch for v2.
