### ISSUE TITLE
Add property to TransactionId which returns the hash of the transaction as sent to the network

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#414]
Getting the hash of a transaction is the responsibility of a client using the SDK. It would be useful to integrate this capability in the SDK such that the SHA-384 hash of the bytes sent to the network are available as a property of the TransactionId entity returned after the call is executed.

**Comment by danielakhterov** [comment]
Currently this is supported through the `TransactionResponse` class since it returns both the `TranasactionId` and the hash of the transaction that was sent. Even though this question was for v1 of the SDK, and v2 is the SDK that has resolved this issue I'm still going to mark it closed.
