### ISSUE TITLE
Memory leak in MirrorConsensusTopicQuery

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-sdk-java#416]
In version 1.2.0, there's a huge memory leak in `MirrorConsensusTopicQuery`. Subscribing to a busy topic will eventually get an `OutOfMemoryError`. Problem looks to be that it adds to the `pendingMessages` map but it never removes from that map. I'm only sending 256B messages and the SDK by default sets a chunk with 1 of 1. Profiled it in VisualVM and tracked it down:

<img width="1139" alt="Screen Shot 2020-09-15 at 20 03 41" src="https://user-images.githubusercontent.com/17552371/93280233-bd34eb00-f78e-11ea-922a-6bc4e6b951a9.png">

**Comment by steven-sheehy** [comment]
Could've worked around it by not sending chunkInfo, but there doesn't seem to be a way to set chunkInfo to null. The SDK will always put a 1 of 1 chunk if not provided. Would be good to be able to send null to HAPI if requested to reduce payload size and avoid the slow, stateful path.

**Comment by danielakhterov** [comment]
@steven-sheehy can you reproduce this issue in v2 of the SDK? I understand this tested with v1, and v1 needs to be fixed since this is a bug, but I'm wondering if v2 has the same issue.

**Comment by steven-sheehy** [comment]
@danielakhterov You fixed this in v1 via commit b252ae1e5c25dd3e2c949776105adcfa2e155711 but probably forgot to mark it as fixing this. I don't have the bandwidth to test v2 but v1 is working fine now. This can be closed.
