### ISSUE TITLE
Update token modifying transaction bodies for autoRenewPeriod, expiry and totalSupply

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#425]
TokenCreateTransactionBody should return a Duration for AutoRenewPeriod, similar to ConsensusCreateTopic
TokenCreateTransactionBody should return a Timestamp for Expiry, similar to ConsensusCreateTopic
TokenMint, TokenBurn and TokenWipe should return the new totalSupply value post applying the transactions

Change dependent on protobuf update to include the above.

Hedera Services issue: https://github.com/hashgraph/hedera-services/issues/645

**Comment by danielakhterov** [comment]
@SimiHunjan 
I understand this:
> TokenCreateTransactionBody should return a Duration for AutoRenewPeriod, similar to ConsensusCreateTopic
TokenCreateTransactionBody should return a Timestamp for Expiry, similar to ConsensusCreateTopic

However, I don't understand what the SDK should do about:
>  TokenMint, TokenBurn and TokenWipe should return the new totalSupply value post applying the transactions

**Comment by SimiHunjan** [comment]
Total supply should return the current total supply (Initial total supply +TokenMint - (TokenBurn +TokenWipe). Not the initial total supply the token was created with.

**Comment by danielakhterov** [comment]
Sorry, I'm still not completely understanding. Right now if you execute any transaction you will always receive a `TransactionResponse` which contains only the `TransactionId` and execution node's `AccountId`. Are you saying we should be returning more special information if the transaction happens to be a `TokenMint`, `TokenBurn`, or `TokenWipe` transaction?

**Comment by danielakhterov** [comment]
Master now supports `TransactionReceipt.totalSupply` https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceipt.java#L70
