### ISSUE TITLE
Typo in client class

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#427]
v2.0.0
```
    public void setMirrorNetwork(List<String> newtork) throws InterruptedException {
        mirrorNetwork.setNetwork(newtork);
```

newtork -> network

https://github.com/hashgraph/hedera-sdk-java/blob/v2.0.0/sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java

**Comment by danielakhterov** [comment]
Thank you for the issue; fixed on `develop`.
