### ISSUE TITLE
v2.0.1 token transfers not returned in record

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#430]
See: https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java

https://github.com/hashgraph/hedera-services/blob/master/hapi-proto/src/main/proto/TransactionRecord.proto

**Comment by danielakhterov** [comment]
This field now exists on master https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java#L74
