### ISSUE TITLE
v2.0.1 - MultiAppTransferExample doesn't work - returns INVALID_SIGNATURE

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#431]
Debugging the above.

-User creates a transaction and signs it. The Transaction object contains 1 sigPair
-Transaction converted to byte array, sent to "exchange" which signs (after signing, the transaction object contains 1 sigPair)
-Exchange returns as byte Array to user - Transaction object now contains 0 sigPair
-Execute returned transaction - fails due to no signatures.

to reproduce easily:

create a transaction then

```
        transferTxn.freezeWith(client);
        transferTxn.sign(userKey);
```

inspecting the `transferTxn.sign` transaction shows signatures size 1, sigPair count is 1
then

```
        byte[] testTxBytes = transferTxn.toBytes();
        Transaction<?> testTransaction = Transaction.fromBytes(testTxBytes);
```

inspecting the `testTransaction` transaction shows signatures size 1, sigPair count is 0 (should be 1)

```
        testTransaction.sign(userKey);
```

sigPair count is now 1

**Comment by gregscullard** [comment]
Also note that when the transaction is first created, it contains 2 node ids (0.0.3 and 0.0.6 as set by the SDK).
Converting to byte array and back, the resulting transaction only contains a single node id (0.0.6), the conversion is "lossy" in that sense.

**Comment by danielakhterov** [comment]
I believe this is fixed on master now.
