### ISSUE TITLE
Add `maxRetry` to v1 of the SDK

### ISSUE THREAD

**Issue by ijungmann** [hashgraph/hedera-sdk-java#435]
The `maxRetry` functionality added [here](https://github.com/hashgraph/hedera-sdk-java/commit/964e35e24ef67af6f2f197c7ec44f6e40e4fa1b7) would be extremely useful to the mirror node, as it would allow it to disable retries when doing performance testing.  For the time being, the mirror node is using v1 of the SDK, where this is not present.  Porting this functionality to v1 would allow us to take advantage of this performance gain.

**Comment by mehcode** [comment]
Not possible unfortunately. Adding retries was a major reason for doing a v2.
