### ISSUE TITLE
Suppress SLFJ4 errors

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#442]
If the SDK detects there is not a logger set-up it should suppress the errors displayed in the terminal when running code.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by danielakhterov** [comment]
From the recent discussion on Slack, it seems this issue should be updated to track SDK's documenting how to set up a logger to suppress that output.
