### ISSUE TITLE
Update to support scheduled transactions

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-sdk-java#446]
Update Java SDK to support scheduled transactions. Currently targeted for March Mainnet release.

**Comment by danielakhterov** [comment]
Just a heads up to anyone else looking at this issue, scheduled transaction now be supported in the latest beta release: v2.0.5-beta.1
A full release will be issued when scheduled transactions are supported on testnet.

**Comment by danielakhterov** [comment]
Both v1 a v2 support scheduled transactions, and have been released; closing.
