### ISSUE TITLE
Add method to parse binary files (0.0.111)

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#449]

**Comment by danielakhterov** [comment]
Are you sure this is something that should be in the SDK? Currently the SDK doesn't support parsing any file.
If we do want to support parsing certain files we'd need a curated list of all files and what the output should be.

**Comment by danielakhterov** [comment]
From the meeting we had today I can confirm this is something the SDK should do. Currently the only two files I know of that need to be parsed are `0.0.101` and `0.0.111`. Are there any other that need to be supported in the SDK's?

**Comment by Sean-Tedrow-LB** [comment]
Is this issue now handled?
