### ISSUE TITLE
Java 8 code in `Network.java` not compatible with iOS App using RoboVM.

### ISSUE THREAD

**Issue by timmolter** [hashgraph/hedera-sdk-java#450]
In `Network.java` line 89 there is a call: `nodes.sort(Node::compareTo);`. This is incompatible with the latest RoboVM library which doesn't support Java 8+.
```
Unhandled exception (probably in a @Callback method called from native code): java/lang/NoSuchMethodError
```
Can you change the sort to `Collections.sort(list, comparator) instead for the jdk7 variation? Alternatively, I can change it and submit a PR. Please let me know, thanks!

**Comment by danielakhterov** [comment]
Thank you for the issue. We'll fix this as soon as we get back in the office Tuesday, and hopefully release soon after. If you'd like to make a PR that'd be appreciated as well.
