### ISSUE TITLE
Replace id -> accountId

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#454]
https://github.com/hashgraph/hedera-sdk-java/blob/v2.0.5-beta.4/sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleCreateTransaction.java#L64

https://github.com/hashgraph/hedera-sdk-java/blob/v2.0.5-beta.4/sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleDeleteTransaction.java#L31

id -> scheduleId

https://github.com/hashgraph/hedera-sdk-java/blob/v2.0.5-beta.4/sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleInfoQuery.java#L21

**Comment by danielakhterov** [comment]
Hmm, may I ask why you requested these changes? The naming of the parameter should have no affect on the actual SDK.

**Comment by SimiHunjan** [comment]
For consistency as it is used in other classes:

https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalanceQuery.java#L38

https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalanceQuery.java#L38

All the IDs have the entity name preceding it.

**Comment by danielakhterov** [comment]
This seems to be resolved now; closing.
