### ISSUE TITLE
Transaction record missing scheduleRef field

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#455]
Missing: `ScheduleID scheduleRef = 12; // Reference to the scheduled transaction ID that this transaction record represent`
SDK: https://github.com/hashgraph/hedera-sdk-java/blob/v2.0.5-beta.4/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java

Transaction Record proto: 
https://github.com/hashgraph/hedera-protobufs/blob/develop/services/TransactionRecord.proto#L48

**Comment by danielakhterov** [comment]
Thanks for pointing this out; can confirm `master` contains `TransactionRecord.scheduleRef`
