### ISSUE TITLE
Rename `Executable.setMaxRetry()` -> `Executable.setMaxAttempts()`

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-java#459]

**Comment by Regan-Koopmans** [comment]
@danielakhterov Should this be updated in `Transaction` too?
https://github.com/hashgraph/hedera-sdk-java/commit/964e35e24ef67af6f2f197c7ec44f6e40e4fa1b7#diff-8aea266fd30d2c85bc481eceaa926c20b9aa71451171e5000e33427c034b637e
