### ISSUE TITLE
Update SDK to support new HCS message size limit

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-sdk-java#463]
HCS will be updated to have a HCS message size limit of 1024 bytes. Users who attempt to submit larger messages should be easily able to have those messages chunked into multiple successive messages. This is targeted for the May mainnet update.

https://github.com/hashgraph/hedera-services/issues/1145

**Comment by danielakhterov** [comment]
This is now fixed in both v1 and v2 SDK's, and has been released.
