### ISSUE TITLE
 io.grpc.StatusRuntimeException: UNAVAILABLE

### ISSUE THREAD

**Issue by amircoder** [hashgraph/hedera-sdk-java#466]
Hedera SDK is integrated into our app and it's working fine. but there is a problem testing the app in some networks. I guess there is some network ban or cloudfire exception in between. 
The actual error happens when I use in the Iran internet network.
I don't know if this error comes from Hedera network or the ISP has done something with gRPC calls.
Can you please give your opinion regarding this issue?
BTW I've put the error I am getting in the following GIST:
https://gist.github.com/amircoder/7393171eeb88c6365582fba8b6279cad

**Comment by danielakhterov** [comment]
I believe the mainnet nodes have been moved from port 50211 to 50212. This is fixed on the `master` branch of the SDK, but has not been released yet, but will be released soon.
