### ISSUE TITLE
Support multiple strategies for picking nodes from a network

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-java#468]
Currently the SDK only supports two methods for setting nodes on a transaction or query.
- 1/3rd of the network nodes will be picked in a round robin fashion regarding their usage.
  - Pro: Nodes are automatically round robin'd.
  - Con: Each request must maintain a list of protobufs; one protobuf for each node which increases memory significantly.
- The user can set specific nodes to use for a certain request explicitly.
  - Pro: The user can specify a single node to reduce memory usage, or all the nodes to maximize reliability.
  - Con: The user would be required to round robin these nodes between requests manually otherwise certain nodes will be over used.

This issue requests the `Client` which contains the `Network` to expose a method to change the strategy that picks which and how many nodes to use per request without users specifying the nodes themselves.

Requested Strategy:
- Pick a single node from the network per request, and only round robin nodes per request instead of per attempt.
  - Pro: Significantly reduces memory since only one protobuf will be required per request.
  - Con: If a node is down some requests will fail with no potential for recovery _from within on execution call_.

Note: If less memory is confused, then the languages GC will need to run less often which increases performance.
Note: Although this issue is in the Java SDK it applies to all currently supported SDKs (Java, JS, and Go).

```java
public enum NetworkStategy {
    ThirdNetwork,
    SingleNode;
}
```

We could use something more arbitrary such as `Performance` and `Reliability` network strategies, but I feel that is too arbitrary and could come to bite us later where we find some new strategy we deem more efficient or reliable than the current strategies.

**Comment by mehcode** [comment]
This is supported now through `setMaxAttempts`.
