### ISSUE TITLE
Transaction body is not returned from requesting a schedule info

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#475]
Transaction body missing:

![Screen Shot 2021-04-14 at 10 30 40 PM](https://user-images.githubusercontent.com/21989138/114818766-328e8b80-9d71-11eb-919a-37937e232bc2.png)

**Comment by andrix10** [comment]
Yep we are returning the specific transaction that contains the body that we received.

**Comment by SimiHunjan** [comment]
I believe I should be able to return the transaction that was scheduled?

https://github.com/hashgraph/hedera-protobufs/blob/develop/services/ScheduleGetInfo.proto#L54

**Comment by mehcode** [comment]
> I believe I should be able to return the transaction that was scheduled?

That *is* what `.getTransaction` is doing. It has to be a method call as it has to parse that into the correct transaction type. Though we should probably rename that to match the other fields to `.getScheduledTransaction`

cc @andrix10 @danielakhterov

**Comment by SimiHunjan** [comment]
thanks that would make it more clear!

**Comment by danielakhterov** [comment]
Issue seems to be resolved, but was not closed; closing.
