### ISSUE TITLE
Transactions should be printable even if not frozen

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#476]
```
        TransferTransaction transaction = new TransferTransaction()
                .addHbarTransfer(newAccountId, Hbar.fromTinybars(-1))
                .addHbarTransfer(myAccountId, Hbar.fromTinybars(1));

        //Create a scheduled transaction
        ScheduleCreateTransaction scheduledTransaction = new ScheduleCreateTransaction()
                .setScheduledTransaction(transaction);
        System.out.println("The schedule transaction is " + scheduledTransaction);
```
output:

The scheduled transaction is # **com.hedera.hashgraph.sdk.proto.TransactionBody**. <--
transaction_fee: 500000000
transaction_valid_duration {
  seconds: 120
}

**Comment by andrix10** [comment]
You have to freeze the transaction, as that builds the body.

**Comment by SimiHunjan** [comment]
I have to freeze which transaction? The ScheduleCreateTransaction?

**Comment by danielakhterov** [comment]
Hijacking issue, we should support printing the transaction even if it's not frozen.

**Comment by andrix10** [comment]
Create Scheduled Transaction now supports printing even if it's not frozen.
