### ISSUE TITLE
Parameter name should be identical 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#477]
https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleDeleteTransaction.java#L35

https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleSignTransaction.java#L31. <-- change to scheduleId

**Comment by danielakhterov** [comment]
This seems to be resolved now.
