### ISSUE TITLE
v1.4.0 is missing .getScheduledTransactionId

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#487]
Cannot return scheduled transaction ID from receipt of a schedule create transaction.

v1: https://github.com/hashgraph/hedera-sdk-java/blob/v1.4.0/src/main/java/com/hedera/hashgraph/sdk/TransactionReceipt.java

v2: https://github.com/hashgraph/hedera-sdk-java/blob/v2.0.5/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceipt.java#L91

**Comment by danielakhterov** [comment]
Thanks, I missed this and the `TransactionRecord.scheduleRef` issue. I've fixed both, added this to the changelog, and this will be part of the next release.
