### ISSUE TITLE
v1.4.0 schedule ref is missing from the transaction record

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#488]
v2: https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java#L77

v1: https://github.com/hashgraph/hedera-sdk-java/blob/v1.4.0/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java

**Comment by danielakhterov** [comment]
Fixed, this should be part of the next release.
