### ISSUE TITLE
I sent my HBAR off of binance.us to a testnet wallet. Need help

### ISSUE THREAD

**Issue by JahovasThickness** [hashgraph/hedera-sdk-java#491]
I sent HBAR to a test net wallet and was directed to here. I know nothing about coding, and the migration article https://hedera.com/blog/migrating-tokens-on-hts-from-testnet-to-mainnet is no help at all.
Thank you

**Comment by danielakhterov** [comment]
I'm not sure what to say here. What is the issue?

**Comment by mehcode** [comment]
There is nothing we can help you with here unless you own the ID on the main network where the tokens ended up. It's not possible to send tokens to a testnet wallet. If you sent the tokens to a wallet that you own that is testnet, the same ID on mainnet now has the tokens.
