### ISSUE TITLE
Run CI against Hedera Services `master` daily

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-java#498]

**Comment by SimiHunjan** [comment]
Is this representative of all SDKs or do we need to create issues in each one?

**Comment by danielakhterov** [comment]
This represents just the Java SDK, I'll make issues in the other SDK's as well.

**Comment by danielakhterov** [comment]
Closed by: https://github.com/hashgraph/hedera-sdk-java/pull/499
