### ISSUE TITLE
mvn install fails

### ISSUE THREAD

**Issue by bandrebandrebandre** [hashgraph/hedera-sdk-java#5]
When I clone the repository and run `mvn build`, I get the following error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project sdk: Compilation failure
[ERROR] ~/hedera-sdk-java/src/main/java/com/hedera/sdk/common/HederaKeyList.java:[12,42] cannot access com.hederahashgraph.api.proto.java.Key
[ERROR]   bad class file: ~/.m2/repository/com/opencrowd/hapi-proto/1.1/hapi-proto-1.1.jar(com/hederahashgraph/api/proto/java/Key.class)
[ERROR]     class file has wrong version 54.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.`

This is on MacOS High Sierra 10.19.6, Maven 3.5.4, java version 1.8.0_121

**Comment by rafialhamd** [comment]
Java version should be 10.0.x.

Your Java version is 1.8.x.

> Pre-requisites
> 
>     JDK: 10.0.x

**Comment by bandrebandrebandre** [comment]
Java is not the same as the JDK, but as it happens I didn't have an up-to-date version of the JDK. Works now, thanks!
