### ISSUE TITLE
How to get list of valid nodes for FileAppendTransaction

### ISSUE THREAD

**Issue by wensheng** [hashgraph/hedera-sdk-java#546]
### Problem

When I do `FileAppendTransaction`, If I don't provide `setNodeAccountIds`, the transaction fails `Index 3 out of bounds for length 3`.  

If I provide a List<AccountId> of more than 3 accountId, the transaction will fail `Some node account IDs did not map to valid nodes in the client's network`.

If I provide a List<AccountId> of 2 accountId, the transaction will fail again `index 3 out of bounds`.

Only when I use List of 1 accountId, the transaction succeeds.   I tried "0.0.4" and "0.0.6", both works. 

My question is: how do I know which node I should use?  Can I use any one of the 20 mainnet nodes?

I know I can get the nodeId from `FileCreateTransaction`, but my application is stateless and doesn't keep track of nodeId, I only have fileId.  Also the fact that I created file on node 0.0.4 but being able to append to it on node 0.0.6, makes keeping track of nodeId irrelevant.

### Solution

It would be helpful if `FileInfoQuery` provides a list of nodes that can be used for appending to a file.

**Comment by wensheng** [comment]
never mind this.
I found the list of nodes in client.network.nodes
so I closes this.

**Comment by mehcode** [comment]
This definitely sounds like a bug. I'll leave it open and ping one of our SDK developers. 

@Sean-Tedrow-LB
