### ISSUE TITLE
Implement `*[Query|Transaction].[to|from]Json()`

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-java#583]
### Problem

Users should be able to store requests in some human readable format such as JSON and construct requests directly from JSON to execute easily. If the user would to do this right now, they'd need to manually parse the JSON, check for nulls, and call the correct set methods for any fields which are not null.

### Solution

Implement `*[Query|Transaction].[to|from]Json()` which correctly encodes or decodes the JSON. One important note is that while decoding the JSON we should explicitly use the `set` methods instead of setting the fields directly. This should prevent small mistakes from happening such as what we have right with issues caused by `Transaction.fromBytes()` not using the setters.

**Comment by Juicestus** [comment]
I would like to try and make this fix, is there a prefered format for the JSON to be in?

**Comment by danielakhterov** [comment]
I think this discussion is still up for debate, but this is what I had in mind.

`AccountCreateTransaction`:
```javascript
{
    // Single Key
    "key": "302...",

    // Keylist and ThresholdKey
    "key": {
        "threshold": "10",
        "keys": [
            {
                "keys": [
                    "302...",
                    "302..."
                ],
            },
            "302..."
        ],
    },

    "initialBalance": "100 ℏ",
    "receiverSignatureRequired": false,
    "proxyAccountId": "0.0.5",
    "autoRenewPeriod": "7776000s",
    "accountMemo": "random memo",
    "transactionId": "0.0.14@1515.789321",
    "validDuration": "120",
    "maxTransactionFee": "2 ℏ",
    "transactionMemo": "random transaction memo",
    "nodeAccountIds": [
        "0.0.3",
        "0.0.4"
    ]
}
````

Some things to take away from this example:
 - Completely avoid using the `number` type; use `string` instead since in JS the `number` type has a limit to 2^53 after which it'll read the value incorrectly.
 - Hbar is represented as a number followed by the unit (this should already be converted by `Hbar.toString()`
 - Duration is represented as number followed by unit with no space
 - Key values can be either a single key, a list of keys, or a list of keys with a threshold. To represent the a single key we use the string representation, if the key is a list of keys or a threshold key we should use an object with fields "keys" and "threshold". The "keys" field should be an array of "Key" types which means it's recursive.

**Comment by Juicestus** [comment]
Ok, since this is a low-priority issue do you mind if I work on this?
The reason I say this is that I am new to large projects like this.

**Comment by danielakhterov** [comment]
Yea, no problem. If you can I'd like for you to create a draft PR with any changes you've made and I highly recommend you work on this in groups; do `Account*[Query|Transaction].[to|from]Json()` then `FIle*`, `Contract*`, etc. That way if you ever decide to stop working on it, or become busy with other things we'd still be able to merge your work.
