### ISSUE TITLE
Use `Lombok` to generate setters and getters

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-java#586]
### Problem

At the moment the SDKs have *a lot* of noise which mostly consists of getters and setters.

### Solution

Lombok from https://projectlombok.org/ supports annotations that can generate these methods at build time which would clean up a lot of code. However, as noted by several articles Lombok is known to be abused since often times developers would use annotations that generate excessive code. So, to keep our usage of Lombok sane, we should limit our usage to only `@Getter`, `@Setter`, `@NonNull`. To really test this change we'll need to run the build set in `variant/jdk7` branch as well.

**Comment by gregscullard** [comment]
Note. If you use Lombok, it’s not shipped with all IDEs (eg eclipse) leading to annotations not being understood, readme should be updated to ensure developers are able to install in order to load the sdk in an ide successfully. 

Also, some code quality / lint tools don’t always work well with Lombok, would suggest a small test on one class to ensure all is well before “going all in”


Envoyé depuis mon iPhone/Sent from my iPhone

**Comment by danielakhterov** [comment]
@gregscullard That's a good point. I'll make a simple PR with only `AccountCreateTransaction` being converted to use Lombok and we'll work from there.
cc @steven-sheehy in case you have anything else to add

**Comment by steven-sheehy** [comment]
Nope, we use Lombok extensively without issue. I don't see why you wouldn't use more of the lombok annotations than you list. Java 14 records should make a lot of Lombok unnecessary, but it will be a long time before the SDK can use that.

**Comment by danielakhterov** [comment]
There are two reasons I think we should limit our use of Lombok:
1) Code generation often leads to more complexity which makes it harder for someone new to understand the code base. 
2) Some of Lomboks annotations such as `@Data` generate more methods that we'd like such as `equals` and `hashCode` which often is not wanted. 
Perhaps later we'll use more of Lombok, but at least in the beginning I think it'd be best to limit our usage.

**Comment by danielakhterov** [comment]
After further investigation and internal discussion and as much as it pains me to say it, but I don't think we can proceed with using Lombok because of the following reasons:
1) Lombok does not work well with Javadoc. We need to be able to set `@NonNull` specifically on the generated setter which does not work with Javadoc; this would be done through the experimental `onParam` functionality. The `onParam` functionality works fine when building the project, but when running through Javadoc it fails hard. I tried to take a different approach with this by adding the `@NotNull` annotation to the field itself, and although this did maintain the functionality and did work with Javadoc I believe it is misleading since often times the field's default value is `null`. This would also cause Intellij to warn about useless checks for `null` on a parameter marked with `@NotNull`.
2) More importantly, we require `requireNotFrozen()` in each setter to make sure a frozen request is not being modified after it has been frozen, but I have not found a way to add this line in the generated setters.
