### ISSUE TITLE
Shall we have 'generated javadoc' hosted in GitHub?

### ISSUE THREAD

**Issue by rafialhamd** [hashgraph/hedera-sdk-java#6]
@gregscullard @kenthejr 

It would be useful to have the '_Generated JavaDoc_' and available in the repository.
Better yet, it's **hosted in GitHub**.

It'll be easier for navigation and learning about API, instead of going through the Source Code documentation.

Thanks!

**Comment by gregscullard** [comment]
The next version will generate javadoc in the project under a "javadoc" folder in addition to creating a jar in the /target folder (the .jar is required for publication to sonatype).

**Comment by gregscullard** [comment]
The next release for the sdk will be a maintenance release which will include java docs in a folder amongst other things.

**Comment by rafialhamd** [comment]
Newly generated javadoc files are under folder `apidocs`.

https://github.com/hashgraph/hedera-sdk-java/tree/v0.2.1/sdk/apidocs

It's better by convention that it's named as `javadoc`.

Thanks!

**Comment by rafialhamd** [comment]
Issue is addressed. Closing the issue.
**_Still the above recommendation to rename `apidocs` to `javadoc` is valid!_**

Thanks!

**Comment by gregscullard** [comment]
Version 0.2.1 will change this to javadoc per your recommendation

**Comment by calvinchengx** [comment]
@gregscullard we can autogen into markdown, integrate it with handwritten documentation and host it on github pages.
