### ISSUE TITLE
Unnecessary use of synchronized

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-sdk-java#633]
### Problem

`Client` and its related classes use the `synchronized` keyword liberally. In most of these cases, it is overkill and could be replaced with simpler thread safe mechanisms like `volatile`, atomic classes, thread safe data structures or immutable objects. This can impact performance when using the SDK at scale like we do in the mirror node monitor tool.

### Solution

Evaluate `Client` and other classes and switch to more performant, thread-safe mechanisms.

**Comment by danielakhterov** [comment]
@steven-sheehy How often do you guys change the client configuration after the initialization phase? I'm wondering we want to have some sort of client builder which builds a client that can no longer be changed. Also, what about if the entire client configuration were to be in the config file so when you do `Client.fromConfig()` you'd get an immutable `Client`. #574

**Comment by steven-sheehy** [comment]
Not often. But the performance problem isn't on the setters but the use of synchronized on getters. Though the biggest slowdown is probably `Network.getNodeAccountIdsForExecute()`. I don't think we need a wholescale refactor, just need to make the current approach more performant. I will work on a PR that fixes the low hanging fruit.
