### ISSUE TITLE
Code coverage report is not beign genererated for PRs

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-java#639]
### Description

https://github.com/hashgraph/hedera-sdk-java/pull/637#discussion_r690769783

### Steps to reproduce

Create a PR

### Hedera network

other

### Version

main

### Operating system

Linux

**Comment by Sean-Tedrow-LB** [comment]
Is this still an issue?  I see the code coverage report being generated in PRs, but I haven't paid close attention.

**Comment by steven-sheehy** [comment]
It looks like codecov.io has started to work again at some point. It would be nice to figure out how to get code coverage to work in SonarCloud to consolidate, but probably not that important.
