### ISSUE TITLE
Double deduction of Account query fee

### ISSUE THREAD

**Issue by rafialhamd** [hashgraph/hedera-sdk-java#64]
**Issue summary:**

As per the current setup, the cost of account query is 100000 Tinybars.
But, 200000 Tinybars is deducted.
--

**OS version:**

macOS Mojave 
Version 10.14.1 (18B75)

--
**Java -version**
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

--
**Source code:**
[HederaAccountTest.java](https://gist.github.com/rafialhamd/a47f6a05a56dcd17fd990ece9171ac2c)

--
**Test output:**

**Run 1** [log](https://gist.github.com/rafialhamd/e326713114d2433339b581fe422646ec):

```
header {
    cost: 100000
  }
  accountID {
    accountNum: 1001
  }
  balance: 100498205000
}

```
**Run 2** [log](https://gist.github.com/rafialhamd/18d7db6b14ee147d47c5b79c7a258236):

```
  header {
    cost: 100000
  }
  accountID {
    accountNum: 1001
  }
  balance: 100498005000
}

```
--
**Issue:**

First run balance:
100498205000

Second run balance:
100498005000

According to the 'cost' metioned, which is, 100000 TinyBars, the call should return a balance of 100498105000 instead of 100498005000.

This needs to be fixed.
--

**Comment by lbaird** [comment]
This behavior is correct.  The user pays the node 100,000 tinybars to get the answer. That payment is done by creating a cryptocurrency transfer transaction, to transfer 100,000 tinybars. That transaction has a transaction fee of 100,000 tinybars. So the client’s account balance goes down by 200,000.

**Comment by rafialhamd** [comment]
Wonderful...!
Now, I've a better understanding of Hedera Hashgraph... :-)

Thanks!
