### ISSUE TITLE
Make token association optional

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#654]
### Problem

The need to associate a wallet with a certain token in order to be able to receive this token on the wallet poses usabity issues and makes some business flows that are common practice in the blockchain and NFT space impossible.

HIP: https://github.com/ArkaneNetwork/hedera-improvement-proposal/blob/master/HIP/hip-0000-makeTokenAssociationOptIn.md

### Solution

The proposal is to remove the need to explicitly associate a wallet with a token. It can be optional for specific wallets to choose to make token assiciation required on an opt-in basis.

**Comment by danielakhterov** [comment]
I'm not sure what the SDK needs to do here. If Hedera Services makes token association optional it shouldn't change anything in the SDK. Perhaps examples/tests could be updated to remove the extra `TokenAssociateTransaction` call, but besides that I don't think there is anything the SDK needs to update.

**Comment by SimiHunjan** [comment]
There are protobuf changes that would impact the SDK are listed here: https://github.com/hashgraph/hedera-protobufs/pull/81/files 
Along with new response codes: https://github.com/hashgraph/hedera-protobufs/pull/83

**Comment by danielakhterov** [comment]
Ah, I see; that makes sense. How come that HIP doesn't have a number attached to it? We should probably standardize how we add new features to the SDKs following the HIP proposal number. Something like, "Add support for HIP-N".

**Comment by SimiHunjan** [comment]
I've pinged the team about updating the HIP number and content to match what was finalized. In general, the HIP should have an assigned number before it is implemented. 

I think the sounds good to me.
