### ISSUE TITLE
Request to prefix artifact-id with 'hedera'

### ISSUE THREAD

**Issue by rafialhamd** [hashgraph/hedera-sdk-java#69]
Few artifactIds are named as **`java-sdk-full`** and **`java-sdk`**, in the pom.xml files.
These should be renamed as **`hedera-java-sdk-full`** and **`hedera-java-sdk`**, respectively.

Though they're unique in the maven repo, it's _not helpful to locate the hedera related sdk jars_ under lib directory.

For example:

```
myMac:hh-core admin$ ls -ltr target/libs/ | grep hedera
-rw-r--r--  1 admin  staff    44612 Jan 15 17:43 hedera-sdk-java-examples-0.2.0.jar
myMac:hh-core admin$ 
```

But, a generic search brings a java sdk (which should have been a hedera sdk)!

```
myMac:hh-core admin$ ls -ltr target/libs/ | grep sdk
-rw-r--r--  1 admin  staff   223679 Jan 15 17:43 java-sdk-0.2.0.jar
-rw-r--r--  1 admin  staff    44612 Jan 15 17:43 hedera-sdk-java-examples-0.2.0.jar
myMac:hh-core admin$ 
```

**Another potential problem** is that, if someone publishes an artifactId with the SIMILAR name `java-sdk`, like below, this will cause confusions and/or conflicts - besides, it will be difficult to isolate the problem.

```
<groupId>com.example.company</groupId>
<artifactId>java-sdk</artifactId>
<version>0.2.0</version>
<packaging>jar</packaging>
```

So, I strongly recommend that, all the hedera related artifacts are prefixed with 'hedera' or something similar and unique.

Thanks!

**Comment by gregscullard** [comment]
Fixed in v0.2.1. thanks for the suggestion
