### ISSUE TITLE
cannot get transaction records

### ISSUE THREAD

**Issue by saahmadi** [hashgraph/hedera-sdk-java#702]
### Description

i want to get Account transaction record but it return 0 size
when i see in the explorer show all transactions
List<TransactionRecord> transactionRecords = new AccountRecordsQuery().setAccountId(AccountId.fromString("0.0.413561"))
                .execute(client);

### Steps to reproduce

List<TransactionRecord> transactionRecords = new AccountRecordsQuery().setAccountId(AccountId.fromString("0.0.413561"))
                .execute(client);

### Hedera network

mainnet

### Version

2.0.14

### Operating system

Windows

**Comment by danielakhterov** [comment]
Have you made transactions within the last 180 seconds of making that request? Also, _I could be wrong_, but I believe `mainnet` does not yet support this feature.
