### ISSUE TITLE
Unable to cancel API calls

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-sdk-java#703]
### Description

The SDK does not properly handle a cancellation request for the `CompletableFuture` it returns from its APIs. This causes the asynchronous thread to continue to retry failing API calls in the background until it either succeeds or reaches its max attempts (which is upwards of 50 seconds by default).

This can become a serious problem when testing at high TPS as receipts are more likely to fail and the background retry threads can pile up and cause resource exhaustion.

It seems like `Executable` has some code that attempts to cancel the gRPC request, but due to use of chaining futures this doesn't actually get invoked in practice. Once fixed, please add a test that verifies this works.

### Steps to reproduce

1. Invoke an API call that will take a number of retries to succeed (like getting a receipt)
2. Cancel the call
3. The SDK thread continues to attempt to retry the get receipt in the background as evidenced by the logs

```java
        Client client = Client.forTestnet();
        client.setOperator(OPERATOR_ID, OPERATOR_KEY);
        CompletableFuture<TransactionReceipt> future = TransactionId.generate(OPERATOR_ID).getReceiptAsync(client);
        future.cancel(true);
        System.out.println("Future cancelled=" + future.isCancelled());
        System.out.println("Future done=" + future.isDone());
        System.out.println("Future completedExceptionally=" + future.isCompletedExceptionally());
        Thread.sleep(60_000);
```

```
Future cancelled=true
Future done=true
Future completedExceptionally=true
[hedera-sdk-4] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.3 in 250 ms after failure during attempt #1: RECEIPT_NOT_FOUND
[hedera-sdk-10] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.4 in 500 ms after failure during attempt #2: RECEIPT_NOT_FOUND
[hedera-sdk-2] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.3 in 1000 ms after failure during attempt #3: RECEIPT_NOT_FOUND
[hedera-sdk-6] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.4 in 2000 ms after failure during attempt #4: RECEIPT_NOT_FOUND
[hedera-sdk-10] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.3 in 4000 ms after failure during attempt #5: RECEIPT_NOT_FOUND
[hedera-sdk-0] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.4 in 8000 ms after failure during attempt #6: RECEIPT_NOT_FOUND
[hedera-sdk-4] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.3 in 8000 ms after failure during attempt #7: RECEIPT_NOT_FOUND
[hedera-sdk-7] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.4 in 8000 ms after failure during attempt #8: RECEIPT_NOT_FOUND
[hedera-sdk-10] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.3 in 8000 ms after failure during attempt #9: RECEIPT_NOT_FOUND
[hedera-sdk-0] WARN com.hedera.hashgraph.sdk.TransactionReceiptQuery - Retrying node 0.0.4 in 8000 ms after failure during attempt #10: RECEIPT_NOT_FOUND
```

### Additional context

We could workaround this issue if #585 was implemented as it would allow us to leverage our own threading model.

### Hedera network

testnet

### Version

v2.0.14

### Operating system

macOS

**Comment by danielakhterov** [comment]
Did a quick search, and this seems to be intentional? https://stackoverflow.com/questions/23320407/how-to-cancel-java-8-completable-future

**Comment by steven-sheehy** [comment]
Right, I understand it's not automatically cancelling the chain. You have to manually pass the cancellation through unfortunately. Something like this:

```java
public CompletableFuture<O> executeAsync(Client client) {
...
    AtomicReference<CompletableFuture<String>> futureReference = new AtomicReference<>();
    BooleanSupplier cancelled = () -> futureReference.get() == null || futureReference.get().isCancelled();
    CompletableFuture<O> future = onExecuteAsync(client).thenCompose((v) -> {
...
                    return executeAsync(client, 1, null, cancelled);
    });
    futureReference.set(future);
    return future;
}
```

Then pass the cancellation supplier and use it anywhere that can take a long time like the thread sleeps. Instead of sleeping for 8s you'd sleep for milliseconds and check for cancellation:

```java
    var stopAt = Instant.now().plusSeconds(8L);
    while (!cancelled.getAsBoolean() && Instant.now().isBefore(stopAt)) {
        Thread.sleep(250L);
    }
```
