### ISSUE TITLE
How to send message 

### ISSUE THREAD

**Issue by hieudoanduc** [hashgraph/hedera-sdk-java#71]
How to send message on transaction?

**Comment by rafialhamd** [comment]
At the moment, it's not possible to send, 'message of any size' as you would do in Ethereum.
But, you can make use of **'memo' field** to send a 'note' like information.

This 'memo' field will *not* be stored on the ledger forever.
You need to find alternate ways to keep the data/message in the hedera network, permanently.
The only way, at the moment, is to make use of **file storage**.
