### ISSUE TITLE
Each integration test should indicate which networks it's supported on exit early otherwise

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-java#723]
### Problem

There are multiple networks a person can run the integration tests against:
 - `previewnet`
 - `testnet`
 - `mainnet`
 - `integrationnet`
 - `localhost`

Since each network has different features it supports it would make sense for each test to confirm it's running against a network it's expected to pass on. At the moment we simply disable any test that doesn't succeed on `testnet`, but that is a bit of a hack.

### Solution

Each test should check `Client.getNetworkName()` and confirm it's running against the correct network(s).

**Comment by steven-sheehy** [comment]
That sounds brittle. You really only need to feature flag new features and make sure the test only runs on environments its supports. Then as they get rolled out to mainnet you can remove those feature flags. Are you aware of any features that only work on mainnet and not preceding environments?

Regardless, would suggest using JUnit's `@EnabledIf` or `@DisabledIf` and its variants thereof. You can also write a custom annotation if those don't suffice that uses a custom `ExecutionCondition` to centralize the logic.

**Comment by danielakhterov** [comment]
> That sounds brittle.

I don't disagree.

> Are you aware of any features that only work on mainnet and not preceding environments?

I haven't experienced any issues with breaking changes from testnet to mainnet, but I have with previewnet and testnet

> Regardless, would suggest using JUnit's @EnabledIf or @DisabledIf and its variants thereof. You can also write a custom annotation if those don't suffice that uses a custom ExecutionCondition to centralize the logic.

This sounds like a reasonable thing to do.

> You really only need to feature flag new features and make sure the test only runs on environments its supports

I'm not entirely sure if feature flags are the best choice here because sometimes the same feature works slightly different between previewnet and testnet. That is why I thought it'd be a good idea to have each test indicate which network it should run on. However, perhaps I'm not entirely understanding what you mean by feature flags; my current understanding is that it is probably environment variables that enable test for e.g. custom fees. Continuing with the custom fee example; if custom fee functionality differs on previewnet compared to testnet then running some of the existing custom fee tests would fail. This means the daily previewnt CI would fail, but more importantly it makes it more difficult to develop the SDK if you have to keep in mind which custom fee tests are allowed to fail. However, if each test specified which networks it supports we'd be able to have several custom fee integration tests that test the specific functionality on the a specific network.

**Comment by danielakhterov** [comment]
Moving this to discussion: https://github.com/hashgraph/hedera-sdk-java/discussions/725
