### ISSUE TITLE
Error in mapping documentation. Line 829 of HederaContract.java

### ISSUE THREAD

**Issue by JaimeSilver** [hashgraph/hedera-sdk-java#75]
hedera-sdk-java/sdk/src/main/java/com/hedera/sdk/contract/HederaContract.java
Release  0.3.0
Java SDK

--------------------- Issue: mvn install fails. ----------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc (attach-javadocs) on project hedera-java-sdk: An error has occurred in Javadoc report generation:
[ERROR] Exit code: 1 - C:\Swirlds\hedera-sdk-java-0.3.0\sdk\src\main\java\com\hedera\sdk\contract\HederaContract.java:829: error: @param name not found
[ERROR] * @param accountID accountID of the account records being queried
[ERROR] ^
[ERROR] C:\Swirlds\hedera-sdk-java-0.3.0\sdk\src\main\java\com\hedera\sdk\contract\HederaContract.java:833: warning: no @param for contractID
[ERROR] public boolean getRecords(HederaTransaction payment, HederaQueryHeader.QueryResponseType responseType, HederaContractID contractID) throws InterruptedException {

----------------------------Correction -----------------------
Line 829 @param accountID accountID of the account records being queried
does not map the parameters. 
replace with * @param contractID contractID of the contract records being queried

**Comment by gregscullard** [comment]
Corrected in last commit. Thank you
