### ISSUE TITLE
2.3.0 sdk-jdk7 version crashes on some Android versions

### ISSUE THREAD

**Issue by timmolter** [hashgraph/hedera-sdk-java#756]
### Description

Here's the error in the console:

```
Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 5:
^(?<address>\S+):(?<port>\d+)$
     ^
	at java.util.regex.Pattern.compileImpl(Native Method)
	at java.util.regex.Pattern.compile(Pattern.java:411)
	at java.util.regex.Pattern.<init>(Pattern.java:394)
	at java.util.regex.Pattern.compile(Pattern.java:381)
	at com.hedera.hashgraph.sdk.ManagedNodeAddress.<clinit>(ManagedNodeAddress.java:8)
```

Something about this regex, Android doesn't like. Only some versions though. 

Downgrading to 2.2.0 fixes the issue.

### Steps to reproduce

1. build our Android app with 2.3.0 jar as a dependency and run it.

### Hedera network

mainnet

### Version

2.3.0

### Operating system

Other

**Comment by SimiHunjan** [comment]
@danielakhterov @Sean-Tedrow-LB did either of you get a chance to review this?

**Comment by danielakhterov** [comment]
Yes and no. I created a separate project that used Java 7 and copied over the regexes we used, but when compiling there were no issues. I did just realize that perhaps I should run the Java 7 project, but I just don't see why compiling would work, but running would not. Nonetheless I'll try.

**Comment by timmolter** [comment]
Strange stuff can happen on old versions of Android due to namespace clashes. If `java.util.regex` is somehow loaded by the Android runtime from an Android-packaged library that clashes with your compile-time JDK, stuff like this can occur. And it's almost impossible to test. I've seen this with other parts of your SDK and have submitted PRs to fix it. So while I don't know exactly how to fix this one, it is definitely a problem. Maybe you can not use a regex or refactor the code in some way??

**Comment by danielakhterov** [comment]
Which Android API version do you guys compile for? Looking at https://developer.android.com/reference/java/util/regex/Pattern named groups are only supported as of API 26.

**Comment by timmolter** [comment]
Android 4. So level 17 therabouts.

**Comment by timmolter** [comment]
But just compiling for it doesn't always catch the runtime errors.
