### ISSUE TITLE
Make callLocal PUBLIC so multiple entries can be returned at once.

### ISSUE THREAD

**Issue by JaimeSilver** [hashgraph/hedera-sdk-java#76]
https://github.com/hashgraph/hedera-sdk-java/blob/9ed59876032d39aa620d559d2c208e0718484529/examples/src/main/java/com/hedera/examples/contractWrappers/ContractFunctionsWrapper.java#L120

**Comment by mehcode** [comment]
@JaimeSilver In the new SDK ( currently unreleased in [`develop`](https://github.com/hashgraph/hedera-sdk-java/tree/develop) ) this is exposed as follows: 

Example of usage: https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/com/hedera/sdk/examples/advanced/CreateSimpleContract.java#L77

`FunctionResult`: https://github.com/hashgraph/hedera-sdk-java/blob/develop/src/main/java/com/hedera/sdk/FunctionResult.java#L12

**Comment by gregscullard** [comment]
Fixed in release/0.3.0

**Comment by JaimeSilver** [comment]
Hi Ryan,

That works.

Thanks, Jaime
