### ISSUE TITLE
`Executable.execute(Client, Duration)` ignores timeout

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-java#786]
### Description

Method ignores timeout.

### Steps to reproduce

Use the method.

### Hedera network

mainnet, testnet, previewnet

### Version

v2.4.0

### Operating system

Linux

**Comment by dalvizu** [comment]
I am running into this issue in our synthetic monitoring. Is there an alternative way of calling the SDK to get this behavior, or does this affect all methods used to call the API?

**Comment by danielakhterov** [comment]
I believe if you call the `executeAsync()` method instead you'd get the functionality you desire although that method constructs futures which might way down on performance a bit.
