### ISSUE TITLE
Add schedule transfer test

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#802]
### Problem

Add the following test to the SDK test suite.

1. User sends CryptoTransfer to a specific Hedera Account and two things are initiated from that:
2. 9 nodes submit `ScheduleCreate` containing `CryptoTransfer`
3. 8 of those `ScheduleCreate` fail with `IDENTICAL_TX_CREATED`
4. 8 of those that fail, create `ScheduleSign`
5. When 5/9 sign the Scheduled Entity, the underlying `CryptoTransfer` is executed
6. 9 nodes submit a `ConsensusMessage` to an already existing `Topic` that has `5/9` threshold key list

### Solution

See above.

**Comment by danielakhterov** [comment]
I believe this should be closed now since we do not require e2e tests anymore.
