### ISSUE TITLE
HederaTransactionState uses HashMap with synchronized blocks

### ISSUE THREAD

**Issue by jcdang** [hashgraph/hedera-sdk-java#81]
https://github.com/hashgraph/hedera-sdk-java/blob/b71bd275a916dd8ae796eafd71d788b101128f4c/sdk/src/main/java/com/hedera/sdk/common/HederaTransactionState.java#L24

I'd suggest using a ConcurrentHashMap.

**Comment by gregscullard** [comment]
Fixed in release/0.3.0
