### ISSUE TITLE
HederaSignatureThreshold constructor line does not do what comment says

### ISSUE THREAD

**Issue by jcdang** [hashgraph/hedera-sdk-java#82]
https://github.com/hashgraph/hedera-sdk-java/blob/13757097f88593b835e953ec3d30829a6a868247/sdk/src/main/java/com/hedera/sdk/common/HederaSignatureThreshold.java#L50-L51

All this line does is clear an empty list.

**Comment by gregscullard** [comment]
SignatureThresholds will be deprecated in the next version of HAPI to be replaced with flat lists of signatures. This class no longer exists in the new (0.3.0) SDK as a result.
