### ISSUE TITLE
Many of the Classes in the sdk implement the Java Serializable interface but do not follow it's rules

### ISSUE THREAD

**Issue by jcdang** [hashgraph/hedera-sdk-java#83]
They implement the interface but do not follow the contractual requirements.

Using protobuf is not the same thing as using Java Serializable.

- method readObject is required
- method writeObject is required

**Comment by gregscullard** [comment]
The legacy SDKs in release/0.3.x or release/0.2.x are in maintenance mode and for backwards compatibility with existing projects.
