### ISSUE TITLE
Fix broken methods

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#843]
### Description

`Client.setRequestTimeout()`
`Executable.execute(client, timeout)`

These methods do not work.

### Steps to reproduce

Use `Client.setRequestTimeout()` and `Executable.execute(client, timeout)`

### Hedera network

other

### Version

current

**Comment by danielakhterov** [comment]
Fixed on `develop` https://github.com/hashgraph/hedera-sdk-java/commit/7d8f06d23c807dc2ead62b12ba1a3932dc4d3241
