### ISSUE TITLE
Update default mirror endpoint to use public

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#890]
### Problem

The private mirror node is listed as the mirror node endpoint in the SDKs.

### Solution

Update to the public mirror node endpoint.

**Comment by Sean-Tedrow-LB** [comment]
This [was addressed](https://github.com/hashgraph/hedera-sdk-java/blob/efa642765ba8e1f17849b7332bf4bdf1a4d022f6/sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java#L63) by [PR #1093 ](https://github.com/hashgraph/hedera-sdk-java/pull/1093)
