### ISSUE TITLE
NFT allowance in Account Info is missing isApproveForAll flag

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-sdk-java#918]
### Description

GetAccountInfo is missing the isApproveForAll flag for the NFT allowances. 

```
NFT Allowances : 
[TokenNftAllowance{tokenId=0.0.2165, ownerAccountId=null, spenderAccountId=0.0.2158, serials=null}]
```

here the spender `0.0.2158` has allowance for all serials on the owner for NFT `0.0.2165` 

But this information is missing the info.

### Steps to reproduce

Create a owner account, spender account and an NFT token.
grant allowance on NFT token of the owner to the spender with `approveForAll` set true.

get Account info on owner doest not show this flag. 

### Hedera network

previewnet

### Version

0.24

**Comment by Sean-Tedrow-LB** [comment]
In the SDK, a `TokenNftAllowance` with `serials == null` serializes into an `NftAllowance` protobuf message with `approvedForAll == true`.  Is this issue merely requesting a change to the `toString()` implementation to make this appear unambiguous?  If so, that's easy enough.

**Comment by anighanta** [comment]
yes Sean, I think tweaking the toString() method would do I think
