### ISSUE TITLE
Enable the SDK to retrieve a record even if a transaction failed

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#969]
### Problem

Right now, getRecord does a getReceipt first and if the status isn’t SUCCESS, it throws an exception.

There are cases when being able to get a record for a failed transaction does make sense, and it would be desirable to be able to override the exception being thrown.

### Solution

Add support for this feature.

**Comment by mehcode** [comment]
The idea was always to do `new TransactionRecordQuery()` manually if you want a failing record/receipt. That path does not error.

---

Given a time machine, I agree that I would have done something like this in examples:

```java
var record = transactionResponse.getRecord(client).throwOnStatus();
```

And this would work without exception

```java
var record = transactionResponse.getRecord(client);
```

---

Until we do a v3, I'd record we have something like `.forceGetRecord` or something. It's a bit of a sledgehammer approach but it'll be obvious to people.

**Comment by gregscullard** [comment]
Hi, I'm not sold on `forceGetRecord` as a name, not quite sure what to suggest but how about something along the lines of `getRecordNoThrow` or `getRecordWithoutException`.

**Comment by rickyrodmac** [comment]
Since I just used what Ryan suggested above a name change would not bother me. I've had experience where the convention was to prepend `try` to calls that could throw an exception. It does not look that hadera has adopted it.
Right now there are 3 options: 
- `forceGetRecord`
- `getRecordNoThrow`
- `getRecordWithoutException`
I would like to suggest: `getRecordNoException`

**Comment by danielakhterov** [comment]
@gregscullard @mehcode 
Actually, thinking on this why do we even have `forceGetRecord()` at all? If we were to support `TransactionResponse.getRecordQuery()` all the user would need to do is add `execute` and it'll behave much like you'd expect.
