### ISSUE TITLE
`tranferToCrypto` not populating the returned object

### ISSUE THREAD

**Issue by bchevallereau** [hashgraph/hedera-sdk-java#98]
When I call “transferCryptoTo” from the client, I get a Transaction ID but it seems that this one has no account ID populated or valid start.

**Comment by abonander** [comment]
This should be fixed now. Please try with the latest `master` (we're still working on getting out a release) and let me know if this is still happening.

**Comment by bchevallereau** [comment]
Updated from `master`, installed locally `0.5.0`, re-tested my code and everything was populated as expected:

```
{
  "accountID": {
    "shardNum": 0,
    "realmNum": 0,
    "accountNum": 1274
  },
  "transactionValidStart": "2019-06-15T12:54:17Z"
}
```

Ticket can be closed.
